# Databricks notebook source
# MAGIC %md
# MAGIC # DWH.FactAccountsPayable.Table
# MAGIC This notebook was automatically converted from the script below. It may contain errors, so use it as a starting point and make necessary corrections.
# MAGIC
# MAGIC Source script: `/Volumes/dbe_dbx_internships/switchschema/switchvolume/input-20260323134003-blyy/DWH.FactAccountsPayable.Table.sql`

# COMMAND ----------

# --------------------------------------------------
# Set the catalog to one the user has READ_METADATA permission on
# --------------------------------------------------
spark.sql("USE CATALOG spark_catalog")   # Adjust if a different catalog is appropriate

# COMMAND ----------

# --------------------------------------------------
# Setup: ensure the target database exists
# --------------------------------------------------
spark.sql("CREATE DATABASE IF NOT EXISTS DWH")

# COMMAND ----------

# --------------------------------------------------
# Create the FactAccountsPayable Delta table
# --------------------------------------------------
# NOTE:
# - IDENTITY columns are supported via GENERATED BY DEFAULT AS IDENTITY.
# - PRIMARY KEY and FOREIGN KEY constraints are not enforced in Delta Lake;
#   they are omitted or left as comments for reference.
spark.sql("""
CREATE OR REPLACE TABLE DWH.FactAccountsPayable (
    FactAccountsPayableId BIGINT GENERATED BY DEFAULT AS IDENTITY,   -- IDENTITY(1,1)
    DimCompanyId INT NOT NULL,
    DimPurchaseInvoiceId INT NOT NULL,
    DimIsOpenAmountId BOOLEAN NOT NULL,
    DimOutstandingPeriodId INT NOT NULL,
    DimSupplierId INT NOT NULL,
    DimTransactionCurrencyId INT NOT NULL,
    DimAccountingCurrencyId INT NOT NULL,
    DimReportingCurrencyId INT NOT NULL,
    DimGroupCurrencyId INT NOT NULL,
    DimReportDateId INT NOT NULL,
    DimDueDateId INT NOT NULL,
    ReportMonthId INT,
    InvoiceDate TIMESTAMP NOT NULL,
    LastPaymentDate TIMESTAMP NOT NULL,
    DocumentDate TIMESTAMP NOT NULL,
    RecId BIGINT NOT NULL,                     -- Replaced LONG with BIGINT (Spark SQL type)
    PayablesVoucher STRING NOT NULL,
    Description STRING NOT NULL,
    InvoiceAmountTC DECIMAL(38,6),
    InvoiceAmountAC DECIMAL(38,6),
    InvoiceAmountRC DECIMAL(38,6),
    InvoiceAmountGC DECIMAL(38,6),
    InvoiceAmountAC_Budget DECIMAL(38,6),
    InvoiceAmountRC_Budget DECIMAL(38,6),
    InvoiceAmountGC_Budget DECIMAL(38,6),
    PaidAmountTC DECIMAL(38,6),
    PaidAmountAC DECIMAL(38,6),
    PaidAmountRC DECIMAL(38,6),
    PaidAmountGC DECIMAL(38,6),
    PaidAmountAC_Budget DECIMAL(38,6),
    PaidAmountRC_Budget DECIMAL(38,6),
    PaidAmountGC_Budget DECIMAL(38,6),
    OpenAmountTC DECIMAL(38,6),
    OpenAmountAC DECIMAL(38,6),
    OpenAmountRC DECIMAL(38,6),
    OpenAmountGC DECIMAL(38,6),
    OpenAmountAC_Budget DECIMAL(38,6),
    OpenAmountRC_Budget DECIMAL(38,6),
    OpenAmountGC_Budget DECIMAL(38,6),
    AppliedExchangeRateTC DECIMAL(38,6),
    AppliedExchangeRateAC DECIMAL(38,6),
    AppliedExchangeRateRC DECIMAL(38,6),
    AppliedExchangeRateGC DECIMAL(38,6),
    AppliedExchangeRateAC_Budget DECIMAL(38,6),
    AppliedExchangeRateRC_Budget DECIMAL(38,6),
    AppliedExchangeRateGC_Budget DECIMAL(38,6),
    CreatedETLRunId INT NOT NULL,
    ModifiedETLRunId INT NOT NULL,
    DimVoucherId INT
)
""")

# COMMAND ----------

# MAGIC %md
# MAGIC ## Static Syntax Check Results
# MAGIC These are errors from static syntax checks. Manual corrections are required for these errors.
# MAGIC ### Spark SQL Syntax Errors
# MAGIC ```
# MAGIC Error in query 1: (org.apache.spark.SparkSecurityException) [INSUFFICIENT_PERMISSIONS] Insufficient privileges:
# MAGIC User does not have permission READ_METADATA on CATALOG. SQLSTATE: 42501
# MAGIC Error in query 2: [PARSE_SYNTAX_ERROR] Syntax error at or near end of input. SQLSTATE: 42601 (line 1, pos 2009)
# MAGIC
# MAGIC == SQL ==
# MAGIC EXPLAIN CREATE OR REPLACE TABLE DWH.FactAccountsPayable (     FactAccountsPayableId BIGINT GENERATED BY DEFAULT AS IDENTITY,   -- IDENTITY(1,1)     DimCompanyId INT NOT NULL,     DimPurchaseInvoiceId INT NOT NULL,     DimIsOpenAmountId BOOLEAN NOT NULL,     DimOutstandingPeriodId INT NOT NULL,     DimSupplierId INT NOT NULL,     DimTransactionCurrencyId INT NOT NULL,     DimAccountingCurrencyId INT NOT NULL,     DimReportingCurrencyId INT NOT NULL,     DimGroupCurrencyId INT NOT NULL,     DimReportDateId INT NOT NULL,     DimDueDateId INT NOT NULL,     ReportMonthId INT,     InvoiceDate TIMESTAMP NOT NULL,     LastPaymentDate TIMESTAMP NOT NULL,     DocumentDate TIMESTAMP NOT NULL,     RecId BIGINT NOT NULL,                     -- Replaced LONG with BIGINT (Spark SQL type)     PayablesVoucher STRING NOT NULL,     Description STRING NOT NULL,     InvoiceAmountTC DECIMAL(38,6),     InvoiceAmountAC DECIMAL(38,6),     InvoiceAmountRC DECIMAL(38,6),     InvoiceAmountGC DECIMAL(38,6),     InvoiceAmountAC_Budget DECIMAL(38,6),     InvoiceAmountRC_Budget DECIMAL(38,6),     InvoiceAmountGC_Budget DECIMAL(38,6),     PaidAmountTC DECIMAL(38,6),     PaidAmountAC DECIMAL(38,6),     PaidAmountRC DECIMAL(38,6),     PaidAmountGC DECIMAL(38,6),     PaidAmountAC_Budget DECIMAL(38,6),     PaidAmountRC_Budget DECIMAL(38,6),     PaidAmountGC_Budget DECIMAL(38,6),     OpenAmountTC DECIMAL(38,6),     OpenAmountAC DECIMAL(38,6),     OpenAmountRC DECIMAL(38,6),     OpenAmountGC DECIMAL(38,6),     OpenAmountAC_Budget DECIMAL(38,6),     OpenAmountRC_Budget DECIMAL(38,6),     OpenAmountGC_Budget DECIMAL(38,6),     AppliedExchangeRateTC DECIMAL(38,6),     AppliedExchangeRateAC DECIMAL(38,6),     AppliedExchangeRateRC DECIMAL(38,6),     AppliedExchangeRateGC DECIMAL(38,6),     AppliedExchangeRateAC_Budget DECIMAL(38,6),     AppliedExchangeRateRC_Budget DECIMAL(38,6),     AppliedExchangeRateGC_Budget DECIMAL(38,6),     CreatedETLRunId INT NOT NULL,     ModifiedETLRunId INT NOT NULL,     DimVoucherId INT )
# MAGIC -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------^^^
# MAGIC ```
