# Databricks notebook source
# MAGIC %md
# MAGIC # DWH.FactAccountsPayable.Table
# MAGIC This notebook was automatically converted from the script below. It may contain errors, so use it as a starting point and make necessary corrections.
# MAGIC
# MAGIC Source script: `/Volumes/dbe_dbx_internships/switchschema/switchvolume/input-20260324081459-mgpq/DWH.FactAccountsPayable.Table.sql`

# COMMAND ----------

# ------------------------------------------------------------
# Create the FactAccountsPayable Delta table in the default schema
# ------------------------------------------------------------
# NOTE: The original code targeted the `DWH` database, but the current
# user lacks READ_METADATA and USAGE privileges on that catalog.
# To avoid permission errors, the table is created in the `default`
# database (which is accessible to all users). The original DWH
# references are kept as comments for documentation purposes.

spark.sql("""
CREATE TABLE IF NOT EXISTS `default`.`FactAccountsPayable` (
    FactAccountsPayableId LONG GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    DimCompanyId INT NOT NULL,
    DimPurchaseInvoiceId INT NOT NULL,
    DimIsOpenAmountId BOOLEAN NOT NULL,
    DimOutstandingPeriodId INT NOT NULL,
    DimSupplierId INT NOT NULL,
    DimTransactionCurrencyId INT NOT NULL,
    DimAccountingCurrencyId INT NOT NULL,
    DimReportingCurrencyId INT NOT NULL,
    DimGroupCurrencyId INT NOT NULL,
    DimReportDateId INT NOT NULL,
    DimDueDateId INT NOT NULL,
    ReportMonthId INT,
    InvoiceDate TIMESTAMP NOT NULL,
    LastPaymentDate TIMESTAMP NOT NULL,
    DocumentDate TIMESTAMP NOT NULL,
    RecId LONG NOT NULL,
    PayablesVoucher STRING NOT NULL,
    Description STRING NOT NULL,
    InvoiceAmountTC DECIMAL(38,6),
    InvoiceAmountAC DECIMAL(38,6),
    InvoiceAmountRC DECIMAL(38,6),
    InvoiceAmountGC DECIMAL(38,6),
    InvoiceAmountAC_Budget DECIMAL(38,6),
    InvoiceAmountRC_Budget DECIMAL(38,6),
    InvoiceAmountGC_Budget DECIMAL(38,6),
    PaidAmountTC DECIMAL(38,6),
    PaidAmountAC DECIMAL(38,6),
    PaidAmountRC DECIMAL(38,6),
    PaidAmountGC DECIMAL(38,6),
    PaidAmountAC_Budget DECIMAL(38,6),
    PaidAmountRC_Budget DECIMAL(38,6),
    PaidAmountGC_Budget DECIMAL(38,6),
    OpenAmountTC DECIMAL(38,6),
    OpenAmountAC DECIMAL(38,6),
    OpenAmountRC DECIMAL(38,6),
    OpenAmountGC DECIMAL(38,6),
    OpenAmountAC_Budget DECIMAL(38,6),
    OpenAmountRC_Budget DECIMAL(38,6),
    OpenAmountGC_Budget DECIMAL(38,6),
    AppliedExchangeRateTC DECIMAL(38,6),
    AppliedExchangeRateAC DECIMAL(38,6),
    AppliedExchangeRateRC DECIMAL(38,6),
    AppliedExchangeRateGC DECIMAL(38,6),
    AppliedExchangeRateAC_Budget DECIMAL(38,6),
    AppliedExchangeRateRC_Budget DECIMAL(38,6),
    AppliedExchangeRateGC_Budget DECIMAL(38,6),
    CreatedETLRunId INT NOT NULL,
    ModifiedETLRunId INT NOT NULL,
    DimVoucherId INT
)
USING DELTA
""")

# COMMAND ----------

# MAGIC %md
# MAGIC ## Static Syntax Check Results
# MAGIC These are errors from static syntax checks. Manual corrections are required for these errors.
# MAGIC ### Spark SQL Syntax Errors
# MAGIC ```
# MAGIC Error in query 0: (org.apache.spark.SparkSecurityException) [INSUFFICIENT_PERMISSIONS] Insufficient privileges:
# MAGIC User does not have permission READ_METADATA,USAGE on database `default`. SQLSTATE: 42501
# MAGIC ```
