# Databricks notebook source
# MAGIC %md
# MAGIC # dbo.CustCustomerV3Staging.Table
# MAGIC This notebook was automatically converted from the script below. It may contain errors, so use it as a starting point and make necessary corrections.
# MAGIC
# MAGIC Source script: `/Volumes/dbe_dbx_internships/dbo/dbo_volume/dbo/dbo.CustCustomerV3Staging.Table.sql`

# COMMAND ----------

# ----------------------------------------------
# 1️⃣ Create the staging table **CustCustomerV3Staging**
# ----------------------------------------------
spark.sql(f"""
CREATE TABLE IF NOT EXISTS `dbe_dbx_internships`.`dbo`.`CustCustomerV3Staging` (
    -- 1. Simple string columns
    PARTYTYPE STRING NOT NULL,
    ADDRESSBOOKS STRING NOT NULL,
    ADDRESSLOCATIONROLES STRING NOT NULL,
    PRIMARYCONTACTEMAILPURPOSE STRING NOT NULL,
    PRIMARYCONTACTFAXPURPOSE STRING NOT NULL,
    PRIMARYCONTACTPHONEPURPOSE STRING NOT NULL,
    PRIMARYCONTACTTELEXPURPOSE STRING NOT NULL,
    PRIMARYCONTACTURLPURPOSE STRING NOT NULL,
    PRIMARYCONTACTFACEBOOKPURPOSE STRING NOT NULL,
    PRIMARYCONTACTLINKEDINPURPOSE STRING NOT NULL,
    PRIMARYCONTACTTWITTERPURPOSE STRING NOT NULL,
    EMPLOYEERESPONSIBLENUMBER STRING NOT NULL,
    DEFAULTDIMENSIONDISPLAYVALUE STRING NOT NULL,
    ELECTRONICLOCATIONID STRING NOT NULL,
    ADDRESSCOUNTRYREGIONISOCODE STRING NOT NULL,
    DELIVERYADDRESSCOUNTRYREGIONISOCODE STRING NOT NULL,
    INVOICEADDRESSCOUNTRYREGIONISOCODE STRING NOT NULL,
    ADDRESSCOUNTRYREGIONID STRING NOT NULL,
    ADDRESSPOSTBOX STRING NOT NULL,
    ADDRESSZIPCODE STRING NOT NULL,
    DELIVERYADDRESSZIPCODE STRING NOT NULL,
    INVOICEADDRESSZIPCODE STRING NOT NULL,
    DEFINITIONGROUP STRING NOT NULL,
    EXECUTIONID STRING NOT NULL,
    DATAAREAID STRING NOT NULL,                -- added for PK
    ISSELECTED INT NOT NULL,
    TRANSFERSTATUS INT NOT NULL,
    CUSTOMERACCOUNT STRING NOT NULL,
    ORGANIZATIONNAME STRING NOT NULL,
    NAMEALIAS STRING NOT NULL,
    KNOWNAS STRING NOT NULL,
    CUSTOMERGROUPID STRING NOT NULL,
    ORGANIZATIONNUMBER STRING NOT NULL,
    ORGANIZATIONNUMBEROFEMPLOYEES INT NOT NULL,
    ORGANIZATIONABCCODE INT NOT NULL,
    ORGANIZATIONPHONETICNAME STRING NOT NULL,
    PERSONINITIALS STRING NOT NULL,
    PERSONFIRSTNAME STRING NOT NULL,
    PERSONMIDDLENAME STRING NOT NULL,
    PERSONLASTNAMEPREFIX STRING NOT NULL,
    PERSONLASTNAME STRING NOT NULL,
    PERSONPROFESSIONALTITLE STRING NOT NULL,
    PERSONPROFESSIONALSUFFIX STRING NOT NULL,
    PERSONPHONETICFIRSTNAME STRING NOT NULL,
    PERSONPHONETICLASTNAME STRING NOT NULL,
    PERSONPHONETICMIDDLENAME STRING NOT NULL,
    PERSONGENDER INT NOT NULL,
    PERSONMARITALSTATUS INT NOT NULL,
    PERSONANNIVERSARYDAY INT NOT NULL,
    PERSONANNIVERSARYMONTH INT NOT NULL,
    PERSONANNIVERSARYYEAR INT NOT NULL,
    PERSONCHILDRENNAMES STRING NOT NULL,
    PERSONHOBBIES STRING NOT NULL,
    PARTYNUMBER STRING NOT NULL,
    LANGUAGEID STRING NOT NULL,
    FULLPRIMARYADDRESS STRING NOT NULL,
    ADDRESSDESCRIPTION STRING NOT NULL,
    ADDRESSCITY STRING NOT NULL,
    ADDRESSCOUNTY STRING NOT NULL,
    ADDRESSDISTRICTNAME STRING NOT NULL,
    ADDRESSLATITUDE DECIMAL(32,10) NOT NULL,
    ADDRESSLOCATIONID STRING NOT NULL,
    ADDRESSLONGITUDE DECIMAL(32,10) NOT NULL,
    ADDRESSSTATE STRING NOT NULL,
    ADDRESSSTREET STRING NOT NULL,
    ADDRESSSTREETNUMBER STRING NOT NULL,
    ADDRESSTIMEZONE INT NOT NULL,
    ADDRESSBUILDINGCOMPLEMENT STRING NOT NULL,
    ADDRESSVALIDFROM TIMESTAMP NOT NULL,
    ADDRESSVALIDTO TIMESTAMP NOT NULL,
    ADDRESSBRAZILIANCNPJORCPF STRING NOT NULL,
    ADDRESSBRAZILIANIE STRING NOT NULL,
    PRIMARYCONTACTEMAIL STRING NOT NULL,
    PRIMARYCONTACTEMAILDESCRIPTION STRING NOT NULL,
    PRIMARYCONTACTEMAILISIM INT NOT NULL,
    PRIMARYCONTACTFAX STRING NOT NULL,
    PRIMARYCONTACTFAXDESCRIPTION STRING NOT NULL,
    PRIMARYCONTACTFAXEXTENSION STRING NOT NULL,
    PRIMARYCONTACTPHONE STRING NOT NULL,
    PRIMARYCONTACTPHONEDESCRIPTION STRING NOT NULL,
    PRIMARYCONTACTPHONEEXTENSION STRING NOT NULL,
    PRIMARYCONTACTPHONEISMOBILE INT NOT NULL,
    PRIMARYCONTACTTELEX STRING NOT NULL,
    PRIMARYCONTACTTELEXDESCRIPTION STRING NOT NULL,
    PRIMARYCONTACTURL STRING NOT NULL,
    PRIMARYCONTACTURLDESCRIPTION STRING NOT NULL,
    PRIMARYCONTACTFACEBOOK STRING NOT NULL,
    PRIMARYCONTACTFACEBOOKDESCRIPTION STRING NOT NULL,
    PRIMARYCONTACTLINKEDIN STRING NOT NULL,
    PRIMARYCONTACTLINKEDINDESCRIPTION STRING NOT NULL,
    PRIMARYCONTACTTWITTERDESCRIPTION STRING NOT NULL,
    PRIMARYCONTACTTWITTER STRING NOT NULL,

    -- 2. More complex columns
    ISONETIMECUSTOMER INT NOT NULL,
    STATISTICSGROUPID STRING NOT NULL,
    ACCOUNTSTATEMENT INT NOT NULL,
    IDENTIFICATIONNUMBER STRING NOT NULL,
    PARTYCOUNTRY STRING NOT NULL,
    PARTYSTATE STRING NOT NULL,
    VENDORACCOUNT STRING NOT NULL,
    FEDERALINDICATOR INT NOT NULL,
    FEDERALAGENCYLOCATIONCODE STRING NOT NULL,
    FEDERALCOMMENTS STRING NOT NULL,
    IRS1099CINDICATOR INT NOT NULL,
    CONTACTPERSONID STRING NOT NULL,
    LINEOFBUSINESSID STRING NOT NULL,
    SALESSEGMENTID STRING NOT NULL,
    SALESSUBSEGMENTID STRING NOT NULL,
    SALESDISTRICT STRING NOT NULL,
    COMPANYCHAIN STRING NOT NULL,
    SALESCURRENCYCODE STRING NOT NULL,
    SALESMEMO STRING,                                    -- nullable
    ONHOLDSTATUS INT NOT NULL,
    CREDITLIMITISMANDATORY INT NOT NULL,
    CREDITRATING STRING NOT NULL,
    CREDITLIMIT DECIMAL(32,6) NOT NULL,
    COLLECTIONSCONTACTPERSONID STRING NOT NULL,
    ISEXCLUDEDFROMINTERESTCHARGECALCULATION INT NOT NULL,
    ISEXCLUDEDFROMCOLLECTIONFEECALCULATION INT NOT NULL,
    CHARGESGROUPID STRING NOT NULL,
    SITEID STRING NOT NULL,
    WAREHOUSEID STRING NOT NULL,
    ITEMCUSTOMERGROUPID STRING NOT NULL,
    COMMISSIONCUSTOMERGROUPID STRING NOT NULL,
    COMMISSIONSALESGROUPID STRING NOT NULL,
    SALESORDERPOOLID STRING NOT NULL,
    SALESACCOUNTNUMBER STRING NOT NULL,
    ORDERENTRYDEADLINE STRING NOT NULL,
    MULTILINEDISCOUNTCODE STRING NOT NULL,
    TOTALDISCOUNTCODE STRING NOT NULL,
    DISCOUNTPRICEGROUPID STRING NOT NULL,
    LINEDISCOUNTCODE STRING NOT NULL,
    CUSTOMERREBATEGROUPID STRING NOT NULL,
    CUSTOMERTMAGROUPID STRING NOT NULL,
    SUPPLEMENTARYITEMGROUPID STRING NOT NULL,
    PAYMENTTERMS STRING NOT NULL,
    PAYMENTMETHOD STRING NOT NULL,
    PAYMENTSPECIFICATION STRING NOT NULL,
    PAYMENTSCHEDULE STRING NOT NULL,
    PAYMENTDAY STRING NOT NULL,
    PAYMENTCASHDISCOUNT STRING NOT NULL,
    PAYMENTTERMSBASEDAYS INT NOT NULL,
    PAYMENTBANKACCOUNT STRING NOT NULL,
    PAYMENTFACTORINGACCOUNT STRING NOT NULL,
    PAYMENTIDTYPE STRING NOT NULL,
    PAYMENTUSECASHDISCOUNT INT NOT NULL,
    CENTRALBANKPURPOSECODE STRING NOT NULL,
    CENTRALBANKPURPOSENOTES STRING NOT NULL,
    CREDITCARDADDRESSVERIFICATION INT NOT NULL,
    CREDITCARDADDRESSVERIFICATIONISAUTHORIZATIONVOIDEDONFAILURE INT NOT NULL,
    CREDITCARDADDRESSVERIFICATIONLEVEL INT NOT NULL,
    CREDITCARDCVC INT NOT NULL,
    WAREHOUSEISASNGENERATED INT NOT NULL,
    WAREHOUSEISENTIRESHIPMENTFILLED INT NOT NULL,
    DEFAULTINVENTORYSTATUSID STRING NOT NULL,
    INVOICEACCOUNT STRING NOT NULL,
    INVOICEADDRESS INT NOT NULL,
    NUMBERSEQUENCEGROUP STRING NOT NULL,
    GIROTYPE INT NOT NULL,
    GIROTYPEFREETEXTINVOICE INT NOT NULL,
    GIROTYPEINTERESTNOTE INT NOT NULL,
    GIROTYPECOLLECTIONLETTER INT NOT NULL,
    GIROTYPEPROJINVOICE INT NOT NULL,
    GIROTYPEACCOUNTSTATEMENT INT NOT NULL,
    DELIVERYFREIGHTZONE STRING NOT NULL,
    DELIVERYTERMS STRING NOT NULL,
    DELIVERYMODE STRING NOT NULL,
    DELIVERYREASON STRING NOT NULL,
    DESTINATIONCODE STRING NOT NULL,
    RECEIPTCALENDAR STRING NOT NULL,
    ISFUELSURCHARGEAPPLIED INT NOT NULL,
    SALESTAXGROUP STRING NOT NULL,
    TAXEXEMPTNUMBER STRING NOT NULL,
    ISSALESTAXINCLUDEDINPRICES INT NOT NULL,
    PACKINGDUTYLICENSE STRING NOT NULL,
    FISCALCODE STRING NOT NULL,
    PACKINGMATERIALFEELICENSENUMBER STRING NOT NULL,
    ISELECTRONICINVOICE INT NOT NULL,
    ELECTRONICINVOICEEAN STRING NOT NULL,
    ISFREIGHTACCRUED INT NOT NULL,
    ISEXPRESSBILLOFLADINGACCEPTED INT NOT NULL,
    ISTRANSACTIONPOSTEDASSHIPMENT INT NOT NULL,
    ISORDERNUMBERREFERENCEUSED INT NOT NULL,
    SALESRETURNTAXGROUP STRING NOT NULL,
    RECEIPTEMAIL STRING NOT NULL,
    RECEIPTOPTION INT NOT NULL,
    ISWITHHOLDINGTAXCALCULATED INT NOT NULL,
    WITHHOLDINGTAXGROUPCODE STRING NOT NULL,
    FRENCHSIRET STRING NOT NULL,
    NAFCODE STRING NOT NULL,
    COMPANYTYPE INT NOT NULL,
    CURPNUMBER STRING NOT NULL,
    RFCNUMBER STRING NOT NULL,
    STATEINSCRIPTION STRING NOT NULL,
    TAXREGISTRATIONID STRING NOT NULL,
    CONSOLIDATIONDAY INT NOT NULL,
    NATIONALREGISTRYNUMBER STRING NOT NULL,
    RELIEFGROUPID STRING NOT NULL,
    CALCULATEWITHHOLDINGTAX INT NOT NULL,
    FOREIGNCUSTOMER INT NOT NULL,
    TCSGROUP STRING NOT NULL,
    TDSGROUP STRING NOT NULL,
    PREFERENTIALCUSTOMER INT NOT NULL,
    NATUREOFASSESSSEE INT NOT NULL,
    PANNUMBER STRING NOT NULL,
    PANREFERENCENUMBER STRING NOT NULL,
    PANSTATUS INT NOT NULL,
    CUSTOMERPAYMENTFINECODE STRING NOT NULL,
    CUSTOMERPAYMENTFINANCIALINTERESTCODE STRING NOT NULL,
    BRAZILIANCCM STRING NOT NULL,
    BRAZILIANCNAE STRING NOT NULL,
    BRAZILIANCNPJORCPF STRING NOT NULL,
    ISFINALUSER INT NOT NULL,
    CUSTOMERWITHHOLDINGCONTRIBUTIONTYPE INT NOT NULL,
    ISINCOMINGFISCALDOCUMENTGENERATED INT NOT NULL,
    ISICMSCONTRIBUTOR INT NOT NULL,
    BRAZILIANIE STRING NOT NULL,
    BRAZILIANINSSCEI STRING NOT NULL,
    BRAZILIANNIT STRING NOT NULL,
    ISSERVICEDELIVERYADDRESSBASED INT NOT NULL,
    ISINSUFRAMAREGION INT NOT NULL,
    SUFRAMANUMBER STRING NOT NULL,
    HASSUFRAMADISCOUNTPISANDCOFINS INT NOT NULL,
    FOREIGNERID STRING NOT NULL,
    TRANSACTIONPRESENCETYPE INT NOT NULL,
    WRITEOFFREASON STRING NOT NULL,
    EXPORTSALE INT NOT NULL,
    BIRTHCOUNTYCODE STRING NOT NULL,
    BIRTHPLACE STRING NOT NULL,
    RESIDENCEFOREIGNCOUNTRYREGIONID STRING NOT NULL,
    ISPURCHREQUESTUSED INT NOT NULL,
    DELIVERYADDRESSDESCRIPTION STRING NOT NULL,
    DELIVERYADDRESSTIMEZONE INT NOT NULL,
    DELIVERYADDRESSCITY STRING NOT NULL,
    DELIVERYADDRESSCOUNTRYREGIONID STRING NOT NULL,
    DELIVERYADDRESSCOUNTY STRING NOT NULL,
    DELIVERYADDRESSDISTRICTNAME STRING NOT NULL,
    DELIVERYADDRESSLATITUDE DECIMAL(32,10) NOT NULL,
    DELIVERYADDRESSLONGITUDE DECIMAL(32,10) NOT NULL,
    DELIVERYADDRESSLOCATIONID STRING NOT NULL,
    DELIVERYADDRESSSTATE STRING NOT NULL,
    DELIVERYADDRESSSTREET STRING NOT NULL,
    DELIVERYADDRESSSTREETNUMBER STRING NOT NULL,
    DELIVERYADDRESSBUILDINGCOMPLEMENT STRING NOT NULL,
    DELIVERYADDRESSVALIDFROM TIMESTAMP NOT NULL,
    DELIVERYADDRESSVALIDTO TIMESTAMP NOT NULL,
    INVOICEADDRESSDESCRIPTION STRING NOT NULL,
    INVOICEADDRESSTIMEZONE INT NOT NULL,
    INVOICEADDRESSCITY STRING NOT NULL,
    INVOICEADDRESSCOUNTRYREGIONID STRING NOT NULL,
    INVOICEADDRESSCOUNTY STRING NOT NULL,
    INVOICEADDRESSDISTRICTNAME STRING NOT NULL,
    INVOICEADDRESSLATITUDE DECIMAL(32,10) NOT NULL,
    INVOICEADDRESSLONGITUDE DECIMAL(32,10) NOT NULL,
    INVOICEADDRESSLOCATIONID STRING NOT NULL,
    INVOICEADDRESSSTATE STRING NOT NULL,
    INVOICEADDRESSSTREET STRING NOT NULL,
    INVOICEADDRESSSTREETNUMBER STRING NOT NULL,
    INVOICEADDRESSBUILDINGCOMPLEMENT STRING NOT NULL,
    INVOICEADDRESSVALIDFROM TIMESTAMP NOT NULL,
    INVOICEADDRESSVALIDTO TIMESTAMP NOT NULL,

    -- 3️⃣ Concurrency / primary‑key columns
    ISEXTERNALLYMAINTAINED INT NOT NULL,
    MERCHANTID STRING NOT NULL,
    DEFAULTECOMMERCEOPERATOR STRING NOT NULL,
    CUSTOMERTYPE INT NOT NULL,
    FULFILLMENTPOLICYNAME STRING NOT NULL,
    CUSTCLASSIFICATIONID STRING NOT NULL,
    ISALLOWCREATEINDIRECTORDERLINES INT NOT NULL,

    -- 4️⃣ BIGINT identity‑like columns (mapped to LONG in Spark)
    PRIMARYCONTACTEMAILRECORDID LONG NOT NULL,
    PRIMARYCONTACTFAXRECORDID LONG NOT NULL,
    PRIMARYCONTACTPHONERECORDID LONG NOT NULL,
    PRIMARYCONTACTURLRECORDID LONG NOT NULL,
    ADDRESSRECORDID LONG NOT NULL,

    -- 5️⃣ Additional numeric flags
    COLLECTIONLETTERCODE INT NOT NULL,
    EINVOICEREGISTER INT NOT NULL,
    AUTHORITYOFFICE STRING NOT NULL,
    EINVOICEATTACHMENT INT NOT NULL,
    PARTITION STRING NOT NULL,
    PRIORITY INT NOT NULL,
    INVOICEPOSTINGTYPE INT NOT NULL,
    FOREIGNRESIDENT INT NOT NULL,

    -- 6️⃣ Credit‑related columns
    CREDMANELIGIBLECREDITLIMITDATE TIMESTAMP NOT NULL,
    CREDMANGROUPID STRING NOT NULL,
    CREDMANEXCLUDE INT NOT NULL,
    CREDMANNOTES STRING,                           -- nullable
    CREDMANACCOUNTSTATUSID STRING NOT NULL,
    CREDMANELIGIBLECREDITMAX DECIMAL(32,6) NOT NULL,
    CREDMANBUSINESSSTARTED TIMESTAMP NOT NULL,
    CREDMANTITLEHELD INT NOT NULL

    -- 7️⃣ Primary‑key definition for Delta Lake
    CONSTRAINT PK_CustCustomerV3Staging PRIMARY KEY (EXECUTIONID, CUSTOMERACCOUNT, DATAAREAID, PARTITION)
) USING DELTA
""")

# COMMAND ----------

# MAGIC %md
# MAGIC ## Static Syntax Check Results
# MAGIC These are errors from static syntax checks. Manual corrections are required for these errors.
# MAGIC ### Spark SQL Syntax Errors
# MAGIC ```
# MAGIC Error in query 0: 
# MAGIC [PARSE_SYNTAX_ERROR] Syntax error at or near end of input. SQLSTATE: 42601 (line 1, pos 12419)
# MAGIC
# MAGIC == SQL ==
# MAGIC EXPLAIN CREATE TABLE IF NOT EXISTS `_placeholder_`.`_placeholder_`.`CustCustomerV3Staging` (     -- 1. Simple string columns     PARTYTYPE STRING NOT NULL,     ADDRESSBOOKS STRING NOT NULL,     ADDRESSLOCATIONROLES STRING NOT NULL,     PRIMARYCONTACTEMAILPURPOSE STRING NOT NULL,     PRIMARYCONTACTFAXPURPOSE STRING NOT NULL,     PRIMARYCONTACTPHONEPURPOSE STRING NOT NULL,     PRIMARYCONTACTTELEXPURPOSE STRING NOT NULL,     PRIMARYCONTACTURLPURPOSE STRING NOT NULL,     PRIMARYCONTACTFACEBOOKPURPOSE STRING NOT NULL,     PRIMARYCONTACTLINKEDINPURPOSE STRING NOT NULL,     PRIMARYCONTACTTWITTERPURPOSE STRING NOT NULL,     EMPLOYEERESPONSIBLENUMBER STRING NOT NULL,     DEFAULTDIMENSIONDISPLAYVALUE STRING NOT NULL,     ELECTRONICLOCATIONID STRING NOT NULL,     ADDRESSCOUNTRYREGIONISOCODE STRING NOT NULL,     DELIVERYADDRESSCOUNTRYREGIONISOCODE STRING NOT NULL,     INVOICEADDRESSCOUNTRYREGIONISOCODE STRING NOT NULL,     ADDRESSCOUNTRYREGIONID STRING NOT NULL,     ADDRESSPOSTBOX STRING NOT NULL,     ADDRESSZIPCODE STRING NOT NULL,     DELIVERYADDRESSZIPCODE STRING NOT NULL,     INVOICEADDRESSZIPCODE STRING NOT NULL,     DEFINITIONGROUP STRING NOT NULL,     EXECUTIONID STRING NOT NULL,     DATAAREAID STRING NOT NULL,                -- added for PK     ISSELECTED INT NOT NULL,     TRANSFERSTATUS INT NOT NULL,     CUSTOMERACCOUNT STRING NOT NULL,     ORGANIZATIONNAME STRING NOT NULL,     NAMEALIAS STRING NOT NULL,     KNOWNAS STRING NOT NULL,     CUSTOMERGROUPID STRING NOT NULL,     ORGANIZATIONNUMBER STRING NOT NULL,     ORGANIZATIONNUMBEROFEMPLOYEES INT NOT NULL,     ORGANIZATIONABCCODE INT NOT NULL,     ORGANIZATIONPHONETICNAME STRING NOT NULL,     PERSONINITIALS STRING NOT NULL,     PERSONFIRSTNAME STRING NOT NULL,     PERSONMIDDLENAME STRING NOT NULL,     PERSONLASTNAMEPREFIX STRING NOT NULL,     PERSONLASTNAME STRING NOT NULL,     PERSONPROFESSIONALTITLE STRING NOT NULL,     PERSONPROFESSIONALSUFFIX STRING NOT NULL,     PERSONPHONETICFIRSTNAME STRING NOT NULL,     PERSONPHONETICLASTNAME STRING NOT NULL,     PERSONPHONETICMIDDLENAME STRING NOT NULL,     PERSONGENDER INT NOT NULL,     PERSONMARITALSTATUS INT NOT NULL,     PERSONANNIVERSARYDAY INT NOT NULL,     PERSONANNIVERSARYMONTH INT NOT NULL,     PERSONANNIVERSARYYEAR INT NOT NULL,     PERSONCHILDRENNAMES STRING NOT NULL,     PERSONHOBBIES STRING NOT NULL,     PARTYNUMBER STRING NOT NULL,     LANGUAGEID STRING NOT NULL,     FULLPRIMARYADDRESS STRING NOT NULL,     ADDRESSDESCRIPTION STRING NOT NULL,     ADDRESSCITY STRING NOT NULL,     ADDRESSCOUNTY STRING NOT NULL,     ADDRESSDISTRICTNAME STRING NOT NULL,     ADDRESSLATITUDE DECIMAL(32,10) NOT NULL,     ADDRESSLOCATIONID STRING NOT NULL,     ADDRESSLONGITUDE DECIMAL(32,10) NOT NULL,     ADDRESSSTATE STRING NOT NULL,     ADDRESSSTREET STRING NOT NULL,     ADDRESSSTREETNUMBER STRING NOT NULL,     ADDRESSTIMEZONE INT NOT NULL,     ADDRESSBUILDINGCOMPLEMENT STRING NOT NULL,     ADDRESSVALIDFROM TIMESTAMP NOT NULL,     ADDRESSVALIDTO TIMESTAMP NOT NULL,     ADDRESSBRAZILIANCNPJORCPF STRING NOT NULL,     ADDRESSBRAZILIANIE STRING NOT NULL,     PRIMARYCONTACTEMAIL STRING NOT NULL,     PRIMARYCONTACTEMAILDESCRIPTION STRING NOT NULL,     PRIMARYCONTACTEMAILISIM INT NOT NULL,     PRIMARYCONTACTFAX STRING NOT NULL,     PRIMARYCONTACTFAXDESCRIPTION STRING NOT NULL,     PRIMARYCONTACTFAXEXTENSION STRING NOT NULL,     PRIMARYCONTACTPHONE STRING NOT NULL,     PRIMARYCONTACTPHONEDESCRIPTION STRING NOT NULL,     PRIMARYCONTACTPHONEEXTENSION STRING NOT NULL,     PRIMARYCONTACTPHONEISMOBILE INT NOT NULL,     PRIMARYCONTACTTELEX STRING NOT NULL,     PRIMARYCONTACTTELEXDESCRIPTION STRING NOT NULL,     PRIMARYCONTACTURL STRING NOT NULL,     PRIMARYCONTACTURLDESCRIPTION STRING NOT NULL,     PRIMARYCONTACTFACEBOOK STRING NOT NULL,     PRIMARYCONTACTFACEBOOKDESCRIPTION STRING NOT NULL,     PRIMARYCONTACTLINKEDIN STRING NOT NULL,     PRIMARYCONTACTLINKEDINDESCRIPTION STRING NOT NULL,     PRIMARYCONTACTTWITTERDESCRIPTION STRING NOT NULL,     PRIMARYCONTACTTWITTER STRING NOT NULL,      -- 2. More complex columns     ISONETIMECUSTOMER INT NOT NULL,     STATISTICSGROUPID STRING NOT NULL,     ACCOUNTSTATEMENT INT NOT NULL,     IDENTIFICATIONNUMBER STRING NOT NULL,     PARTYCOUNTRY STRING NOT NULL,     PARTYSTATE STRING NOT NULL,     VENDORACCOUNT STRING NOT NULL,     FEDERALINDICATOR INT NOT NULL,     FEDERALAGENCYLOCATIONCODE STRING NOT NULL,     FEDERALCOMMENTS STRING NOT NULL,     IRS1099CINDICATOR INT NOT NULL,     CONTACTPERSONID STRING NOT NULL,     LINEOFBUSINESSID STRING NOT NULL,     SALESSEGMENTID STRING NOT NULL,     SALESSUBSEGMENTID STRING NOT NULL,     SALESDISTRICT STRING NOT NULL,     COMPANYCHAIN STRING NOT NULL,     SALESCURRENCYCODE STRING NOT NULL,     SALESMEMO STRING,                                    -- nullable     ONHOLDSTATUS INT NOT NULL,     CREDITLIMITISMANDATORY INT NOT NULL,     CREDITRATING STRING NOT NULL,     CREDITLIMIT DECIMAL(32,6) NOT NULL,     COLLECTIONSCONTACTPERSONID STRING NOT NULL,     ISEXCLUDEDFROMINTERESTCHARGECALCULATION INT NOT NULL,     ISEXCLUDEDFROMCOLLECTIONFEECALCULATION INT NOT NULL,     CHARGESGROUPID STRING NOT NULL,     SITEID STRING NOT NULL,     WAREHOUSEID STRING NOT NULL,     ITEMCUSTOMERGROUPID STRING NOT NULL,     COMMISSIONCUSTOMERGROUPID STRING NOT NULL,     COMMISSIONSALESGROUPID STRING NOT NULL,     SALESORDERPOOLID STRING NOT NULL,     SALESACCOUNTNUMBER STRING NOT NULL,     ORDERENTRYDEADLINE STRING NOT NULL,     MULTILINEDISCOUNTCODE STRING NOT NULL,     TOTALDISCOUNTCODE STRING NOT NULL,     DISCOUNTPRICEGROUPID STRING NOT NULL,     LINEDISCOUNTCODE STRING NOT NULL,     CUSTOMERREBATEGROUPID STRING NOT NULL,     CUSTOMERTMAGROUPID STRING NOT NULL,     SUPPLEMENTARYITEMGROUPID STRING NOT NULL,     PAYMENTTERMS STRING NOT NULL,     PAYMENTMETHOD STRING NOT NULL,     PAYMENTSPECIFICATION STRING NOT NULL,     PAYMENTSCHEDULE STRING NOT NULL,     PAYMENTDAY STRING NOT NULL,     PAYMENTCASHDISCOUNT STRING NOT NULL,     PAYMENTTERMSBASEDAYS INT NOT NULL,     PAYMENTBANKACCOUNT STRING NOT NULL,     PAYMENTFACTORINGACCOUNT STRING NOT NULL,     PAYMENTIDTYPE STRING NOT NULL,     PAYMENTUSECASHDISCOUNT INT NOT NULL,     CENTRALBANKPURPOSECODE STRING NOT NULL,     CENTRALBANKPURPOSENOTES STRING NOT NULL,     CREDITCARDADDRESSVERIFICATION INT NOT NULL,     CREDITCARDADDRESSVERIFICATIONISAUTHORIZATIONVOIDEDONFAILURE INT NOT NULL,     CREDITCARDADDRESSVERIFICATIONLEVEL INT NOT NULL,     CREDITCARDCVC INT NOT NULL,     WAREHOUSEISASNGENERATED INT NOT NULL,     WAREHOUSEISENTIRESHIPMENTFILLED INT NOT NULL,     DEFAULTINVENTORYSTATUSID STRING NOT NULL,     INVOICEACCOUNT STRING NOT NULL,     INVOICEADDRESS INT NOT NULL,     NUMBERSEQUENCEGROUP STRING NOT NULL,     GIROTYPE INT NOT NULL,     GIROTYPEFREETEXTINVOICE INT NOT NULL,     GIROTYPEINTERESTNOTE INT NOT NULL,     GIROTYPECOLLECTIONLETTER INT NOT NULL,     GIROTYPEPROJINVOICE INT NOT NULL,     GIROTYPEACCOUNTSTATEMENT INT NOT NULL,     DELIVERYFREIGHTZONE STRING NOT NULL,     DELIVERYTERMS STRING NOT NULL,     DELIVERYMODE STRING NOT NULL,     DELIVERYREASON STRING NOT NULL,     DESTINATIONCODE STRING NOT NULL,     RECEIPTCALENDAR STRING NOT NULL,     ISFUELSURCHARGEAPPLIED INT NOT NULL,     SALESTAXGROUP STRING NOT NULL,     TAXEXEMPTNUMBER STRING NOT NULL,     ISSALESTAXINCLUDEDINPRICES INT NOT NULL,     PACKINGDUTYLICENSE STRING NOT NULL,     FISCALCODE STRING NOT NULL,     PACKINGMATERIALFEELICENSENUMBER STRING NOT NULL,     ISELECTRONICINVOICE INT NOT NULL,     ELECTRONICINVOICEEAN STRING NOT NULL,     ISFREIGHTACCRUED INT NOT NULL,     ISEXPRESSBILLOFLADINGACCEPTED INT NOT NULL,     ISTRANSACTIONPOSTEDASSHIPMENT INT NOT NULL,     ISORDERNUMBERREFERENCEUSED INT NOT NULL,     SALESRETURNTAXGROUP STRING NOT NULL,     RECEIPTEMAIL STRING NOT NULL,     RECEIPTOPTION INT NOT NULL,     ISWITHHOLDINGTAXCALCULATED INT NOT NULL,     WITHHOLDINGTAXGROUPCODE STRING NOT NULL,     FRENCHSIRET STRING NOT NULL,     NAFCODE STRING NOT NULL,     COMPANYTYPE INT NOT NULL,     CURPNUMBER STRING NOT NULL,     RFCNUMBER STRING NOT NULL,     STATEINSCRIPTION STRING NOT NULL,     TAXREGISTRATIONID STRING NOT NULL,     CONSOLIDATIONDAY INT NOT NULL,     NATIONALREGISTRYNUMBER STRING NOT NULL,     RELIEFGROUPID STRING NOT NULL,     CALCULATEWITHHOLDINGTAX INT NOT NULL,     FOREIGNCUSTOMER INT NOT NULL,     TCSGROUP STRING NOT NULL,     TDSGROUP STRING NOT NULL,     PREFERENTIALCUSTOMER INT NOT NULL,     NATUREOFASSESSSEE INT NOT NULL,     PANNUMBER STRING NOT NULL,     PANREFERENCENUMBER STRING NOT NULL,     PANSTATUS INT NOT NULL,     CUSTOMERPAYMENTFINECODE STRING NOT NULL,     CUSTOMERPAYMENTFINANCIALINTERESTCODE STRING NOT NULL,     BRAZILIANCCM STRING NOT NULL,     BRAZILIANCNAE STRING NOT NULL,     BRAZILIANCNPJORCPF STRING NOT NULL,     ISFINALUSER INT NOT NULL,     CUSTOMERWITHHOLDINGCONTRIBUTIONTYPE INT NOT NULL,     ISINCOMINGFISCALDOCUMENTGENERATED INT NOT NULL,     ISICMSCONTRIBUTOR INT NOT NULL,     BRAZILIANIE STRING NOT NULL,     BRAZILIANINSSCEI STRING NOT NULL,     BRAZILIANNIT STRING NOT NULL,     ISSERVICEDELIVERYADDRESSBASED INT NOT NULL,     ISINSUFRAMAREGION INT NOT NULL,     SUFRAMANUMBER STRING NOT NULL,     HASSUFRAMADISCOUNTPISANDCOFINS INT NOT NULL,     FOREIGNERID STRING NOT NULL,     TRANSACTIONPRESENCETYPE INT NOT NULL,     WRITEOFFREASON STRING NOT NULL,     EXPORTSALE INT NOT NULL,     BIRTHCOUNTYCODE STRING NOT NULL,     BIRTHPLACE STRING NOT NULL,     RESIDENCEFOREIGNCOUNTRYREGIONID STRING NOT NULL,     ISPURCHREQUESTUSED INT NOT NULL,     DELIVERYADDRESSDESCRIPTION STRING NOT NULL,     DELIVERYADDRESSTIMEZONE INT NOT NULL,     DELIVERYADDRESSCITY STRING NOT NULL,     DELIVERYADDRESSCOUNTRYREGIONID STRING NOT NULL,     DELIVERYADDRESSCOUNTY STRING NOT NULL,     DELIVERYADDRESSDISTRICTNAME STRING NOT NULL,     DELIVERYADDRESSLATITUDE DECIMAL(32,10) NOT NULL,     DELIVERYADDRESSLONGITUDE DECIMAL(32,10) NOT NULL,     DELIVERYADDRESSLOCATIONID STRING NOT NULL,     DELIVERYADDRESSSTATE STRING NOT NULL,     DELIVERYADDRESSSTREET STRING NOT NULL,     DELIVERYADDRESSSTREETNUMBER STRING NOT NULL,     DELIVERYADDRESSBUILDINGCOMPLEMENT STRING NOT NULL,     DELIVERYADDRESSVALIDFROM TIMESTAMP NOT NULL,     DELIVERYADDRESSVALIDTO TIMESTAMP NOT NULL,     INVOICEADDRESSDESCRIPTION STRING NOT NULL,     INVOICEADDRESSTIMEZONE INT NOT NULL,     INVOICEADDRESSCITY STRING NOT NULL,     INVOICEADDRESSCOUNTRYREGIONID STRING NOT NULL,     INVOICEADDRESSCOUNTY STRING NOT NULL,     INVOICEADDRESSDISTRICTNAME STRING NOT NULL,     INVOICEADDRESSLATITUDE DECIMAL(32,10) NOT NULL,     INVOICEADDRESSLONGITUDE DECIMAL(32,10) NOT NULL,     INVOICEADDRESSLOCATIONID STRING NOT NULL,     INVOICEADDRESSSTATE STRING NOT NULL,     INVOICEADDRESSSTREET STRING NOT NULL,     INVOICEADDRESSSTREETNUMBER STRING NOT NULL,     INVOICEADDRESSBUILDINGCOMPLEMENT STRING NOT NULL,     INVOICEADDRESSVALIDFROM TIMESTAMP NOT NULL,     INVOICEADDRESSVALIDTO TIMESTAMP NOT NULL,      -- 3️⃣ Concurrency / primary‑key columns     ISEXTERNALLYMAINTAINED INT NOT NULL,     MERCHANTID STRING NOT NULL,     DEFAULTECOMMERCEOPERATOR STRING NOT NULL,     CUSTOMERTYPE INT NOT NULL,     FULFILLMENTPOLICYNAME STRING NOT NULL,     CUSTCLASSIFICATIONID STRING NOT NULL,     ISALLOWCREATEINDIRECTORDERLINES INT NOT NULL,      -- 4️⃣ BIGINT identity‑like columns (mapped to LONG in Spark)     PRIMARYCONTACTEMAILRECORDID LONG NOT NULL,     PRIMARYCONTACTFAXRECORDID LONG NOT NULL,     PRIMARYCONTACTPHONERECORDID LONG NOT NULL,     PRIMARYCONTACTURLRECORDID LONG NOT NULL,     ADDRESSRECORDID LONG NOT NULL,      -- 5️⃣ Additional numeric flags     COLLECTIONLETTERCODE INT NOT NULL,     EINVOICEREGISTER INT NOT NULL,     AUTHORITYOFFICE STRING NOT NULL,     EINVOICEATTACHMENT INT NOT NULL,     PARTITION STRING NOT NULL,     PRIORITY INT NOT NULL,     INVOICEPOSTINGTYPE INT NOT NULL,     FOREIGNRESIDENT INT NOT NULL,      -- 6️⃣ Credit‑related columns     CREDMANELIGIBLECREDITLIMITDATE TIMESTAMP NOT NULL,     CREDMANGROUPID STRING NOT NULL,     CREDMANEXCLUDE INT NOT NULL,     CREDMANNOTES STRING,                           -- nullable     CREDMANACCOUNTSTATUSID STRING NOT NULL,     CREDMANELIGIBLECREDITMAX DECIMAL(32,6) NOT NULL,     CREDMANBUSINESSSTARTED TIMESTAMP NOT NULL,     CREDMANTITLEHELD INT NOT NULL      -- 7️⃣ Primary‑key definition for Delta Lake     CONSTRAINT PK_CustCustomerV3Staging PRIMARY KEY (EXECUTIONID, CUSTOMERACCOUNT, DATAAREAID, PARTITION) ) USING DELTA
# MAGIC -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------^^^
# MAGIC
# MAGIC ```
