/****** Object:  Database [CustomerBackup]    Script Date: 03/03/2026 16:26:08 ******/
CREATE DATABASE `CustomerBackup`  (EDITION = 'Standard', SERVICE_OBJECTIVE = 'S3', MAXSIZE = 250 GB) ;
WITH CATALOG_COLLATION = SQL_Latin1_General_CP1_CI_AS, LEDGER = OFF;

ALTER DATABASE `CustomerBackup` SET COMPATIBILITY_LEVEL = 170
;

ALTER DATABASE `CustomerBackup` SET ANSI_NULL_DEFAULT OFF 
;

ALTER DATABASE `CustomerBackup` 
;

ALTER DATABASE `CustomerBackup` SET ANSI_PADDING OFF 
;

ALTER DATABASE `CustomerBackup` SET ANSI_WARNINGS OFF 
;

ALTER DATABASE `CustomerBackup` SET ARITHABORT OFF 
;

ALTER DATABASE `CustomerBackup` SET AUTO_SHRINK OFF 
;

ALTER DATABASE `CustomerBackup`  
;

ALTER DATABASE `CustomerBackup` SET CURSOR_CLOSE_ON_COMMIT OFF 
;

ALTER DATABASE `CustomerBackup` SET CONCAT_NULL_YIELDS_NULL OFF 
;

ALTER DATABASE `CustomerBackup` SET NUMERIC_ROUNDABORT OFF 
;

ALTER DATABASE `CustomerBackup` 
;

ALTER DATABASE `CustomerBackup` SET RECURSIVE_TRIGGERS OFF 
;

ALTER DATABASE `CustomerBackup` SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
;

ALTER DATABASE `CustomerBackup`  
;

ALTER DATABASE `CustomerBackup` SET PARAMETERIZATION SIMPLE 
;

ALTER DATABASE `CustomerBackup`  
;

ALTER DATABASE `CustomerBackup` SET  MULTI_USER 
;

ALTER DATABASE `CustomerBackup` 
;

ALTER DATABASE `CustomerBackup` SET QUERY_STORE = ON
;

ALTER DATABASE `CustomerBackup` SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 100, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
;
/*** The scripts of database scoped configurations in Azure should be executed inside the target database connection. ***/


-- ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 8;



ALTER DATABASE `CustomerBackup` SET  READ_WRITE 
;
