/****** Object:  Table [DataStore].[RFQ]    Script Date: 03/03/2026 16:26:09 ******/



CREATE OR REPLACE TABLE `DataStore`.`RFQ`(
	`RFQCaseCode`  STRING NOT NULL,
	`RFQCaseName`  STRING NOT NULL,
	`RFQCaseLineNumber` bigint NOT NULL,
	`RFQCode`  STRING NOT NULL,
	`RFQName`  STRING NOT NULL,
	`RFQLineNumber`  DECIMAL(32,16) NOT NULL,
	`SupplierCode`  STRING NOT NULL,
	`CompanyCode`  STRING NOT NULL,
	`ProductConfigurationCode`  STRING NOT NULL,
	`ProductCode`  STRING NOT NULL,
	`DeliveryModeCode`  STRING NOT NULL,
	`DeliveryTermsCode`  STRING NOT NULL,
	`DefaultExchangeRateTypeCode`  STRING NOT NULL,
	`BudgetExchangeRateTypeCode`  STRING NOT NULL,
	`TransactionCurrencyCode`  STRING NOT NULL,
	`AccountingCurrencyCode`  STRING NOT NULL,
	`ReportingCurrencyCode`  STRING NOT NULL,
	`GroupCurrencyCode`  STRING NOT NULL,
	`DeliveryDate` TIMESTAMP ,
	`ExpiryDate` TIMESTAMP ,
	`CreatedDate` TIMESTAMP ,
	`RFQCaseStatusLow`  STRING,
	`RFQCaseStatusHigh`  STRING,
	`RFQLineStatus`  STRING,
	`PurchaseUnit`  STRING NOT NULL,
	`PurchQuantity`  DECIMAL(32,6) NOT NULL,
	`PurchPriceTC`  DECIMAL(32,6) NOT NULL,
	`PurchPriceAC`  DECIMAL(38,6) NOT NULL,
	`PurchPriceRC`  DECIMAL(38,6) NOT NULL,
	`PurchPriceGC`  DECIMAL(38,6) NOT NULL,
	`PurchPriceAC_Budget`  DECIMAL(38,6) NOT NULL,
	`PurchPriceRC_Budget`  DECIMAL(38,6) NOT NULL,
	`PurchPriceGC_Budget`  DECIMAL(38,6) NOT NULL,
	`RFQLineAmountTC`  DECIMAL(32,6) NOT NULL,
	`RFQLineAmountAC`  DECIMAL(38,6) NOT NULL,
	`RFQLineAmountRC`  DECIMAL(38,6) NOT NULL,
	`RFQLineAmountGC`  DECIMAL(38,6) NOT NULL,
	`RFQLineAmountAC_Budget`  DECIMAL(38,6) NOT NULL,
	`RFQLineAmountRC_Budget`  DECIMAL(38,6) NOT NULL,
	`RFQLineAmountGC_Budget`  DECIMAL(38,6) NOT NULL,
	`CostAvoidanceAmountTC`  DECIMAL(33,6) NOT NULL,
	`CostAvoidanceAmountAC`  DECIMAL(38,6) NOT NULL,
	`CostAvoidanceAmountRC`  DECIMAL(38,6) NOT NULL,
	`CostAvoidanceAmountGC`  DECIMAL(38,6) NOT NULL,
	`CostAvoidanceAmountAC_Budget`  DECIMAL(38,6) NOT NULL,
	`CostAvoidanceAmountRC_Budget`  DECIMAL(38,6) NOT NULL,
	`CostAvoidanceAmountGC_Budget`  DECIMAL(38,6) NOT NULL,
	`MaxPurchPriceTC`  DECIMAL(32,6) NOT NULL,
	`MaxPurchPriceAC`  DECIMAL(38,6) NOT NULL,
	`MaxPurchPriceRC`  DECIMAL(38,6) NOT NULL,
	`MaxPurchPriceGC`  DECIMAL(38,6) NOT NULL,
	`MaxPurchPriceAC_Budget`  DECIMAL(38,6) NOT NULL,
	`MaxPurchPriceRC_Budget`  DECIMAL(38,6) NOT NULL,
	`MaxPurchPriceGC_Budget`  DECIMAL(38,6) NOT NULL,
	`MinPurchPriceTC`  DECIMAL(32,6) NOT NULL,
	`MinPurchPriceAC`  DECIMAL(38,6) NOT NULL,
	`MinPurchPriceRC`  DECIMAL(38,6) NOT NULL,
	`MinPurchPriceGC`  DECIMAL(38,6) NOT NULL,
	`MinPurchPriceAC_Budget`  DECIMAL(38,6) NOT NULL,
	`MinPurchPriceRC_Budget`  DECIMAL(38,6) NOT NULL,
	`MinPurchPriceGC_Budget`  DECIMAL(38,6) NOT NULL,
	`AppliedExchangeRateTC`  DECIMAL(38,6) ,
	`AppliedExchangeRateRC`  DECIMAL(38,21) NOT NULL,
	`AppliedExchangeRateAC`  DECIMAL(38,21) NOT NULL,
	`AppliedExchangeRateGC`  DECIMAL(38,21) NOT NULL
)
;
