/****** Object:  Table [DataStore2].[ProductionOrder]    Script Date: 03/03/2026 16:26:09 ******/



CREATE OR REPLACE TABLE `DataStore2`.`ProductionOrder`(
	`ProductionOrderCode`  STRING NOT NULL,
	`TransactionType`  STRING NOT NULL,
	`ProductionOrderStatus`  STRING NOT NULL,
	`CompanyCode`  STRING NOT NULL,
	`ProductCode`  STRING NOT NULL,
	`ProductCode_UsedBOMLines`  STRING NOT NULL,
	`RouteCode`  STRING NOT NULL,
	`SiteCode`  STRING NOT NULL,
	`OperationCode`  STRING NOT NULL,
	`OperationNumber` int NOT NULL,
	`ResourceCode`  STRING NOT NULL,
	`CalculationType`  STRING NOT NULL,
	`ProductionResourceCode`  STRING NOT NULL,
	`CostGroupCode`  STRING NOT NULL,
	`InventDimCode`  STRING NOT NULL,
	`InventDimCode_UsedBOMLines`  STRING NOT NULL,
	`BOMCode`  STRING NOT NULL,
	`JournalPostingDate` TIMESTAMP NOT NULL,
	`RequestedDeliveryDate` TIMESTAMP NOT NULL,
	`ScheduledDeliveryDate` TIMESTAMP NOT NULL,
	`ActualDeliveryDate` TIMESTAMP NOT NULL,
	`ScheduledProductionStartDate` TIMESTAMP NOT NULL,
	`ScheduledProductionEndDate` TIMESTAMP NOT NULL,
	`ProductionStartDate` TIMESTAMP ,
	`ProductionEndDate` TIMESTAMP ,
	`OTIF`  DECIMAL(38,6) NOT NULL,
	`InventUnit`  STRING NOT NULL,
	`InventUnit_UsedBOMLines`  STRING NOT NULL,
	`OriginalEstimatedQuantity`  DECIMAL(32,6) NOT NULL,
	`OriginalEstimatedQuantityDetail`  DECIMAL(38,12) ,
	`EstimatedQuantity`  DECIMAL(32,6) NOT NULL,
	`EstimatedQuantityDetail`  DECIMAL(38,12) ,
	`ProducedQuantity`  DECIMAL(38,6) NOT NULL,
	`ProducedQuantityDetail`  DECIMAL(38,6) ,
	`ReportRemainderAsFinished`  DECIMAL(32,6) NOT NULL,
	`ReportRemainderAsFinishedDetail`  DECIMAL(38,12) ,
	`TotalEstimatedConsumptionQuantity`  DECIMAL(34,17) ,
	`NetEstimatedConsumptionQuantity`  DECIMAL(38,6) ,
	`RealConsumptionQuantity`  DECIMAL(33,17) ,
	`ConstantScrapQuantity`  DECIMAL(38,6) ,
	`VariableScrapQuantity`  DECIMAL(38,6) ,
	`TotalEstimatedCostAmountAC`  DECIMAL(34,17) ,
	`NetEstimatedCostAmountAC`  DECIMAL(32,17) ,
	`RealCostAmountAC`  DECIMAL(33,17) 
)
;
