/****** Object:  Table [DataStore2].[ProductionTimeRegistration]    Script Date: 03/03/2026 16:26:08 ******/



CREATE OR REPLACE TABLE `DataStore2`.`ProductionTimeRegistration`(
	`ProductionOrderCode`  STRING NOT NULL,
	`CompanyCode`  STRING NOT NULL,
	`ProductConfigurationCode`  STRING NOT NULL,
	`ResourceCode`  STRING NOT NULL,
	`RouteCode`  STRING NOT NULL,
	`OperationCode`  STRING NOT NULL,
	`OperationNumber` int NOT NULL,
	`RoutingName`  STRING NOT NULL,
	`Shift`  STRING NOT NULL,
	`OperatorType`  STRING NOT NULL,
	`OperatorName`  STRING,
	`DefaultExchangeRateTypeCode`  STRING NOT NULL,
	`BudgetExchangeRateTypeCode`  STRING NOT NULL,
	`TransactionCurrencyCode`  STRING NOT NULL,
	`AccountingCurrencyCode`  STRING NOT NULL,
	`ReportingCurrencyCode`  STRING NOT NULL,
	`GroupCurrencyCode`  STRING NOT NULL,
	`RecId` bigint NOT NULL,
	`PostedJournalDate` TIMESTAMP ,
	`MachineTimeMinutes`  DECIMAL(35,6) NOT NULL,
	`MachineTimeHours`  DECIMAL(32,6) NOT NULL,
	`MachineTimeDays`  DECIMAL(35,9) NOT NULL,
	`MachineCostTC`  DECIMAL(38,6) ,
	`MachineCostAC`  DECIMAL(38,6) NOT NULL,
	`MachineCostRC`  DECIMAL(38,6) NOT NULL,
	`MachineCostGC`  DECIMAL(38,6) NOT NULL,
	`MachineCostAC_Budget`  DECIMAL(38,6) NOT NULL,
	`MachineCostRC_Budget`  DECIMAL(38,6) NOT NULL,
	`MachineCostGC_Budget`  DECIMAL(38,6) NOT NULL,
	`OperatorTimeMinutes`  DECIMAL(35,6) NOT NULL,
	`OperatorTimeHours`  DECIMAL(32,6) NOT NULL,
	`OperatorTimeDays`  DECIMAL(35,9) NOT NULL,
	`LabourCostTC`  DECIMAL(38,6) ,
	`LabourCostAC`  DECIMAL(38,6) NOT NULL,
	`LabourCostRC`  DECIMAL(38,6) NOT NULL,
	`LabourCostGC`  DECIMAL(38,6) NOT NULL,
	`LabourCostAC_Budget`  DECIMAL(38,6) NOT NULL,
	`LabourCostRC_Budget`  DECIMAL(38,6) NOT NULL,
	`LabourCostGC_Budget`  DECIMAL(38,6) NOT NULL,
	`AppliedExchangeRateTC`  DECIMAL(38,6) ,
	`AppliedExchangeRateRC`  DECIMAL(38,21) NOT NULL,
	`AppliedExchangeRateAC`  DECIMAL(38,21) NOT NULL,
	`AppliedExchangeRateGC`  DECIMAL(38,21) NOT NULL,
	`AppliedExchangeRateRC_Budget`  DECIMAL(38,21) NOT NULL,
	`AppliedExchangeRateAC_Budget`  DECIMAL(38,21) NOT NULL,
	`AppliedExchangeRateGC_Budget`  DECIMAL(38,21) NOT NULL
)
;
