/****** Object:  Table [DataStore2].[IntercompanyARAP]    Script Date: 03/03/2026 16:26:08 ******/



CREATE OR REPLACE TABLE `DataStore2`.`IntercompanyARAP`(
	`SalesInvoiceCode`  STRING NOT NULL,
	`PurchaseInvoiceCode`  STRING NOT NULL,
	`ReportDate` INT,
	`SupplierCode`  STRING NOT NULL,
	`CustomerCode`  STRING,
	`DefaultExchangeRateTypeCode`  STRING NOT NULL,
	`TransactionCurrencyCode`  STRING,
	`AccountingCurrencyCode`  STRING NOT NULL,
	`ReportingCurrencyCode`  STRING NOT NULL,
	`GroupCurrencyCode`  STRING NOT NULL,
	`InvoiceAmountTC`  DECIMAL(38,8) ,
	`InvoiceAmountAC`  DECIMAL(38,6) ,
	`InvoiceAmountRC`  DECIMAL(38,6) ,
	`InvoiceAmountGC`  DECIMAL(38,6) ,
	`OpenAmountTC`  DECIMAL(38,6) ,
	`OpenAmountAC`  DECIMAL(38,6) ,
	`OpenAmountRC`  DECIMAL(38,6) ,
	`OpenAmountGC`  DECIMAL(38,6) ,
	`AmountInvoiceTC` decimal(38, 6),
	`AmountInvoiceAC` decimal(38, 6),
	`AmountInvoiceRC` decimal(38, 6),
	`AmountInvoiceGC` decimal(38, 6),
	`SupplierSettlement`  STRING NOT NULL,
	`CustomerSettlement`  STRING,
	`DimInvoiceDateId` INT,
	`DimDueDateId` INT,
	`PostedDate` TIMESTAMP ,
	`ETA` TIMESTAMP ,
	`ETD` TIMESTAMP ,
	`Branch`  STRING NOT NULL,
	`Departement`  STRING NOT NULL,
	`BusinessType`  STRING NOT NULL,
	`AR_AP_Type`  STRING NOT NULL,
	`Type`  STRING NOT NULL,
	`JobInvoice`  STRING NOT NULL,
	`POD`  STRING NOT NULL,
	`POL`  STRING NOT NULL,
	`House`  STRING NOT NULL,
	`ShipmentNumber`  STRING NOT NULL,
	`Master`  STRING NOT NULL,
	`OrigCountry`  STRING NOT NULL,
	`OrigCountryName`  STRING NOT NULL,
	`CompanyCode`  STRING
)
;
