/****** Object:  Table [DataStore2].[PurchaseInvoice]    Script Date: 03/03/2026 16:26:08 ******/



CREATE OR REPLACE TABLE `DataStore2`.`PurchaseInvoice`(
	`PurchaseInvoiceIdScreening`  STRING NOT NULL,
	`PurchaseInvoiceCode`  STRING NOT NULL,
	`PurchaseInvoiceLineNumber`  DECIMAL(32,16) NOT NULL,
	`InvoiceLineNumberCombination`  STRING,
	`CompanyCode`  STRING,
	`PurchaseOrderCode`  STRING NOT NULL,
	`InventTransCode`  STRING NOT NULL,
	`InventDimCode`  STRING NOT NULL,
	`PurchaseOrderStatus`  STRING,
	`SupplierCode`  STRING,
	`ProductCode`  STRING NOT NULL,
	`PaymentTermsCode`  STRING,
	`DeliveryModeCode`  STRING,
	`DeliveryTermsCode`  STRING,
	`InternalInvoiceCode`  STRING NOT NULL,
	`TaxWriteCode` INT,
	`TransactionType`  STRING,
	`DefaultExchangeRateTypeCode`  STRING NOT NULL,
	`BudgetExchangeRateTypeCode`  STRING NOT NULL,
	`TransactionCurrencyCode`  STRING,
	`AccountingCurrencyCode`  STRING NOT NULL,
	`ReportingCurrencyCode`  STRING NOT NULL,
	`GroupCurrencyCode`  STRING NOT NULL,
	`GLAccountCode`  STRING NOT NULL,
	`IntercompanyCode`  STRING NOT NULL,
	`BusinessSegmentCode`  STRING NOT NULL,
	`DepartmentCode`  STRING NOT NULL,
	`EndCustomerCode`  STRING NOT NULL,
	`LocationCode`  STRING NOT NULL,
	`ShipmentContractCode`  STRING NOT NULL,
	`LocalAccountCode`  STRING NOT NULL,
	`ProductFDCode`  STRING NOT NULL,
	`InvoiceDate` TIMESTAMP NOT NULL,
	`PurchaseUnit`  STRING,
	`InvoicedQuantity_InventoryUnit`  DECIMAL(38,6) NOT NULL,
	`InvoicedQuantity_PurchaseUnit`  DECIMAL(38,6) NOT NULL,
	`InvoicedQuantity_SalesUnit`  DECIMAL(38,6) NOT NULL,
	`PurchasePricePerUnitTC`  DECIMAL(38,6) NOT NULL,
	`PurchasePricePerUnitAC`  DECIMAL(38,6) NOT NULL,
	`PurchasePricePerUnitRC`  DECIMAL(38,6) NOT NULL,
	`PurchasePricePerUnitGC`  DECIMAL(38,6) NOT NULL,
	`PurchasePricePerUnitAC_Budget`  DECIMAL(38,6) NOT NULL,
	`PurchasePricePerUnitRC_Budget`  DECIMAL(38,6) NOT NULL,
	`PurchasePricePerUnitGC_Budget`  DECIMAL(38,6) NOT NULL,
	`GrossPurchaseTC`  DECIMAL(38,6) NOT NULL,
	`GrossPurchaseAC`  DECIMAL(38,6) NOT NULL,
	`GrossPurchaseRC`  DECIMAL(38,6) NOT NULL,
	`GrossPurchaseGC`  DECIMAL(38,6) NOT NULL,
	`GrossPurchaseAC_Budget`  DECIMAL(38,6) NOT NULL,
	`GrossPurchaseRC_Budget`  DECIMAL(38,6) NOT NULL,
	`GrossPurchaseGC_Budget`  DECIMAL(38,6) NOT NULL,
	`DiscountAmountTC`  DECIMAL(38,6) NOT NULL,
	`DiscountAmountAC`  DECIMAL(38,6) NOT NULL,
	`DiscountAmountRC`  DECIMAL(38,6) NOT NULL,
	`DiscountAmountGC`  DECIMAL(38,6) NOT NULL,
	`DiscountAmountAC_Budget`  DECIMAL(38,6) NOT NULL,
	`DiscountAmountRC_Budget`  DECIMAL(38,6) NOT NULL,
	`DiscountAmountGC_Budget`  DECIMAL(38,6) NOT NULL,
	`InvoicedPurchaseAmountTC`  DECIMAL(38,6) NOT NULL,
	`InvoicedPurchaseAmountAC`  DECIMAL(38,6) NOT NULL,
	`InvoicedPurchaseAmountRC`  DECIMAL(38,6) NOT NULL,
	`InvoicedPurchaseAmountGC`  DECIMAL(38,6) NOT NULL,
	`InvoicedPurchaseAmountAC_Budget`  DECIMAL(38,6) NOT NULL,
	`InvoicedPurchaseAmountRC_Budget`  DECIMAL(38,6) NOT NULL,
	`InvoicedPurchaseAmountGC_Budget`  DECIMAL(38,6) NOT NULL,
	`MarkupAmountTC`  DECIMAL(38,6) NOT NULL,
	`MarkupAmountAC`  DECIMAL(38,6) NOT NULL,
	`MarkupAmountRC`  DECIMAL(38,6) NOT NULL,
	`MarkupAmountGC`  DECIMAL(38,6) NOT NULL,
	`MarkupAmountAC_Budget`  DECIMAL(38,6) NOT NULL,
	`MarkupAmountRC_Budget`  DECIMAL(38,6) NOT NULL,
	`MarkupAmountGC_Budget`  DECIMAL(38,6) NOT NULL,
	`NetPurchaseAmountTC`  DECIMAL(38,6) NOT NULL,
	`NetPurchaseAmountAC`  DECIMAL(38,6) NOT NULL,
	`NetPurchaseAmountRC`  DECIMAL(38,6) NOT NULL,
	`NetPurchaseAmountGC`  DECIMAL(38,6) NOT NULL,
	`NetPurchaseAmountAC_Budget`  DECIMAL(38,6) NOT NULL,
	`NetPurchaseAmountRC_Budget`  DECIMAL(38,6) NOT NULL,
	`NetPurchaseAmountGC_Budget`  DECIMAL(38,6) NOT NULL,
	`AppliedExchangeRateTC`  DECIMAL(38,6) ,
	`AppliedExchangeRateAC`  DECIMAL(38,21) NOT NULL,
	`AppliedExchangeRateRC`  DECIMAL(38,21) NOT NULL,
	`AppliedExchangeRateGC`  DECIMAL(38,21) NOT NULL,
	`AppliedExchangeRateAC_Budget`  DECIMAL(38,21) NOT NULL,
	`AppliedExchangeRateRC_Budget`  DECIMAL(38,21) NOT NULL,
	`AppliedExchangeRateGC_Budget`  DECIMAL(38,21) NOT NULL,
	`SurchargeTransportTC`  DECIMAL(38,6) ,
	`SurchargeTransportAC`  DECIMAL(38,6) NOT NULL,
	`SurchargeTransportRC`  DECIMAL(38,6) NOT NULL,
	`SurchargeTransportGC`  DECIMAL(38,6) NOT NULL,
	`SurchargeTransportAC_Budget`  DECIMAL(38,6) NOT NULL,
	`SurchargeTransportRC_Budget`  DECIMAL(38,6) NOT NULL,
	`SurchargeTransportGC_Budget`  DECIMAL(38,6) NOT NULL,
	`SurchargeTotalTC`  DECIMAL(38,6) ,
	`SurchargeTotalAC`  DECIMAL(38,6) NOT NULL,
	`SurchargeTotalRC`  DECIMAL(38,6) NOT NULL,
	`SurchargeTotalGC`  DECIMAL(38,6) NOT NULL,
	`SurchargeTotalAC_Budget`  DECIMAL(38,6) NOT NULL,
	`SurchargeTotalRC_Budget`  DECIMAL(38,6) NOT NULL,
	`SurchargeTotalGC_Budget`  DECIMAL(38,6) NOT NULL
)
;
