/****** Object:  Table [DataStore2].[SalesOrder]    Script Date: 03/03/2026 16:26:09 ******/



CREATE OR REPLACE TABLE `DataStore2`.`SalesOrder`(
	`SalesOrderIdScreening`  STRING NOT NULL,
	`SalesOrderCode`  STRING NOT NULL,
	`SalesOrderLineNumber`  DECIMAL(32,16) NOT NULL,
	`SalesOrderLineNumberCombination`  STRING,
	`DeliveryAddress`  STRING,
	`OrderTransaction`  STRING,
	`DocumentStatus`  STRING NOT NULL,
	`CompanyCode`  STRING,
	`InventTransCode`  STRING NOT NULL,
	`InventDimCode`  STRING NOT NULL,
	`DeliveryTermsCode`  STRING NOT NULL,
	`PaymentTermsCode`  STRING NOT NULL,
	`OrderCustomerCode`  STRING NOT NULL,
	`CustomerCode`  STRING NOT NULL,
	`ProductCode`  STRING NOT NULL,
	`SalesOrderStatus`  STRING NOT NULL,
	`DeliveryModeCode`  STRING NOT NULL,
	`DefaultExchangeRateType`  STRING NOT NULL,
	`BudgetExchangeRateType`  STRING NOT NULL,
	`TransactionCurrencyCode`  STRING,
	`AccountingCurrencyCode`  STRING NOT NULL,
	`ReportingCurrencyCode`  STRING NOT NULL,
	`GroupCurrencyCode`  STRING NOT NULL,
	`CreationDate` TIMESTAMP ,
	`RequestedShippingDate` TIMESTAMP ,
	`ConfirmedShippingDate` TIMESTAMP ,
	`RequestedDeliveryDate` TIMESTAMP ,
	`ConfirmedDeliveryDate` TIMESTAMP ,
	`FirstShipmentDate` TIMESTAMP ,
	`LastShipmentDate` TIMESTAMP ,
	`SalesUnit`  STRING NOT NULL,
	`OrderedQuantity_InventoryUnit`  DECIMAL(38,6) NOT NULL,
	`OrderedQuantity_PurchaseUnit`  DECIMAL(38,6) NOT NULL,
	`OrderedQuantity_SalesUnit`  DECIMAL(38,6) NOT NULL,
	`DeliveredQuantity_InventoryUnit`  DECIMAL(38,6) NOT NULL,
	`DeliveredQuantity_PurchaseUnit`  DECIMAL(38,6) NOT NULL,
	`DeliveredQuantity_SalesUnit`  DECIMAL(38,6) NOT NULL,
	`SalesPricePerUnitTC`  DECIMAL(38,6) NOT NULL,
	`SalesPricePerUnitAC`  DECIMAL(38,6) NOT NULL,
	`SalesPricePerUnitRC`  DECIMAL(38,6) NOT NULL,
	`SalesPricePerUnitGC`  DECIMAL(38,6) NOT NULL,
	`SalesPricePerUnitAC_Budget`  DECIMAL(38,6) NOT NULL,
	`SalesPricePerUnitRC_Budget`  DECIMAL(38,6) NOT NULL,
	`SalesPricePerUnitGC_Budget`  DECIMAL(38,6) NOT NULL,
	`GrossSalesTC`  DECIMAL(38,6) NOT NULL,
	`GrossSalesAC`  DECIMAL(38,6) NOT NULL,
	`GrossSalesRC`  DECIMAL(38,6) NOT NULL,
	`GrossSalesGC`  DECIMAL(38,6) NOT NULL,
	`GrossSalesAC_Budget`  DECIMAL(38,6) NOT NULL,
	`GrossSalesRC_Budget`  DECIMAL(38,6) NOT NULL,
	`GrossSalesGC_Budget`  DECIMAL(38,6) NOT NULL,
	`DiscountAmountTC`  DECIMAL(38,6) NOT NULL,
	`DiscountAmountAC`  DECIMAL(38,6) NOT NULL,
	`DiscountAmountRC`  DECIMAL(38,6) NOT NULL,
	`DiscountAmountGC`  DECIMAL(38,6) NOT NULL,
	`DiscountAmountAC_Budget`  DECIMAL(38,6) NOT NULL,
	`DiscountAmountRC_Budget`  DECIMAL(38,6) NOT NULL,
	`DiscountAmountGC_Budget`  DECIMAL(38,6) NOT NULL,
	`InvoicedSalesAmountTC`  DECIMAL(38,6) NOT NULL,
	`InvoicedSalesAmountAC`  DECIMAL(38,6) NOT NULL,
	`InvoicedSalesAmountRC`  DECIMAL(38,6) NOT NULL,
	`InvoicedSalesAmountGC`  DECIMAL(38,6) NOT NULL,
	`InvoicedSalesAmountAC_Budget`  DECIMAL(38,6) NOT NULL,
	`InvoicedSalesAmountRC_Budget`  DECIMAL(38,6) NOT NULL,
	`InvoicedSalesAmountGC_Budget`  DECIMAL(38,6) NOT NULL,
	`NetSalesAmountTC`  DECIMAL(38,6) NOT NULL,
	`NetSalesAmountAC`  DECIMAL(38,6) NOT NULL,
	`NetSalesAmountRC`  DECIMAL(38,6) NOT NULL,
	`NetSalesAmountGC`  DECIMAL(38,6) NOT NULL,
	`NetSalesAmountAC_Budget`  DECIMAL(38,6) NOT NULL,
	`NetSalesAmountRC_Budget`  DECIMAL(38,6) NOT NULL,
	`NetSalesAmountGC_Budget`  DECIMAL(38,6) NOT NULL,
	`CostOfGoodsSoldTC`  DECIMAL(38,6) NOT NULL,
	`CostOfGoodsSoldAC`  DECIMAL(38,6) NOT NULL,
	`CostOfGoodsSoldRC`  DECIMAL(38,6) NOT NULL,
	`CostOfGoodsSoldGC`  DECIMAL(38,6) NOT NULL,
	`CostOfGoodsSoldAC_Budget`  DECIMAL(38,6) NOT NULL,
	`CostOfGoodsSoldRC_Budget`  DECIMAL(38,6) NOT NULL,
	`CostOfGoodsSoldGC_Budget`  DECIMAL(38,6) NOT NULL,
	`AppliedExchangeRateTC`  DECIMAL(38,6) ,
	`AppliedExchangeRateAC`  DECIMAL(38,21) NOT NULL,
	`AppliedExchangeRateRC`  DECIMAL(38,21) NOT NULL,
	`AppliedExchangeRateGC`  DECIMAL(38,21) NOT NULL,
	`AppliedExchangeRateAC_Budget`  DECIMAL(38,21) NOT NULL,
	`AppliedExchangeRateRC_Budget`  DECIMAL(38,21) NOT NULL,
	`AppliedExchangeRateGC_Budget`  DECIMAL(38,21) NOT NULL,
	`SurchargeTransportTC`  DECIMAL(38,6) ,
	`SurchargeTransportAC`  DECIMAL(38,6) NOT NULL,
	`SurchargeTransportRC`  DECIMAL(38,6) NOT NULL,
	`SurchargeTransportGC`  DECIMAL(38,6) NOT NULL,
	`SurchargeTransportAC_Budget`  DECIMAL(38,6) NOT NULL,
	`SurchargeTransportRC_Budget`  DECIMAL(38,6) NOT NULL,
	`SurchargeTransportGC_Budget`  DECIMAL(38,6) NOT NULL,
	`SurchargePurchaseTC`  DECIMAL(38,6) ,
	`SurchargePurchaseAC`  DECIMAL(38,6) NOT NULL,
	`SurchargePurchaseRC`  DECIMAL(38,6) NOT NULL,
	`SurchargePurchaseGC`  DECIMAL(38,6) NOT NULL,
	`SurchargePurchaseAC_Budget`  DECIMAL(38,6) NOT NULL,
	`SurchargePurchaseRC_Budget`  DECIMAL(38,6) NOT NULL,
	`SurchargePurchaseGC_Budget`  DECIMAL(38,6) NOT NULL,
	`SurchargeDeliveryTC`  DECIMAL(38,6) ,
	`SurchargeDeliveryAC`  DECIMAL(38,6) NOT NULL,
	`SurchargeDeliveryRC`  DECIMAL(38,6) NOT NULL,
	`SurchargeDeliveryGC`  DECIMAL(38,6) NOT NULL,
	`SurchargeDeliveryAC_Budget`  DECIMAL(38,6) NOT NULL,
	`SurchargeDeliveryRC_Budget`  DECIMAL(38,6) NOT NULL,
	`SurchargeDeliveryGC_Budget`  DECIMAL(38,6) NOT NULL,
	`SurchargeTotalTC`  DECIMAL(38,6) ,
	`SurchargeTotalAC`  DECIMAL(38,6) NOT NULL,
	`SurchargeTotalRC`  DECIMAL(38,6) NOT NULL,
	`SurchargeTotalGC`  DECIMAL(38,6) NOT NULL,
	`SurchargeTotalAC_Budget`  DECIMAL(38,6) NOT NULL,
	`SurchargeTotalRC_Budget`  DECIMAL(38,6) NOT NULL,
	`SurchargeTotalGC_Budget`  DECIMAL(38,6) NOT NULL
)
;
