/****** Object:  Table [DataStore2].[NetRequirements]    Script Date: 03/03/2026 16:26:08 ******/



CREATE OR REPLACE TABLE `DataStore2`.`NetRequirements`(
	`RecId` bigint NOT NULL,
	`CompanyCode`  STRING NOT NULL,
	`ReferenceType`  STRING NOT NULL,
	`PlanVersion`  STRING NOT NULL,
	`ProductCode`  STRING NOT NULL,
	`InventDimCode`  STRING NOT NULL,
	`RequirementDate` TIMESTAMP ,
	`RequirementTime`  STRING NOT NULL,
	`RequirementDateTime` TIMESTAMP ,
	`ReferenceCode`  STRING NOT NULL,
	`ProducedItemCode`  STRING,
	`CustomerCode`  STRING NOT NULL,
	`VendorCode`  STRING,
	`ActionDate` TIMESTAMP ,
	`ActionDays` int NOT NULL,
	`ActionType`  STRING NOT NULL,
	`ActionMarked`  STRING NOT NULL,
	`FuturesDate` TIMESTAMP NOT NULL,
	`FuturesDays` int NOT NULL,
	`FuturesCalculated`  STRING NOT NULL,
	`FuturesMarked`  STRING NOT NULL,
	`Direction`  STRING NOT NULL,
	`RankNr` BIGINT,
	`FictionalOOS` int NOT NULL,
	`ActualOOS` int NOT NULL,
	`FictionalOOS_Confirmed` int NOT NULL,
	`ActualOOS_Confirmed` int NOT NULL,
	`Quantity_InventoryUnit`  DECIMAL(32,6) NOT NULL,
	`Quantity_PurchaseUnit`  DECIMAL(38,6) NOT NULL,
	`Quantity_SalesUnit`  DECIMAL(38,6) NOT NULL,
	`AccumulatedQuantity_InventoryUnit`  DECIMAL(38,6) NOT NULL,
	`AccumulatedQuantity_PurchaseUnit`  DECIMAL(38,6) NOT NULL,
	`AccumulatedQuantity_SalesUnit`  DECIMAL(38,6) NOT NULL,
	`QuantityConfirmed_InventoryUnit`  DECIMAL(32,6) NOT NULL,
	`QuantityConfirmed_PurchaseUnit`  DECIMAL(38,6) NOT NULL,
	`QuantityConfirmed_SalesUnit`  DECIMAL(38,6) NOT NULL,
	`AccumulatedQuantityConfirmed_InventoryUnit`  DECIMAL(38,6) NOT NULL,
	`AccumulatedQuantityConfirmed_PurchaseUnit`  DECIMAL(38,6) NOT NULL,
	`AccumulatedQuantityConfirmed_SalesUnit`  DECIMAL(38,6) NOT NULL,
	`ValueAC`  DECIMAL(38,6) NOT NULL,
	`ValueGC`  DECIMAL(38,6) NOT NULL,
	`PriceAC`  DECIMAL(38,9) NOT NULL,
	`PriceGC`  DECIMAL(38,6) NOT NULL
)
;
