/****** Object:  Table [DataStore4].[ProductionOrder]    Script Date: 03/03/2026 16:26:08 ******/



CREATE OR REPLACE TABLE `DataStore4`.`ProductionOrder`(
	`ProductionOrderCode`  STRING NOT NULL,
	`ProductionOrderStatus`  STRING NOT NULL,
	`CompanyCode`  STRING NOT NULL,
	`ProductCode`  STRING NOT NULL,
	`RouteCode`  STRING NOT NULL,
	`SiteCode`  STRING NOT NULL,
	`OperationCode`  STRING NOT NULL,
	`OperationNumber` int NOT NULL,
	`ResourceCode`  STRING NOT NULL,
	`CalculationType`  STRING NOT NULL,
	`ProductionResourceCode`  STRING NOT NULL,
	`CostGroupCode`  STRING NOT NULL,
	`InventDimCode`  STRING NOT NULL,
	`BOMCode`  STRING NOT NULL,
	`AccountingCurrencyCode`  STRING NOT NULL,
	`ReportingCurrencyCode`  STRING NOT NULL,
	`GroupCurrencyCode`  STRING NOT NULL,
	`DefaultExchangeRateTypeCode`  STRING NOT NULL,
	`BudgetExchangeRateTypeCode`  STRING NOT NULL,
	`AppliedExchangeRateAC`  DECIMAL(38,6) ,
	`AppliedExchangeRateRC`  DECIMAL(38,21) NOT NULL,
	`AppliedExchangeRateGC`  DECIMAL(38,21) NOT NULL,
	`AppliedExchangeRateRC_Budget`  DECIMAL(38,21) NOT NULL,
	`AppliedExchangeRateGC_Budget`  DECIMAL(38,21) NOT NULL,
	`JournalPostingDate` TIMESTAMP NOT NULL,
	`RequestedDeliveryDate` TIMESTAMP NOT NULL,
	`ScheduledDeliveryDate` TIMESTAMP NOT NULL,
	`ActualDeliveryDate` TIMESTAMP NOT NULL,
	`ScheduledProductionStartDate` TIMESTAMP NOT NULL,
	`ScheduledProductionEndDate` TIMESTAMP NOT NULL,
	`ProductionStartDate` TIMESTAMP ,
	`ProductionEndDate` TIMESTAMP ,
	`OTIF`  DECIMAL(38,6) NOT NULL,
	`InventUnit`  STRING NOT NULL,
	`OriginalEstimatedQuantity_InventoryUnit`  DECIMAL(38,6) NOT NULL,
	`OriginalEstimatedQuantity_PurchaseUnit`  DECIMAL(38,6) NOT NULL,
	`OriginalEstimatedQuantity_SalesUnit`  DECIMAL(38,6) NOT NULL,
	`OriginalEstimatedQuantityDetail_InventoryUnit`  DECIMAL(38,6) NOT NULL,
	`OriginalEstimatedQuantityDetail_PurchaseUnit`  DECIMAL(38,6) NOT NULL,
	`OriginalEstimatedQuantityDetail_SalesUnit`  DECIMAL(38,6) NOT NULL,
	`EstimatedQuantity_InventoryUnit`  DECIMAL(38,6) NOT NULL,
	`EstimatedQuantity_PurchaseUnit`  DECIMAL(38,6) NOT NULL,
	`EstimatedQuantity_SalesUnit`  DECIMAL(38,6) NOT NULL,
	`EstimatedQuantityDetail_InventoryUnit`  DECIMAL(38,6) NOT NULL,
	`EstimatedQuantityDetail_PurchaseUnit`  DECIMAL(38,6) NOT NULL,
	`EstimatedQuantityDetail_SalesUnit`  DECIMAL(38,6) NOT NULL,
	`ProducedQuantity_InventoryUnit`  DECIMAL(38,6) NOT NULL,
	`ProducedQuantity_PurchaseUnit`  DECIMAL(38,6) NOT NULL,
	`ProducedQuantity_SalesUnit`  DECIMAL(38,6) NOT NULL,
	`ProducedQuantityDetail_InventoryUnit`  DECIMAL(38,6) NOT NULL,
	`ProducedQuantityDetail_PurchaseUnit`  DECIMAL(38,6) NOT NULL,
	`ProducedQuantityDetail_SalesUnit`  DECIMAL(38,6) NOT NULL,
	`TotalEstimatedConsumptionQuantity_InventoryUnit`  DECIMAL(38,6) NOT NULL,
	`TotalEstimatedConsumptionQuantity_PurchaseUnit`  DECIMAL(38,6) NOT NULL,
	`TotalEstimatedConsumptionQuantity_SalesUnit`  DECIMAL(38,6) NOT NULL,
	`NetEstimatedConsumptionQuantity_InventoryUnit`  DECIMAL(38,6) NOT NULL,
	`NetEstimatedConsumptionQuantity_PurchaseUnit`  DECIMAL(38,6) NOT NULL,
	`NetEstimatedConsumptionQuantity_SalesUnit`  DECIMAL(38,6) NOT NULL,
	`RealConsumptionQuantity_InventoryUnit`  DECIMAL(38,6) NOT NULL,
	`RealConsumptionQuantity_PurchaseUnit`  DECIMAL(38,6) NOT NULL,
	`RealConsumptionQuantity_SalesUnit`  DECIMAL(38,6) NOT NULL,
	`TotalScrapQuantity_InventoryUnit`  DECIMAL(38,6) NOT NULL,
	`TotalScrapQuantity_PurchaseUnit`  DECIMAL(38,6) NOT NULL,
	`TotalScrapQuantity_SalesUnit`  DECIMAL(38,6) NOT NULL,
	`NetScrapQuantity_InventoryUnit`  DECIMAL(38,6) NOT NULL,
	`NetScrapQuantity_PurchaseUnit`  DECIMAL(38,6) NOT NULL,
	`NetScrapQuantity_SalesUnit`  DECIMAL(38,6) NOT NULL,
	`ReportRemainderAsFinished_InventoryUnit`  DECIMAL(38,6) NOT NULL,
	`ReportRemainderAsFinished_PurchaseUnit`  DECIMAL(38,6) NOT NULL,
	`ReportRemainderAsFinished_SalesUnit`  DECIMAL(38,6) NOT NULL,
	`ReportRemainderAsFinishedDetail_InventoryUnit`  DECIMAL(38,6) NOT NULL,
	`ReportRemainderAsFinishedDetail_PurchaseUnit`  DECIMAL(38,6) NOT NULL,
	`ReportRemainderAsFinishedDetail_SalesUnit`  DECIMAL(38,6) NOT NULL,
	`EstimatedCostAmountAC`  DECIMAL(38,6) ,
	`EstimatedCostAmountRC`  DECIMAL(38,6) NOT NULL,
	`EstimatedCostAmountGC`  DECIMAL(38,6) NOT NULL,
	`EstimatedCostAmountRC_Budget`  DECIMAL(38,6) NOT NULL,
	`EstimatedCostAmountGC_Budget`  DECIMAL(38,6) NOT NULL,
	`RealCostAmountAC`  DECIMAL(33,17) ,
	`RealCostAmountRC`  DECIMAL(38,6) NOT NULL,
	`RealCostAmountGC`  DECIMAL(38,6) NOT NULL,
	`RealCostAmountRC_Budget`  DECIMAL(38,6) NOT NULL,
	`RealCostAmountGC_Budget`  DECIMAL(38,6) NOT NULL,
	`TotalScrapAmountAC`  DECIMAL(38,6) ,
	`TotalScrapAmountRC`  DECIMAL(38,6) NOT NULL,
	`TotalScrapAmountGC`  DECIMAL(38,6) NOT NULL,
	`TotalScrapAmountRC_Budget`  DECIMAL(38,6) NOT NULL,
	`TotalScrapAmountGC_Budget`  DECIMAL(38,6) NOT NULL,
	`NetScrapAmountAC`  DECIMAL(38,6) ,
	`NetScrapAmountRC`  DECIMAL(38,6) NOT NULL,
	`NetScrapAmountGC`  DECIMAL(38,6) NOT NULL,
	`NetScrapAmountRC_Budget`  DECIMAL(38,6) NOT NULL,
	`NetScrapAmountGC_Budget`  DECIMAL(38,6) NOT NULL
)
;
