/****** Object:  Table [DataStore2].[SalesInvoice]    Script Date: 03/03/2026 16:26:09 ******/



CREATE OR REPLACE TABLE `DataStore2`.`SalesInvoice`(
	`SalesInvoiceCode`  STRING NOT NULL,
	`TransactionType`  STRING,
	`SalesInvoiceLineNumber`  DECIMAL(32,16) NOT NULL,
	`SalesInvoiceLineNumberCombination`  STRING,
	`CompanyCode`  STRING,
	`SalesOrderCode`  STRING NOT NULL,
	`SalesOrderStatus`  STRING,
	`InventTransCode`  STRING NOT NULL,
	`InventDimCode`  STRING NOT NULL,
	`TaxWriteCode` INT,
	`CustomerCode`  STRING NOT NULL,
	`ProductCode`  STRING NOT NULL,
	`PaymentTermsCode`  STRING NOT NULL,
	`DeliveryModeCode`  STRING NOT NULL,
	`DeliveryTermsCode`  STRING NOT NULL,
	`OrderCustomerCode`  STRING NOT NULL,
	`DefaultExchangeRateTypeCode`  STRING NOT NULL,
	`BudgetExchangeRateTypeCode`  STRING NOT NULL,
	`TransactionCurrencyCode`  STRING,
	`AccountingCurrencyCode`  STRING NOT NULL,
	`ReportingCurrencyCode`  STRING NOT NULL,
	`GroupCurrencyCode`  STRING NOT NULL,
	`GLAccountCode`  STRING NOT NULL,
	`IntercompanyCode`  STRING NOT NULL,
	`BusinessSegmentCode`  STRING NOT NULL,
	`DeparmentCode`  STRING NOT NULL,
	`EndCustomerCode`  STRING NOT NULL,
	`LocationCode`  STRING NOT NULL,
	`ShipmentContractCode`  STRING NOT NULL,
	`LocalAccountCode`  STRING NOT NULL,
	`ProductFDCode`  STRING NOT NULL,
	`InvoiceDate` TIMESTAMP ,
	`RequestedDeliveryDate` TIMESTAMP ,
	`ConfirmedDeliveryDate` TIMESTAMP ,
	`SalesUnit`  STRING NOT NULL,
	`InvoicedQuantity_InventoryUnit`  DECIMAL(38,6) NOT NULL,
	`InvoicedQuantity_PurchaseUnit`  DECIMAL(38,6) NOT NULL,
	`InvoicedQuantity_SalesUnit`  DECIMAL(38,6) NOT NULL,
	`SalesPricePerUnitTC`  DECIMAL(38,6) ,
	`SalesPricePerUnitAC`  DECIMAL(38,6) ,
	`SalesPricePerUnitRC`  DECIMAL(38,6) ,
	`SalesPricePerUnitGC`  DECIMAL(38,6) ,
	`SalesPricePerUnitAC_Budget`  DECIMAL(38,6) ,
	`SalesPricePerUnitRC_Budget`  DECIMAL(38,6) ,
	`SalesPricePerUnitGC_Budget`  DECIMAL(38,6) ,
	`GrossSalesTC`  DECIMAL(38,6) ,
	`GrossSalesAC`  DECIMAL(38,6) ,
	`GrossSalesRC`  DECIMAL(38,6) ,
	`GrossSalesGC`  DECIMAL(38,6) ,
	`GrossSalesAC_Budget`  DECIMAL(38,6) ,
	`GrossSalesRC_Budget`  DECIMAL(38,6) ,
	`GrossSalesGC_Budget`  DECIMAL(38,6) ,
	`DiscountAmountTC`  DECIMAL(38,6) ,
	`DiscountAmountAC`  DECIMAL(38,6) ,
	`DiscountAmountRC`  DECIMAL(38,6) ,
	`DiscountAmountGC`  DECIMAL(38,6) ,
	`DiscountAmountAC_Budget`  DECIMAL(38,6) ,
	`DiscountAmountRC_Budget`  DECIMAL(38,6) ,
	`DiscountAmountGC_Budget`  DECIMAL(38,6) ,
	`InvoicedSalesAmountTC`  DECIMAL(38,6) ,
	`InvoicedSalesAmountAC`  DECIMAL(38,6) ,
	`InvoicedSalesAmountRC`  DECIMAL(38,6) ,
	`InvoicedSalesAmountGC`  DECIMAL(38,6) ,
	`InvoicedSalesAmountAC_Budget`  DECIMAL(38,6) ,
	`InvoicedSalesAmountRC_Budget`  DECIMAL(38,6) ,
	`InvoicedSalesAmountGC_Budget`  DECIMAL(38,6) ,
	`NetSalesAmountTC`  DECIMAL(38,6) ,
	`NetSalesAmountAC`  DECIMAL(38,6) ,
	`NetSalesAmountRC`  DECIMAL(38,6) ,
	`NetSalesAmountGC`  DECIMAL(38,6) ,
	`NetSalesAmountAC_Budget`  DECIMAL(38,6) ,
	`NetSalesAmountRC_Budget`  DECIMAL(38,6) ,
	`NetSalesAmountGC_Budget`  DECIMAL(38,6) ,
	`RebateAmountOriginalTC`  DECIMAL(38,6) ,
	`RebateAmountOriginalAC`  DECIMAL(38,6) ,
	`RebateAmountOriginalRC`  DECIMAL(38,6) ,
	`RebateAmountOriginalGC`  DECIMAL(38,6) ,
	`RebateAmountOriginalAC_Budget`  DECIMAL(38,6) ,
	`RebateAmountOriginalRC_Budget`  DECIMAL(38,6) ,
	`RebateAmountOriginalGC_Budget`  DECIMAL(38,6) ,
	`RebateAmountCompletedTC`  DECIMAL(38,6) ,
	`RebateAmountCompletedAC`  DECIMAL(38,6) ,
	`RebateAmountCompletedRC`  DECIMAL(38,6) ,
	`RebateAmountCompletedGC`  DECIMAL(38,6) ,
	`RebateAmountCompletedAC_Budget`  DECIMAL(38,6) ,
	`RebateAmountCompletedRC_Budget`  DECIMAL(38,6) ,
	`RebateAmountCompletedGC_Budget`  DECIMAL(38,6) ,
	`RebateAmountMarkedTC`  DECIMAL(38,6) ,
	`RebateAmountMarkedAC`  DECIMAL(38,6) ,
	`RebateAmountMarkedRC`  DECIMAL(38,6) ,
	`RebateAmountMarkedGC`  DECIMAL(38,6) ,
	`RebateAmountMarkedAC_Budget`  DECIMAL(38,6) ,
	`RebateAmountMarkedRC_Budget`  DECIMAL(38,6) ,
	`RebateAmountMarkedGC_Budget`  DECIMAL(38,6) ,
	`RebateAmountCancelledTC`  DECIMAL(38,6) ,
	`RebateAmountCancelledAC`  DECIMAL(38,6) ,
	`RebateAmountCancelledRC`  DECIMAL(38,6) ,
	`RebateAmountCancelledGC`  DECIMAL(38,6) ,
	`RebateAmountCancelledAC_Budget`  DECIMAL(38,6) ,
	`RebateAmountCancelledRC_Budget`  DECIMAL(38,6) ,
	`RebateAmountCancelledGC_Budget`  DECIMAL(38,6) ,
	`RebateAmountVarianceTC`  DECIMAL(38,6) ,
	`RebateAmountVarianceAC`  DECIMAL(38,6) ,
	`RebateAmountVarianceRC`  DECIMAL(38,6) ,
	`RebateAmountVarianceGC`  DECIMAL(38,6) ,
	`RebateAmountVarianceAC_Budget`  DECIMAL(38,6) ,
	`RebateAmountVarianceRC_Budget`  DECIMAL(38,6) ,
	`RebateAmountVarianceGC_Budget`  DECIMAL(38,6) ,
	`CostOfGoodsSoldTC`  DECIMAL(38,6) NOT NULL,
	`CostOfGoodsSoldAC`  DECIMAL(38,6) NOT NULL,
	`CostOfGoodsSoldRC`  DECIMAL(38,6) NOT NULL,
	`CostOfGoodsSoldGC`  DECIMAL(38,6) NOT NULL,
	`CostOfGoodsSoldAC_Budget`  DECIMAL(38,6) NOT NULL,
	`CostOfGoodsSoldRC_Budget`  DECIMAL(38,6) NOT NULL,
	`CostOfGoodsSoldGC_Budget`  DECIMAL(38,6) NOT NULL,
	`SurchargeTotalTC`  DECIMAL(38,6) ,
	`SurchargeTotalAC`  DECIMAL(38,6) ,
	`SurchargeTotalRC`  DECIMAL(38,6) ,
	`SurchargeTotalGC`  DECIMAL(38,6) ,
	`SurchargeTotalAC_Budget`  DECIMAL(38,6) ,
	`SurchargeTotalRC_Budget`  DECIMAL(38,6) ,
	`SurchargeTotalGC_Budget`  DECIMAL(38,6) ,
	`AppliedExchangeRateTC`  DECIMAL(38,6) ,
	`AppliedExchangeRateAC`  DECIMAL(38,6) ,
	`AppliedExchangeRateRC`  DECIMAL(38,6) ,
	`AppliedExchangeRateGC`  DECIMAL(38,6) ,
	`AppliedExchangeRateAC_Budget`  DECIMAL(38,6) ,
	`AppliedExchangeRateRC_Budget`  DECIMAL(38,6) ,
	`AppliedExchangeRateGC_Budget`  DECIMAL(38,6) 
)
;
