/****** Object:  Table [DataStore2].[SalesBudget]    Script Date: 03/03/2026 16:26:08 ******/



CREATE OR REPLACE TABLE `DataStore2`.`SalesBudget`(
	`SalesBudgetIdScreening`  STRING NOT NULL,
	`Comment`  STRING NOT NULL,
	`CompanyCode`  STRING,
	`ProductCode`  STRING NOT NULL,
	`ProductGroupCode`  STRING NOT NULL,
	`CustomerCode`  STRING NOT NULL,
	`CustomerGroupCode`  STRING NOT NULL,
	`ForecastModelCode`  STRING NOT NULL,
	`InventDimCode`  STRING NOT NULL,
	`DefaultExchangeRateTypeCode`  STRING NOT NULL,
	`BudgetExchangeRateTypeCode`  STRING NOT NULL,
	`TransactionCurrencyCode`  STRING,
	`AccountingCurrencyCode`  STRING NOT NULL,
	`ReportingCurrencyCode`  STRING NOT NULL,
	`GroupCurrencyCode`  STRING NOT NULL,
	`GLAccountCode`  STRING NOT NULL,
	`IntercompanyCode`  STRING NOT NULL,
	`ForecastDate` TIMESTAMP NOT NULL,
	`SalesUnit`  STRING NOT NULL,
	`ForecastQuantity`  DECIMAL(32,6) NOT NULL,
	`ForecastQuantity_InventoryUnit`  DECIMAL(38,6) NOT NULL,
	`ForecastQuantity_PurchaseUnit`  DECIMAL(38,6) NOT NULL,
	`ForecastQuantity_SalesUnit`  DECIMAL(38,6) NOT NULL,
	`GrossSalesAmountTC`  DECIMAL(32,6) NOT NULL,
	`GrossSalesAmountAC`  DECIMAL(38,6) NOT NULL,
	`GrossSalesAmountRC`  DECIMAL(38,6) NOT NULL,
	`GrossSalesAmountGC`  DECIMAL(38,6) NOT NULL,
	`GrossSalesAmountAC_Budget`  DECIMAL(38,6) NOT NULL,
	`GrossSalesAmountRC_Budget`  DECIMAL(38,6) NOT NULL,
	`GrossSalesAmountGC_Budget`  DECIMAL(38,6) NOT NULL,
	`CostPriceTC`  DECIMAL(38,6) NOT NULL,
	`CostPriceAC`  DECIMAL(38,6) NOT NULL,
	`CostPriceRC`  DECIMAL(38,6) NOT NULL,
	`CostPriceGC`  DECIMAL(38,6) NOT NULL,
	`CostPriceAC_Budget`  DECIMAL(38,6) NOT NULL,
	`CostPriceRC_Budget`  DECIMAL(38,6) NOT NULL,
	`CostPriceGC_Budget`  DECIMAL(38,6) NOT NULL,
	`GrossMarginTC`  DECIMAL(38,6) ,
	`GrossMarginAC`  DECIMAL(38,6) NOT NULL,
	`GrossMarginRC`  DECIMAL(38,6) NOT NULL,
	`GrossMarginGC`  DECIMAL(38,6) NOT NULL,
	`GrossMarginAC_Budget`  DECIMAL(38,6) NOT NULL,
	`GrossMarginRC_Budget`  DECIMAL(38,6) NOT NULL,
	`GrossMarginGC_Budget`  DECIMAL(38,6) NOT NULL,
	`AppliedExchangeRateTC`  DECIMAL(38,6) ,
	`AppliedExchangeRateRC`  DECIMAL(38,21) NOT NULL,
	`AppliedExchangeRateAC`  DECIMAL(38,21) NOT NULL,
	`AppliedExchangeRateGC`  DECIMAL(38,21) NOT NULL,
	`AppliedExchangeRateRC_Budget`  DECIMAL(38,21) NOT NULL,
	`AppliedExchangeRateAC_Budget`  DECIMAL(38,21) NOT NULL,
	`AppliedExchangeRateGC_Budget`  DECIMAL(38,21) NOT NULL
)
;
