/****** Object:  Table [DataStore].[AccountsReceivable]    Script Date: 03/03/2026 16:26:08 ******/



CREATE OR REPLACE TABLE `DataStore`.`AccountsReceivable`(
	`AccountsReceivableIdScreening`  STRING NOT NULL,
	`RecId` bigint NOT NULL,
	`ReceivablesVoucher`  STRING NOT NULL,
	`Description`  STRING NOT NULL,
	`SalesInvoiceCode`  STRING NOT NULL,
	`CompanyCode`  STRING NOT NULL,
	`DimIsOpenAmountId` int NOT NULL,
	`OutStandingPeriodCode`  STRING NOT NULL,
	`Test` TIMESTAMP ,
	`CustomerCode`  STRING,
	`DefaultExchangeRateTypeCode`  STRING NOT NULL,
	`BudgetExchangeRateTypeCode`  STRING NOT NULL,
	`TransactionCurrencyCode`  STRING NOT NULL,
	`AccountingCurrencyCode`  STRING NOT NULL,
	`ReportingCurrencyCode`  STRING NOT NULL,
	`GroupCurrencyCode`  STRING NOT NULL,
	`InvoiceDate` TIMESTAMP NOT NULL,
	`DueDate` TIMESTAMP ,
	`LastPaymentDate` TIMESTAMP NOT NULL,
	`DocumentDate` TIMESTAMP ,
	`ReportDate` INT,
	`InvoiceAmountTC` decimal(22, 6),
	`InvoiceAmountAC` decimal(38, 6) NOT NULL,
	`InvoiceAmountRC` decimal(38, 6) NOT NULL,
	`InvoiceAmountGC` decimal(38, 6) NOT NULL,
	`InvoiceAmountAC_Budget` decimal(38, 6) NOT NULL,
	`InvoiceAmountRC_Budget` decimal(38, 6) NOT NULL,
	`InvoiceAmountGC_Budget` decimal(38, 6) NOT NULL,
	`PaidAmountTC`  DECIMAL(38,6) ,
	`PaidAmountAC`  DECIMAL(38,6) NOT NULL,
	`PaidAmountRC`  DECIMAL(38,6) NOT NULL,
	`PaidAmountGC`  DECIMAL(38,6) NOT NULL,
	`PaidAmountAC_Budget`  DECIMAL(38,6) NOT NULL,
	`PaidAmountRC_Budget`  DECIMAL(38,6) NOT NULL,
	`PaidAmountGC_Budget`  DECIMAL(38,6) NOT NULL,
	`OpenAmountTC`  DECIMAL(38,6) ,
	`OpenAmountAC`  DECIMAL(38,6) NOT NULL,
	`OpenAmountRC`  DECIMAL(38,6) NOT NULL,
	`OpenAmountGC`  DECIMAL(38,6) NOT NULL,
	`OpenAmountAC_Budget`  DECIMAL(38,6) NOT NULL,
	`OpenAmountRC_Budget`  DECIMAL(38,6) NOT NULL,
	`OpenAmountGC_Budget`  DECIMAL(38,6) NOT NULL,
	`AppliedExchangeRateTC`  DECIMAL(38,6) ,
	`AppliedExchangeRateAC`  DECIMAL(38,17) NOT NULL,
	`AppliedExchangeRateRC`  DECIMAL(38,17) NOT NULL,
	`AppliedExchangeRateGC`  DECIMAL(38,17) NOT NULL,
	`AppliedExchangeRateAC_Budget`  DECIMAL(38,17) NOT NULL,
	`AppliedExchangeRateRC_Budget`  DECIMAL(38,17) NOT NULL,
	`AppliedExchangeRateGC_Budget`  DECIMAL(38,17) NOT NULL
)
;
