/****** Object:  Table [DataStore3].[ProductionOrder]    Script Date: 03/03/2026 16:26:08 ******/



CREATE OR REPLACE TABLE `DataStore3`.`ProductionOrder`(
	`ProductionOrderCode`  STRING NOT NULL,
	`ProductionOrderStatus`  STRING NOT NULL,
	`CompanyCode`  STRING NOT NULL,
	`ProductCode`  STRING NOT NULL,
	`RouteCode`  STRING NOT NULL,
	`SiteCode`  STRING NOT NULL,
	`OperationCode`  STRING NOT NULL,
	`OperationNumber` int NOT NULL,
	`ResourceCode`  STRING NOT NULL,
	`CalculationType`  STRING NOT NULL,
	`ProductionResourceCode`  STRING NOT NULL,
	`CostGroupCode`  STRING NOT NULL,
	`InventDimCode`  STRING NOT NULL,
	`BOMCode`  STRING NOT NULL,
	`TransactionType`  STRING NOT NULL,
	`JournalPostingDate` TIMESTAMP NOT NULL,
	`RequestedDeliveryDate` TIMESTAMP NOT NULL,
	`ScheduledDeliveryDate` TIMESTAMP NOT NULL,
	`ActualDeliveryDate` TIMESTAMP NOT NULL,
	`ScheduledProductionStartDate` TIMESTAMP NOT NULL,
	`ScheduledProductionEndDate` TIMESTAMP NOT NULL,
	`ProductionStartDate` TIMESTAMP ,
	`ProductionEndDate` TIMESTAMP ,
	`OTIF`  DECIMAL(38,6) NOT NULL,
	`InventUnit`  STRING NOT NULL,
	`OriginalEstimatedQuantity`  DECIMAL(32,6) NOT NULL,
	`OriginalEstimatedQuantityDetail`  DECIMAL(38,12) ,
	`EstimatedQuantity`  DECIMAL(32,6) NOT NULL,
	`EstimatedQuantityDetail`  DECIMAL(38,12) ,
	`ProducedQuantity`  DECIMAL(38,6) NOT NULL,
	`ProducedQuantityDetail`  DECIMAL(38,6) ,
	`ReportRemainderAsFinished`  DECIMAL(32,6) NOT NULL,
	`ReportRemainderAsFinishedDetail`  DECIMAL(38,12) ,
	`NetEstimatedConsumptionQuantity`  DECIMAL(38,6) ,
	`TotalEstimatedConsumptionQuantity`  DECIMAL(34,17) ,
	`RealConsumptionQuantity`  DECIMAL(33,17) ,
	`Price_UsedBOMLines`  DECIMAL(38,9) ,
	`TotalEstimatedCostAmountAC`  DECIMAL(34,17) ,
	`EstimatedCostAmountAC`  DECIMAL(38,6) ,
	`RealCostAmountAC`  DECIMAL(33,17) ,
	`TotalScrapQuantity`  DECIMAL(38,6) ,
	`ConstantScrapQuantity`  DECIMAL(38,6) ,
	`VariableScrapQuantity`  DECIMAL(38,6) ,
	`NetScrapQuantity`  DECIMAL(38,6) ,
	`TotalScrapAmountAC`  DECIMAL(38,6) ,
	`NetScrapAmountAC`  DECIMAL(38,6) 
)
;
