/****** Object:  Table [dbo].[SMRBIWrkCtrCapResStaging]    Script Date: 03/03/2026 16:26:08 ******/



CREATE OR REPLACE TABLE `dbo`.`SMRBIWrkCtrCapResStaging`(
	`DEFINITIONGROUP`  STRING NOT NULL,
	`EXECUTIONID`  STRING NOT NULL,
	`ISSELECTED` int NOT NULL,
	`TRANSFERSTATUS` int NOT NULL,
	`COMPANY`  STRING NOT NULL,
	`ENDTIME` int NOT NULL,
	`REFID`  STRING NOT NULL,
	`REFTYPE` int NOT NULL,
	`STARTTIME` int NOT NULL,
	`TRANSDATE` TIMESTAMP NOT NULL,
	`WRKCTRID`  STRING NOT NULL,
	`WRKCTRLOADPCT`  DECIMAL(32,6) NOT NULL,
	`WRKCTRSEC`  DECIMAL(32,6) NOT NULL,
	`PLANVERSION` bigint NOT NULL,
	`PARTITION`  STRING NOT NULL,
	`DATAAREAID`  STRING NOT NULL,
	`SYNCSTARTDATETIME` TIMESTAMP NOT NULL,
	`RECID` bigint NOT NULL,
 CONSTRAINT `PK_SMRBIWrkCtrCapResStaging` PRIMARY KEY CLUSTERED 
(
	`EXECUTIONID` ASC,
	`COMPANY` ASC,
	`ENDTIME` ASC,
	`REFID` ASC,
	`REFTYPE` ASC,
	`STARTTIME` ASC,
	`TRANSDATE` ASC,
	`WRKCTRID` ASC,
	`WRKCTRLOADPCT` ASC,
	`WRKCTRSEC` ASC,
	`DATAAREAID` ASC,
	`PARTITION` ASC
)WITH(STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
;
