/****** Object:  Table [dbo].[YSLEShipmentDetailsStaging]    Script Date: 03/03/2026 16:26:08 ******/



CREATE OR REPLACE TABLE `dbo`.`YSLEShipmentDetailsStaging`(
	`DEFINITIONGROUP`  STRING NOT NULL,
	`EXECUTIONID`  STRING NOT NULL,
	`ISSELECTED` int NOT NULL,
	`TRANSFERSTATUS` int NOT NULL,
	`SHIPMENT`  STRING NOT NULL,
	`LINEOFBUSINESSID`  STRING NOT NULL,
	`CUSTACCOUNT`  STRING NOT NULL,
	`CUSTNAME`  STRING NOT NULL,
	`JOBOWNER`  STRING NOT NULL,
	`BUSINESSOWNER`  STRING NOT NULL,
	`DESTINATIONAGENT`  STRING NOT NULL,
	`BRANCH`  STRING NOT NULL,
	`DEPARTMENT`  STRING NOT NULL,
	`MASTERBILLOFLADING`  STRING NOT NULL,
	`HOUSEBILLOFLADING`  STRING NOT NULL,
	`PORTOFORIGIN`  STRING NOT NULL,
	`PORTOFDESTINATION`  STRING NOT NULL,
	`ETD` TIMESTAMP NOT NULL,
	`ETA` TIMESTAMP NOT NULL,
	`MODEOFTRANSPORTID`  STRING NOT NULL,
	`DESCRIPTION`  STRING NOT NULL,
	`REMARK`  STRING NOT NULL,
	`UPDATEDATE` TIMESTAMP NOT NULL,
	`PARTITION`  STRING NOT NULL,
	`DATAAREAID`  STRING NOT NULL,
	`SYNCSTARTDATETIME` TIMESTAMP NOT NULL,
	`RECID` bigint NOT NULL,
 CONSTRAINT `PK_YSLEShipmentDetailsStaging` PRIMARY KEY CLUSTERED 
(
	`EXECUTIONID` ASC,
	`SHIPMENT` ASC,
	`DATAAREAID` ASC,
	`PARTITION` ASC
)WITH(STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
;
