/****** Object:  Table [dbo].[SMRBIInventTestOperationTimeSheetStaging]    Script Date: 03/03/2026 16:26:09 ******/



CREATE OR REPLACE TABLE `dbo`.`SMRBIInventTestOperationTimeSheetStaging`(
	`DEFINITIONGROUP`  STRING NOT NULL,
	`EXECUTIONID`  STRING NOT NULL,
	`ISSELECTED` int NOT NULL,
	`TRANSFERSTATUS` int NOT NULL,
	`COSTAMOUNT`  DECIMAL(32,6) NOT NULL,
	`INVENTNONCONFORMANCEID`  STRING NOT NULL,
	`INVOICEDSALESID`  STRING NOT NULL,
	`LINENUM`  DECIMAL(32,16) NOT NULL,
	`OPERATIONBILLED` int NOT NULL,
	`OPERATIONDATE` TIMESTAMP NOT NULL,
	`OPERATIONHOURS`  DECIMAL(32,6) NOT NULL,
	`WORKER` bigint NOT NULL,
	`COMPANY`  STRING NOT NULL,
	`PARTITION`  STRING NOT NULL,
	`DATAAREAID`  STRING NOT NULL,
	`SYNCSTARTDATETIME` TIMESTAMP NOT NULL,
	`RECID` bigint NOT NULL,
 CONSTRAINT `PK_SMRBIInventTestOperationTimeSheetStaging` PRIMARY KEY CLUSTERED 
(
	`EXECUTIONID` ASC,
	`COSTAMOUNT` ASC,
	`INVENTNONCONFORMANCEID` ASC,
	`INVOICEDSALESID` ASC,
	`LINENUM` ASC,
	`OPERATIONBILLED` ASC,
	`OPERATIONDATE` ASC,
	`OPERATIONHOURS` ASC,
	`WORKER` ASC,
	`DATAAREAID` ASC,
	`PARTITION` ASC
)WITH(STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
;
