/****** Object:  Table [dbo].[SMRBIReqPOStaging]    Script Date: 03/03/2026 16:26:08 ******/



CREATE OR REPLACE TABLE `dbo`.`SMRBIReqPOStaging`(
	`DEFINITIONGROUP`  STRING NOT NULL,
	`EXECUTIONID`  STRING NOT NULL,
	`ISSELECTED` int NOT NULL,
	`TRANSFERSTATUS` int NOT NULL,
	`COVINVENTDIMID`  STRING NOT NULL,
	`COMPANY`  STRING NOT NULL,
	`ITEMBUYERGROUPID`  STRING NOT NULL,
	`ITEMGROUPID`  STRING NOT NULL,
	`ITEMID`  STRING NOT NULL,
	`LEADTIME` int NOT NULL,
	`PLANVERSION` bigint NOT NULL,
	`PURCHID`  STRING NOT NULL,
	`PURCHQTY`  DECIMAL(32,6) NOT NULL,
	`PURCHUNIT`  STRING NOT NULL,
	`QTY`  DECIMAL(32,6) NOT NULL,
	`REFID`  STRING NOT NULL,
	`REFTYPE` int NOT NULL,
	`REQDATE` TIMESTAMP NOT NULL,
	`REQDATEDLV` TIMESTAMP NOT NULL,
	`REQDATEORDER` TIMESTAMP NOT NULL,
	`REQPOSTATUS` int NOT NULL,
	`VENDGROUPID`  STRING NOT NULL,
	`VENDID`  STRING NOT NULL,
	`PARTITION`  STRING NOT NULL,
	`DATAAREAID`  STRING NOT NULL,
	`SYNCSTARTDATETIME` TIMESTAMP NOT NULL,
	`RECID` bigint NOT NULL,
 CONSTRAINT `PK_SMRBIReqPOStaging` PRIMARY KEY CLUSTERED 
(
	`EXECUTIONID` ASC,
	`PLANVERSION` ASC,
	`REFID` ASC,
	`DATAAREAID` ASC,
	`PARTITION` ASC
)WITH(STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
;
