/****** Object:  Table [dbo].[SMRBICaseAssociationStaging]    Script Date: 03/03/2026 16:26:09 ******/



CREATE OR REPLACE TABLE `dbo`.`SMRBICaseAssociationStaging`(
	`DEFINITIONGROUP`  STRING NOT NULL,
	`EXECUTIONID`  STRING NOT NULL,
	`ISSELECTED` int NOT NULL,
	`TRANSFERSTATUS` int NOT NULL,
	`CASERECID` bigint NOT NULL,
	`ENTITYTYPE` int NOT NULL,
	`ISPRIMARY` int NOT NULL,
	`REFRECID` bigint NOT NULL,
	`PARTITION`  STRING NOT NULL,
	`SYNCSTARTDATETIME` TIMESTAMP NOT NULL,
	`RECID` bigint NOT NULL,
 CONSTRAINT `PK_SMRBICaseAssociationStaging` PRIMARY KEY CLUSTERED 
(
	`EXECUTIONID` ASC,
	`CASERECID` ASC,
	`ENTITYTYPE` ASC,
	`REFRECID` ASC,
	`PARTITION` ASC
)WITH(STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
;
