/****** Object:  Table [dbo].[SMRBISalesOrderLineStaging]    Script Date: 03/03/2026 16:26:08 ******/



CREATE OR REPLACE TABLE `dbo`.`SMRBISalesOrderLineStaging`(
	`DEFINITIONGROUP`  STRING NOT NULL,
	`EXECUTIONID`  STRING NOT NULL,
	`ISSELECTED` int NOT NULL,
	`TRANSFERSTATUS` int NOT NULL,
	`SALESORDERNUMBER`  STRING NOT NULL,
	`INVENTORYLOTID`  STRING NOT NULL,
	`SALESORDERLINESTATUS` int NOT NULL,
	`ITEMNUMBER`  STRING NOT NULL,
	`CONFIRMEDRECEIPTDATE` TIMESTAMP NOT NULL,
	`REQUESTEDRECEIPTDATE` TIMESTAMP NOT NULL,
	`SALESPRICE`  DECIMAL(32,6) NOT NULL,
	`ORDEREDSALESQUANTITY`  DECIMAL(32,6) NOT NULL,
	`SALESUNITSYMBOL`  STRING NOT NULL,
	`CONFIRMEDSHIPPINGDATE` TIMESTAMP NOT NULL,
	`REQUESTEDSHIPPINGDATE` TIMESTAMP NOT NULL,
	`INVENTDIMID`  STRING NOT NULL,
	`COMPANY`  STRING NOT NULL,
	`SALESLINERECID` bigint NOT NULL,
	`INVENTREFTRANSID`  STRING NOT NULL,
	`LINEAMOUNT`  DECIMAL(32,6) NOT NULL,
	`LINEDISCOUNTAMOUNT`  DECIMAL(32,6) NOT NULL,
	`LINEDISCOUNTPERCENTAGE`  DECIMAL(32,6) NOT NULL,
	`LINENUM`  DECIMAL(32,16) NOT NULL,
	`REMAINSALESPHYSICAL`  DECIMAL(32,6) NOT NULL,
	`SALESPRICEQUANTITY`  DECIMAL(32,12) NOT NULL,
	`DEFAULTDIMENSION` bigint NOT NULL,
	`DEFAULTDIMENSIONDISPLAYVALUE`  STRING NOT NULL,
	`COSTPRICE`  DECIMAL(32,6) NOT NULL,
	`EXTERNALITEMID`  STRING NOT NULL,
	`ITEMBOMID`  STRING NOT NULL,
	`NAME`  STRING NOT NULL,
	`TAXGROUP`  STRING NOT NULL,
	`TAXITEMGROUP`  STRING NOT NULL,
	`RETAILVARIANTID`  STRING NOT NULL,
	`PARTITION`  STRING NOT NULL,
	`DATAAREAID`  STRING NOT NULL,
	`SYNCSTARTDATETIME` TIMESTAMP NOT NULL,
 CONSTRAINT `PK_SMRBISalesOrderLineStaging` PRIMARY KEY CLUSTERED 
(
	`EXECUTIONID` ASC,
	`SALESLINERECID` ASC,
	`DATAAREAID` ASC,
	`PARTITION` ASC
)WITH(STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
;
