/****** Object:  Table [dbo].[SMRBIInventTestOperationMiscChargesStaging]    Script Date: 03/03/2026 16:26:09 ******/



CREATE OR REPLACE TABLE `dbo`.`SMRBIInventTestOperationMiscChargesStaging`(
	`DEFINITIONGROUP`  STRING NOT NULL,
	`EXECUTIONID`  STRING NOT NULL,
	`ISSELECTED` int NOT NULL,
	`TRANSFERSTATUS` int NOT NULL,
	`INVENTNONCONFORMANCEID`  STRING NOT NULL,
	`LINENUM`  DECIMAL(32,16) NOT NULL,
	`MARKUPCODE`  STRING NOT NULL,
	`TXT`  STRING NOT NULL,
	`VALUE`  DECIMAL(32,6) NOT NULL,
	`COMPANY`  STRING NOT NULL,
	`PARTITION`  STRING NOT NULL,
	`DATAAREAID`  STRING NOT NULL,
	`SYNCSTARTDATETIME` TIMESTAMP NOT NULL,
	`RECID` bigint NOT NULL,
 CONSTRAINT `PK_SMRBIInventTestOperationMiscChargesStaging` PRIMARY KEY CLUSTERED 
(
	`EXECUTIONID` ASC,
	`INVENTNONCONFORMANCEID` ASC,
	`LINENUM` ASC,
	`MARKUPCODE` ASC,
	`TXT` ASC,
	`VALUE` ASC,
	`DATAAREAID` ASC,
	`PARTITION` ASC
)WITH(STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
;
