/****** Object:  Table [dbo].[SMRBIVendTransStaging]    Script Date: 03/03/2026 16:26:08 ******/



CREATE OR REPLACE TABLE `dbo`.`SMRBIVendTransStaging`(
	`DEFINITIONGROUP`  STRING NOT NULL,
	`EXECUTIONID`  STRING NOT NULL,
	`ISSELECTED` int NOT NULL,
	`TRANSFERSTATUS` int NOT NULL,
	`ACCOUNTNUM`  STRING NOT NULL,
	`AMOUNTCUR`  DECIMAL(32,6) NOT NULL,
	`AMOUNTMST`  DECIMAL(32,6) NOT NULL,
	`CLOSED` TIMESTAMP NOT NULL,
	`CURRENCYCODE`  STRING NOT NULL,
	`DOCUMENTDATE` TIMESTAMP NOT NULL,
	`DUEDATE` TIMESTAMP NOT NULL,
	`INVOICE`  STRING NOT NULL,
	`VENDTRANSRECID` bigint NOT NULL,
	`SETTLEAMOUNTCUR`  DECIMAL(32,6) NOT NULL,
	`SETTLEAMOUNTMST`  DECIMAL(32,6) NOT NULL,
	`TRANSDATE` TIMESTAMP NOT NULL,
	`TXT`  STRING NOT NULL,
	`VOUCHER`  STRING NOT NULL,
	`COMPANY`  STRING NOT NULL,
	`APPROVED` int NOT NULL,
	`PARTITION`  STRING NOT NULL,
	`DATAAREAID`  STRING NOT NULL,
	`SYNCSTARTDATETIME` TIMESTAMP NOT NULL,
	`RECID` bigint NOT NULL
)
;
