/****** Object:  Table [dbo].[SMRBICustomerTransStaging]    Script Date: 03/03/2026 16:26:09 ******/



CREATE OR REPLACE TABLE `dbo`.`SMRBICustomerTransStaging`(
	`DEFINITIONGROUP`  STRING NOT NULL,
	`EXECUTIONID`  STRING NOT NULL,
	`ISSELECTED` int NOT NULL,
	`TRANSFERSTATUS` int NOT NULL,
	`ACCOUNTNUM`  STRING NOT NULL,
	`AMOUNTCUR`  DECIMAL(32,6) NOT NULL,
	`AMOUNTMST`  DECIMAL(32,6) NOT NULL,
	`CLOSED` TIMESTAMP NOT NULL,
	`CUSTOMERTRANSCREATEDDATETIME` TIMESTAMP NOT NULL,
	`CURRENCYCODE`  STRING NOT NULL,
	`COMPANY`  STRING NOT NULL,
	`DOCUMENTDATE` TIMESTAMP NOT NULL,
	`DUEDATE` TIMESTAMP NOT NULL,
	`INVOICE`  STRING NOT NULL,
	`CUSTTRANSRECID` bigint NOT NULL,
	`SETTLEAMOUNTCUR`  DECIMAL(32,6) NOT NULL,
	`SETTLEAMOUNTMST`  DECIMAL(32,6) NOT NULL,
	`TRANSDATE` TIMESTAMP NOT NULL,
	`TXT`  STRING NOT NULL,
	`VOUCHER`  STRING NOT NULL,
	`PARTITION`  STRING NOT NULL,
	`DATAAREAID`  STRING NOT NULL,
	`SYNCSTARTDATETIME` TIMESTAMP NOT NULL,
	`RECID` bigint NOT NULL,
 CONSTRAINT `PK_SMRBICustomerTransStaging` PRIMARY KEY CLUSTERED 
(
	`EXECUTIONID` ASC,
	`CUSTTRANSRECID` ASC,
	`DATAAREAID` ASC,
	`PARTITION` ASC
)WITH(STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
;
