/****** Object:  Table [dbo].[SMRBIWrkCtrActivityRequirementStaging]    Script Date: 03/03/2026 16:26:09 ******/



CREATE OR REPLACE TABLE `dbo`.`SMRBIWrkCtrActivityRequirementStaging`(
	`DEFINITIONGROUP`  STRING NOT NULL,
	`EXECUTIONID`  STRING NOT NULL,
	`ISSELECTED` int NOT NULL,
	`TRANSFERSTATUS` int NOT NULL,
	`ACTIVITYREQUIREMENTSET` bigint NOT NULL,
	`WRKCTRACTIVITYREQUIREMENTRECID` bigint NOT NULL,
	`PARTITION`  STRING NOT NULL,
	`SYNCSTARTDATETIME` TIMESTAMP NOT NULL,
	`RECID` bigint NOT NULL,
 CONSTRAINT `PK_SMRBIWrkCtrActivityRequirementStaging` PRIMARY KEY CLUSTERED 
(
	`EXECUTIONID` ASC,
	`WRKCTRACTIVITYREQUIREMENTRECID` ASC,
	`PARTITION` ASC
)WITH(STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
;
