/****** Object:  Table [dbo].[SMRBIInventItemPriceStaging]    Script Date: 03/03/2026 16:26:08 ******/



CREATE OR REPLACE TABLE `dbo`.`SMRBIInventItemPriceStaging`(
	`DEFINITIONGROUP`  STRING NOT NULL,
	`EXECUTIONID`  STRING NOT NULL,
	`ISSELECTED` int NOT NULL,
	`TRANSFERSTATUS` int NOT NULL,
	`ACTIVATIONDATE` TIMESTAMP NOT NULL,
	`COSTINGTYPE` int NOT NULL,
	`ITEMPRICECREATEDDATETIME` TIMESTAMP NOT NULL,
	`COMPANY`  STRING NOT NULL,
	`INVENTDIMID`  STRING NOT NULL,
	`ITEMID`  STRING NOT NULL,
	`MARKUP`  DECIMAL(32,16) NOT NULL,
	`PRICE`  DECIMAL(32,16) NOT NULL,
	`PRICECALCID`  STRING NOT NULL,
	`ITEMPRICEMODIFIEDDATETIME` TIMESTAMP NOT NULL,
	`PRICEQTY`  DECIMAL(32,6) NOT NULL,
	`PRICETYPE` int NOT NULL,
	`PRICEUNIT`  DECIMAL(32,12) NOT NULL,
	`INVENTITEMPRICERECID` bigint NOT NULL,
	`STDCOSTTRANSDATE` TIMESTAMP NOT NULL,
	`STDCOSTVOUCHER`  STRING NOT NULL,
	`UNITID`  STRING NOT NULL,
	`VERSIONID`  STRING NOT NULL,
	`PARTITION`  STRING NOT NULL,
	`DATAAREAID`  STRING NOT NULL,
	`SYNCSTARTDATETIME` TIMESTAMP NOT NULL,
 CONSTRAINT `PK_SMRBIInventItemPriceStaging` PRIMARY KEY CLUSTERED 
(
	`EXECUTIONID` ASC,
	`INVENTITEMPRICERECID` ASC,
	`DATAAREAID` ASC,
	`PARTITION` ASC
)WITH(STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
;
