/****** Object:  Table [dbo].[SMRBIBOMBillOfMaterialsVersionStaging]    Script Date: 03/03/2026 16:26:09 ******/



CREATE OR REPLACE TABLE `dbo`.`SMRBIBOMBillOfMaterialsVersionStaging`(
	`DEFINITIONGROUP`  STRING NOT NULL,
	`EXECUTIONID`  STRING NOT NULL,
	`ISSELECTED` int NOT NULL,
	`TRANSFERSTATUS` int NOT NULL,
	`BOMID`  STRING NOT NULL,
	`COMPANY`  STRING NOT NULL,
	`FROMQUANTITY`  DECIMAL(32,6) NOT NULL,
	`ISACTIVE` int NOT NULL,
	`ISAPPROVED` int NOT NULL,
	`MANUFACTUREDITEMNUMBER`  STRING NOT NULL,
	`VALIDFROMDATE` TIMESTAMP NOT NULL,
	`VALIDTODATE` TIMESTAMP NOT NULL,
	`BOMVERSIONRECID` bigint NOT NULL,
	`CONFIGID`  STRING NOT NULL,
	`PARTITION`  STRING NOT NULL,
	`DATAAREAID`  STRING NOT NULL,
	`SYNCSTARTDATETIME` TIMESTAMP NOT NULL,
	`RECID` bigint NOT NULL,
 CONSTRAINT `PK_SMRBIBOMBillOfMaterialsVersionStaging` PRIMARY KEY CLUSTERED 
(
	`EXECUTIONID` ASC,
	`BOMID` ASC,
	`ISACTIVE` ASC,
	`MANUFACTUREDITEMNUMBER` ASC,
	`VALIDFROMDATE` ASC,
	`VALIDTODATE` ASC,
	`BOMVERSIONRECID` ASC,
	`DATAAREAID` ASC,
	`PARTITION` ASC
)WITH(STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
;
