/****** Object:  Table [dbo].[SMRBIRouteRouteOperationStaging]    Script Date: 03/03/2026 16:26:08 ******/



CREATE OR REPLACE TABLE `dbo`.`SMRBIRouteRouteOperationStaging`(
	`DEFINITIONGROUP`  STRING NOT NULL,
	`EXECUTIONID`  STRING NOT NULL,
	`ISSELECTED` int NOT NULL,
	`TRANSFERSTATUS` int NOT NULL,
	`NEXTROUTEOPERATIONNUMBER` int NOT NULL,
	`OPERATIONID`  STRING NOT NULL,
	`OPERATIONNUMBER` int NOT NULL,
	`OPERATIONPRIORITY` int NOT NULL,
	`ROUTEID`  STRING NOT NULL,
	`COMPANY`  STRING NOT NULL,
	`PARTITION`  STRING NOT NULL,
	`DATAAREAID`  STRING NOT NULL,
	`SYNCSTARTDATETIME` TIMESTAMP NOT NULL,
	`RECID` bigint NOT NULL,
 CONSTRAINT `PK_SMRBIRouteRouteOperationStaging` PRIMARY KEY CLUSTERED 
(
	`EXECUTIONID` ASC,
	`OPERATIONNUMBER` ASC,
	`OPERATIONPRIORITY` ASC,
	`ROUTEID` ASC,
	`DATAAREAID` ASC,
	`PARTITION` ASC
)WITH(STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
;
