/****** Object:  Table [dbo].[SMRBIDimensionFinancialTagStaging]    Script Date: 03/03/2026 16:26:08 ******/



CREATE OR REPLACE TABLE `dbo`.`SMRBIDimensionFinancialTagStaging`(
	`DEFINITIONGROUP`  STRING NOT NULL,
	`EXECUTIONID`  STRING NOT NULL,
	`ISSELECTED` int NOT NULL,
	`TRANSFERSTATUS` int NOT NULL,
	`DESCRIPTION`  STRING NOT NULL,
	`FINANCIALTAGCATEGORY` bigint NOT NULL,
	`VALUE`  STRING NOT NULL,
	`FINANCIALTAGRECID` bigint NOT NULL,
	`PARTITION`  STRING NOT NULL,
	`SYNCSTARTDATETIME` TIMESTAMP NOT NULL,
	`RECID` bigint NOT NULL,
 CONSTRAINT `PK_SMRBIDimensionFinancialTagStaging` PRIMARY KEY CLUSTERED 
(
	`EXECUTIONID` ASC,
	`FINANCIALTAGRECID` ASC,
	`PARTITION` ASC
)WITH(STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
;
