/****** Object:  Table [dbo].[SMRBIProcProcurementProductCategoryStaging]    Script Date: 03/03/2026 16:26:09 ******/



CREATE OR REPLACE TABLE `dbo`.`SMRBIProcProcurementProductCategoryStaging`(
	`DEFINITIONGROUP`  STRING NOT NULL,
	`EXECUTIONID`  STRING NOT NULL,
	`ISSELECTED` int NOT NULL,
	`TRANSFERSTATUS` int NOT NULL,
	`CODE`  STRING NOT NULL,
	`PROCUREMENTCREATEDDATETIME` TIMESTAMP NOT NULL,
	`LEVEL_` bigint NOT NULL,
	`PROCUREMENTMODIFIEDDATETIME` TIMESTAMP NOT NULL,
	`NAME`  STRING NOT NULL,
	`PARENTCATEGORY` bigint NOT NULL,
	`PROCUREMENTRECID` bigint NOT NULL,
	`PARTITION`  STRING NOT NULL,
	`SYNCSTARTDATETIME` TIMESTAMP NOT NULL,
	`RECID` bigint NOT NULL,
 CONSTRAINT `PK_SMRBIProcProcurementProductCategoryStaging` PRIMARY KEY CLUSTERED 
(
	`EXECUTIONID` ASC,
	`PROCUREMENTRECID` ASC,
	`PARTITION` ASC
)WITH(STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
;
