/****** Object:  Table [dbo].[SMRBIInventTransStaging]    Script Date: 03/03/2026 16:26:08 ******/



CREATE OR REPLACE TABLE `dbo`.`SMRBIInventTransStaging`(
	`DEFINITIONGROUP`  STRING NOT NULL,
	`EXECUTIONID`  STRING NOT NULL,
	`ISSELECTED` int NOT NULL,
	`TRANSFERSTATUS` int NOT NULL,
	`COSTAMOUNTADJUSTMENT`  DECIMAL(32,6) NOT NULL,
	`COSTAMOUNTOPERATIONS`  DECIMAL(32,6) NOT NULL,
	`COSTAMOUNTPHYSICAL`  DECIMAL(32,6) NOT NULL,
	`COSTAMOUNTPOSTED`  DECIMAL(32,6) NOT NULL,
	`COSTAMOUNTSETTLED`  DECIMAL(32,16) NOT NULL,
	`COSTAMOUNTSTD`  DECIMAL(32,6) NOT NULL,
	`CURRENCYCODE`  STRING NOT NULL,
	`COMPANY`  STRING NOT NULL,
	`DATECLOSED` TIMESTAMP NOT NULL,
	`DATEEXPECTED` TIMESTAMP NOT NULL,
	`DATEFINANCIAL` TIMESTAMP NOT NULL,
	`DATEINVENT` TIMESTAMP NOT NULL,
	`DATEPHYSICAL` TIMESTAMP NOT NULL,
	`INVENTDIMID`  STRING NOT NULL,
	`INVENTTRANSORIGIN` bigint NOT NULL,
	`INVOICEID`  STRING NOT NULL,
	`ITEMID`  STRING NOT NULL,
	`QTY`  DECIMAL(32,6) NOT NULL,
	`QTYSETTLED`  DECIMAL(32,16) NOT NULL,
	`INVENTTRANSRECID` bigint NOT NULL,
	`SHIPPINGDATECONFIRMED` TIMESTAMP NOT NULL,
	`SHIPPINGDATEREQUESTED` TIMESTAMP NOT NULL,
	`STATUSISSUE` int NOT NULL,
	`STATUSRECEIPT` int NOT NULL,
	`VOUCHER`  STRING NOT NULL,
	`VOUCHERPHYSICAL`  STRING NOT NULL,
	`PARTITION`  STRING NOT NULL,
	`DATAAREAID`  STRING NOT NULL,
	`SYNCSTARTDATETIME` TIMESTAMP NOT NULL,
	`RECID` bigint NOT NULL,
 CONSTRAINT `PK_SMRBIInventTransStaging` PRIMARY KEY CLUSTERED 
(
	`EXECUTIONID` ASC,
	`INVENTTRANSRECID` ASC,
	`DATAAREAID` ASC,
	`PARTITION` ASC
)WITH(STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
;
