/****** Object:  Table [dbo].[SMRBIInventSumStaging]    Script Date: 03/03/2026 16:26:08 ******/



CREATE OR REPLACE TABLE `dbo`.`SMRBIInventSumStaging`(
	`DEFINITIONGROUP`  STRING NOT NULL,
	`EXECUTIONID`  STRING NOT NULL,
	`ISSELECTED` int NOT NULL,
	`TRANSFERSTATUS` int NOT NULL,
	`INVENTDIMID`  STRING NOT NULL,
	`ITEMID`  STRING NOT NULL,
	`PHYSICALINVENT`  DECIMAL(32,6) NOT NULL,
	`PHYSICALVALUE`  DECIMAL(32,6) NOT NULL,
	`COMPANY`  STRING NOT NULL,
	`AVAILPHYSICAL`  DECIMAL(32,6) NOT NULL,
	`RESERVORDERED`  DECIMAL(32,6) NOT NULL,
	`RESERVPHYSICAL`  DECIMAL(32,6) NOT NULL,
	`PARTITION`  STRING NOT NULL,
	`DATAAREAID`  STRING NOT NULL,
	`SYNCSTARTDATETIME` TIMESTAMP NOT NULL,
 CONSTRAINT `PK_SMRBIInventSumStaging` PRIMARY KEY CLUSTERED 
(
	`EXECUTIONID` ASC,
	`INVENTDIMID` ASC,
	`ITEMID` ASC,
	`DATAAREAID` ASC,
	`PARTITION` ASC
)WITH(STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
;
