/****** Object:  Table [dbo].[SMRBIWorkCalendarEmploymentStaging]    Script Date: 03/03/2026 16:26:09 ******/



CREATE OR REPLACE TABLE `dbo`.`SMRBIWorkCalendarEmploymentStaging`(
	`DEFINITIONGROUP`  STRING NOT NULL,
	`EXECUTIONID`  STRING NOT NULL,
	`ISSELECTED` int NOT NULL,
	`TRANSFERSTATUS` int NOT NULL,
	`CALENDARDATAAREAID`  STRING NOT NULL,
	`CALENDARID`  STRING NOT NULL,
	`HCMEMPLOYMENT_FK_VALIDFROM` TIMESTAMP NOT NULL,
	`HCMEMPLOYMENT_FK_VALIDTO` TIMESTAMP NOT NULL,
	`COMPANYINFO_FK_PARTYNUMBER`  STRING NOT NULL,
	`COMPANYINFO_FK_DATAAREA`  STRING NOT NULL,
	`HCMWORKER_FK_PERSONNELNUMBER`  STRING NOT NULL,
	`DIRPERSON_FK_PARTYNUMBER`  STRING NOT NULL,
	`PARTITION`  STRING NOT NULL,
	`SYNCSTARTDATETIME` TIMESTAMP NOT NULL,
	`RECID` bigint NOT NULL,
 CONSTRAINT `PK_SMRBIWorkCalendarEmploymentStaging` PRIMARY KEY CLUSTERED 
(
	`EXECUTIONID` ASC,
	`HCMEMPLOYMENT_FK_VALIDFROM` ASC,
	`HCMEMPLOYMENT_FK_VALIDTO` ASC,
	`COMPANYINFO_FK_DATAAREA` ASC,
	`HCMWORKER_FK_PERSONNELNUMBER` ASC,
	`DIRPERSON_FK_PARTYNUMBER` ASC,
	`PARTITION` ASC
)WITH(STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
;
