/****** Object:  Table [dbo].[SMRBIDefaultDimensionViewStaging]    Script Date: 03/03/2026 16:26:09 ******/



CREATE OR REPLACE TABLE `dbo`.`SMRBIDefaultDimensionViewStaging`(
	`DEFINITIONGROUP`  STRING NOT NULL,
	`EXECUTIONID`  STRING NOT NULL,
	`ISSELECTED` int NOT NULL,
	`TRANSFERSTATUS` int NOT NULL,
	`DISPLAYVALUE`  STRING NOT NULL,
	`DEFAULTDIMENSION` bigint NOT NULL,
	`NAME`  STRING NOT NULL,
	`PARTITION`  STRING NOT NULL,
	`YSLEGROUPDIMENSION`  STRING NOT NULL,
	`SYNCSTARTDATETIME` TIMESTAMP NOT NULL,
	`RECID` bigint NOT NULL,
 CONSTRAINT `PK_SMRBIDefaultDimensionViewStaging` PRIMARY KEY CLUSTERED 
(
	`EXECUTIONID` ASC,
	`DISPLAYVALUE` ASC,
	`DEFAULTDIMENSION` ASC,
	`NAME` ASC,
	`PARTITION` ASC
)WITH(STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
;
