/****** Object:  Table [dbo].[SMRBIDimensionAttributeStaging]    Script Date: 03/03/2026 16:26:08 ******/



CREATE OR REPLACE TABLE `dbo`.`SMRBIDimensionAttributeStaging`(
	`DEFINITIONGROUP`  STRING NOT NULL,
	`EXECUTIONID`  STRING NOT NULL,
	`ISSELECTED` int NOT NULL,
	`TRANSFERSTATUS` int NOT NULL,
	`DIMENSIONNAME`  STRING NOT NULL,
	`VIEWNAME`  STRING NOT NULL,
	`DIMENSIONATTRIBUTERECID` bigint NOT NULL,
	`BACKINGENTITYTABLENAME`  STRING NOT NULL,
	`BACKINGENTITYVALUEFIELDNAME`  STRING NOT NULL,
	`PARTITION`  STRING NOT NULL,
	`SYNCSTARTDATETIME` TIMESTAMP NOT NULL,
	`RECID` bigint NOT NULL,
 CONSTRAINT `PK_SMRBIDimensionAttributeStaging` PRIMARY KEY CLUSTERED 
(
	`EXECUTIONID` ASC,
	`DIMENSIONNAME` ASC,
	`PARTITION` ASC
)WITH(STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
;
