/****** Object:  Table [dbo].[SMRBIWrkCtrRouteOprActivityStaging]    Script Date: 03/03/2026 16:26:09 ******/



CREATE OR REPLACE TABLE `dbo`.`SMRBIWrkCtrRouteOprActivityStaging`(
	`DEFINITIONGROUP`  STRING NOT NULL,
	`EXECUTIONID`  STRING NOT NULL,
	`ISSELECTED` int NOT NULL,
	`TRANSFERSTATUS` int NOT NULL,
	`ACTIVITY` bigint NOT NULL,
	`ROUTEOPR` bigint NOT NULL,
	`ROUTEOPRDATAAREAID`  STRING NOT NULL,
	`PARTITION`  STRING NOT NULL,
	`SYNCSTARTDATETIME` TIMESTAMP NOT NULL,
	`RECID` bigint NOT NULL,
 CONSTRAINT `PK_SMRBIWrkCtrRouteOprActivityStaging` PRIMARY KEY CLUSTERED 
(
	`EXECUTIONID` ASC,
	`ACTIVITY` ASC,
	`ROUTEOPR` ASC,
	`ROUTEOPRDATAAREAID` ASC,
	`PARTITION` ASC
)WITH(STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
;
