/****** Object:  Table [dbo].[SMRBIWorkTimeTableStaging]    Script Date: 03/03/2026 16:26:09 ******/



CREATE OR REPLACE TABLE `dbo`.`SMRBIWorkTimeTableStaging`(
	`DEFINITIONGROUP`  STRING NOT NULL,
	`EXECUTIONID`  STRING NOT NULL,
	`ISSELECTED` int NOT NULL,
	`TRANSFERSTATUS` int NOT NULL,
	`CLOSEDFORPICKUPFRIDAY` int NOT NULL,
	`CLOSEDFORPICKUPMONDAY` int NOT NULL,
	`CLOSEDFORPICKUPSATURDAY` int NOT NULL,
	`CLOSEDFORPICKUPSUNDAY` int NOT NULL,
	`CLOSEDFORPICKUPTHURSDAY` int NOT NULL,
	`CLOSEDFORPICKUPTUESDAY` int NOT NULL,
	`CLOSEDFORPICKUPWEDNESDAY` int NOT NULL,
	`NAME`  STRING NOT NULL,
	`WORKTIMEID`  STRING NOT NULL,
	`PARTITION`  STRING NOT NULL,
	`DATAAREAID`  STRING NOT NULL,
	`SYNCSTARTDATETIME` TIMESTAMP NOT NULL,
 CONSTRAINT `PK_SMRBIWorkTimeTableStaging` PRIMARY KEY CLUSTERED 
(
	`EXECUTIONID` ASC,
	`WORKTIMEID` ASC,
	`DATAAREAID` ASC,
	`PARTITION` ASC
)WITH(STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
;
