/****** Object:  Table [dbo].[SMRBIInventNonConformanceRelationStaging]    Script Date: 03/03/2026 16:26:09 ******/



CREATE OR REPLACE TABLE `dbo`.`SMRBIInventNonConformanceRelationStaging`(
	`DEFINITIONGROUP`  STRING NOT NULL,
	`EXECUTIONID`  STRING NOT NULL,
	`ISSELECTED` int NOT NULL,
	`TRANSFERSTATUS` int NOT NULL,
	`INVENTNONCONFORMANCEID`  STRING NOT NULL,
	`INVENTNONCONFORMANCEIDREF`  STRING NOT NULL,
	`PARTITION`  STRING NOT NULL,
	`SYNCSTARTDATETIME` TIMESTAMP NOT NULL,
 CONSTRAINT `PK_SMRBIInventNonConformanceRelationStaging` PRIMARY KEY CLUSTERED 
(
	`EXECUTIONID` ASC,
	`INVENTNONCONFORMANCEID` ASC,
	`INVENTNONCONFORMANCEIDREF` ASC,
	`PARTITION` ASC
)WITH(STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
;
