/****** Object:  Table [dbo].[SMRBIPurchRFQCaseTableStaging]    Script Date: 03/03/2026 16:26:08 ******/



CREATE OR REPLACE TABLE `dbo`.`SMRBIPurchRFQCaseTableStaging`(
	`DEFINITIONGROUP`  STRING NOT NULL,
	`EXECUTIONID`  STRING NOT NULL,
	`ISSELECTED` int NOT NULL,
	`TRANSFERSTATUS` int NOT NULL,
	`COMPANY`  STRING NOT NULL,
	`NAME`  STRING NOT NULL,
	`RFQCASEID`  STRING NOT NULL,
	`PARTITION`  STRING NOT NULL,
	`DATAAREAID`  STRING NOT NULL,
	`SYNCSTARTDATETIME` TIMESTAMP NOT NULL,
 CONSTRAINT `PK_SMRBIPurchRFQCaseTableStaging` PRIMARY KEY CLUSTERED 
(
	`EXECUTIONID` ASC,
	`COMPANY` ASC,
	`NAME` ASC,
	`RFQCASEID` ASC,
	`DATAAREAID` ASC,
	`PARTITION` ASC
)WITH(STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
;
