/****** Object:  Table [dbo].[SMRBIWorkCalendarDateStaging]    Script Date: 03/03/2026 16:26:09 ******/



CREATE OR REPLACE TABLE `dbo`.`SMRBIWorkCalendarDateStaging`(
	`DEFINITIONGROUP`  STRING NOT NULL,
	`EXECUTIONID`  STRING NOT NULL,
	`ISSELECTED` int NOT NULL,
	`TRANSFERSTATUS` int NOT NULL,
	`CALENDARID`  STRING NOT NULL,
	`CLOSEDFORPICKUP` int NOT NULL,
	`NAME`  STRING NOT NULL,
	`TRANSDATE` TIMESTAMP NOT NULL,
	`WORKTIMECONTROL` int NOT NULL,
	`PARTITION`  STRING NOT NULL,
	`DATAAREAID`  STRING NOT NULL,
	`SYNCSTARTDATETIME` TIMESTAMP NOT NULL,
	`RECID` bigint NOT NULL,
 CONSTRAINT `PK_SMRBIWorkCalendarDateStaging` PRIMARY KEY CLUSTERED 
(
	`EXECUTIONID` ASC,
	`CALENDARID` ASC,
	`TRANSDATE` ASC,
	`DATAAREAID` ASC,
	`PARTITION` ASC
)WITH(STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
;
