/****** Object:  Table [dbo].[SMRBIGeneralJournalAccountEntryStaging]    Script Date: 03/03/2026 16:26:08 ******/



CREATE OR REPLACE TABLE `dbo`.`SMRBIGeneralJournalAccountEntryStaging`(
	`DEFINITIONGROUP`  STRING NOT NULL,
	`EXECUTIONID`  STRING NOT NULL,
	`ISSELECTED` int NOT NULL,
	`TRANSFERSTATUS` int NOT NULL,
	`ACCOUNTINGDATE` TIMESTAMP NOT NULL,
	`ACCOUNTINGCURRENCYAMOUNT`  DECIMAL(32,6) NOT NULL,
	`DESCRIPTION`  STRING NOT NULL,
	`DOCUMENTDATE` TIMESTAMP NOT NULL,
	`DOCUMENTNUMBER`  STRING NOT NULL,
	`GENERALJOURNALACCOUNTENTRYRECID` bigint NOT NULL,
	`LEDGERNAME`  STRING NOT NULL,
	`REPORTINGCURRENCYAMOUNT`  DECIMAL(32,6) NOT NULL,
	`TRANSACTIONCURRENCYAMOUNT`  DECIMAL(32,6) NOT NULL,
	`TRANSACTIONCURRENCYCODE`  STRING NOT NULL,
	`LEDGERDIMENSIONDISPLAYVALUE`  STRING NOT NULL,
	`JOURNALNUMBER`  STRING NOT NULL,
	`VOUCHER`  STRING NOT NULL,
	`JOURNALCATEGORY` int NOT NULL,
	`ISCREDIT` int NOT NULL,
	`GENERALJOURNALACCOUNTENTRYDIMENSION` bigint NOT NULL,
	`PARTITION`  STRING NOT NULL,
	`YSLEVENDORVALUE`  STRING NOT NULL,
	`YSLESHIPMENTCONTRACTVALUE`  STRING NOT NULL,
	`YSLEINTERCOMPANYVALUE`  STRING NOT NULL,
	`YSLELOCATIONVALUE`  STRING NOT NULL,
	`YSLEENDCUSTOMERVALUE`  STRING NOT NULL,
	`YSLEPRODUCTVALUE`  STRING NOT NULL,
	`YSLEDEPARTMENTVALUE`  STRING NOT NULL,
	`YSLELOCALACCOUNTVALUE`  STRING NOT NULL,
	`YSLETEXT`  STRING NOT NULL,
	`YSLEMAINACCOUNT`  STRING NOT NULL,
	`DATAAREAID`  STRING NOT NULL,
	`SYNCSTARTDATETIME` TIMESTAMP NOT NULL,
	`RECID` bigint NOT NULL,
 CONSTRAINT `PK_SMRBIGeneralJournalAccountEntryStaging` PRIMARY KEY CLUSTERED 
(
	`EXECUTIONID` ASC,
	`GENERALJOURNALACCOUNTENTRYRECID` ASC,
	`DATAAREAID` ASC,
	`PARTITION` ASC
)WITH(STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
;
