/****** Object:  Table [dbo].[SMRBIWMSWarehouseLocationStaging]    Script Date: 03/03/2026 16:26:09 ******/



CREATE OR REPLACE TABLE `dbo`.`SMRBIWMSWarehouseLocationStaging`(
	`DEFINITIONGROUP`  STRING NOT NULL,
	`EXECUTIONID`  STRING NOT NULL,
	`ISSELECTED` int NOT NULL,
	`TRANSFERSTATUS` int NOT NULL,
	`WAREHOUSEID`  STRING NOT NULL,
	`WAREHOUSELOCATIONID`  STRING NOT NULL,
	`WAREHOUSELOCATIONPROFILEID`  STRING NOT NULL,
	`COMPANY`  STRING NOT NULL,
	`WAREHOUSELOCATIONRECID` bigint NOT NULL,
	`MAXVOLUME`  DECIMAL(32,6) NOT NULL,
	`PARTITION`  STRING NOT NULL,
	`DATAAREAID`  STRING NOT NULL,
	`SYNCSTARTDATETIME` TIMESTAMP NOT NULL,
 CONSTRAINT `PK_SMRBIWMSWarehouseLocationStaging` PRIMARY KEY CLUSTERED 
(
	`EXECUTIONID` ASC,
	`WAREHOUSEID` ASC,
	`WAREHOUSELOCATIONID` ASC,
	`DATAAREAID` ASC,
	`PARTITION` ASC
)WITH(STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
;
