/****** Object:  Table [dbo].[SMRBIPurchRFQLineStaging]    Script Date: 03/03/2026 16:26:08 ******/



CREATE OR REPLACE TABLE `dbo`.`SMRBIPurchRFQLineStaging`(
	`DEFINITIONGROUP`  STRING NOT NULL,
	`EXECUTIONID`  STRING NOT NULL,
	`ISSELECTED` int NOT NULL,
	`TRANSFERSTATUS` int NOT NULL,
	`CURRENCYCODE`  STRING NOT NULL,
	`COMPANY`  STRING NOT NULL,
	`DELIVERYDATE` TIMESTAMP NOT NULL,
	`EXPIRYDATETIME` TIMESTAMP NOT NULL,
	`INVENTDIMID`  STRING NOT NULL,
	`ITEMID`  STRING NOT NULL,
	`LINENUM`  DECIMAL(32,16) NOT NULL,
	`RFQCASELINELINENUMBER` bigint NOT NULL,
	`RFQID`  STRING NOT NULL,
	`STATUS` int NOT NULL,
	`ITEMNAME`  STRING NOT NULL,
	`PURCHUNIT`  STRING NOT NULL,
	`PARTITION`  STRING NOT NULL,
	`DATAAREAID`  STRING NOT NULL,
	`SYNCSTARTDATETIME` TIMESTAMP NOT NULL,
 CONSTRAINT `PK_SMRBIPurchRFQLineStaging` PRIMARY KEY CLUSTERED 
(
	`EXECUTIONID` ASC,
	`CURRENCYCODE` ASC,
	`COMPANY` ASC,
	`DELIVERYDATE` ASC,
	`EXPIRYDATETIME` ASC,
	`INVENTDIMID` ASC,
	`ITEMID` ASC,
	`LINENUM` ASC,
	`RFQCASELINELINENUMBER` ASC,
	`RFQID` ASC,
	`STATUS` ASC,
	`DATAAREAID` ASC,
	`PARTITION` ASC
)WITH(STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
;
