/****** Object:  Table [dbo].[SMRBIPurchRFQCaseLineStaging]    Script Date: 03/03/2026 16:26:08 ******/



CREATE OR REPLACE TABLE `dbo`.`SMRBIPurchRFQCaseLineStaging`(
	`DEFINITIONGROUP`  STRING NOT NULL,
	`EXECUTIONID`  STRING NOT NULL,
	`ISSELECTED` int NOT NULL,
	`TRANSFERSTATUS` int NOT NULL,
	`COMPANY`  STRING NOT NULL,
	`ITEMID`  STRING NOT NULL,
	`LINENUMBER` bigint NOT NULL,
	`RFQCASEID`  STRING NOT NULL,
	`STATUSHIGH` int NOT NULL,
	`STATUSLOW` int NOT NULL,
	`PARTITION`  STRING NOT NULL,
	`DATAAREAID`  STRING NOT NULL,
	`SYNCSTARTDATETIME` TIMESTAMP NOT NULL,
 CONSTRAINT `PK_SMRBIPurchRFQCaseLineStaging` PRIMARY KEY CLUSTERED 
(
	`EXECUTIONID` ASC,
	`COMPANY` ASC,
	`ITEMID` ASC,
	`LINENUMBER` ASC,
	`RFQCASEID` ASC,
	`STATUSHIGH` ASC,
	`STATUSLOW` ASC,
	`DATAAREAID` ASC,
	`PARTITION` ASC
)WITH(STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
;
