/****** Object:  Table [dbo].[SMRBICustPackingSlipJourStaging]    Script Date: 03/03/2026 16:26:08 ******/



CREATE OR REPLACE TABLE `dbo`.`SMRBICustPackingSlipJourStaging`(
	`DEFINITIONGROUP`  STRING NOT NULL,
	`EXECUTIONID`  STRING NOT NULL,
	`ISSELECTED` int NOT NULL,
	`TRANSFERSTATUS` int NOT NULL,
	`COMPANY`  STRING NOT NULL,
	`DELIVERYDATE` TIMESTAMP NOT NULL,
	`DELIVERYNAME`  STRING NOT NULL,
	`DLVMODE`  STRING NOT NULL,
	`DLVTERM`  STRING NOT NULL,
	`ORDERACCOUNT`  STRING NOT NULL,
	`PACKINGSLIPID`  STRING NOT NULL,
	`QTY`  DECIMAL(32,6) NOT NULL,
	`SALESID`  STRING NOT NULL,
	`SALESTYPE` int NOT NULL,
	`ADDRESS`  STRING NOT NULL,
	`PARTITION`  STRING NOT NULL,
	`DATAAREAID`  STRING NOT NULL,
	`SYNCSTARTDATETIME` TIMESTAMP NOT NULL,
	`RECID` bigint NOT NULL,
 CONSTRAINT `PK_SMRBICustPackingSlipJourStaging` PRIMARY KEY CLUSTERED 
(
	`EXECUTIONID` ASC,
	`COMPANY` ASC,
	`DELIVERYDATE` ASC,
	`DELIVERYNAME` ASC,
	`DLVMODE` ASC,
	`DLVTERM` ASC,
	`ORDERACCOUNT` ASC,
	`PACKINGSLIPID` ASC,
	`QTY` ASC,
	`SALESID` ASC,
	`SALESTYPE` ASC,
	`DATAAREAID` ASC,
	`PARTITION` ASC
)WITH(STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
;
