/****** Object:  Table [dbo].[SMRBICostControlTransCommittedCostStaging]    Script Date: 03/03/2026 16:26:09 ******/



CREATE OR REPLACE TABLE `dbo`.`SMRBICostControlTransCommittedCostStaging`(
	`DEFINITIONGROUP`  STRING NOT NULL,
	`EXECUTIONID`  STRING NOT NULL,
	`ISSELECTED` int NOT NULL,
	`TRANSFERSTATUS` int NOT NULL,
	`ACTIVITYNUMBER`  STRING NOT NULL,
	`AMOUNT`  DECIMAL(32,6) NOT NULL,
	`CATEGORYID`  STRING NOT NULL,
	`COMMITTEDCOSTORIG` int NOT NULL,
	`COMMITTEDDATE` TIMESTAMP NOT NULL,
	`CURRENCYCODE`  STRING NOT NULL,
	`COMPANY`  STRING NOT NULL,
	`EMPLITEMID`  STRING NOT NULL,
	`OPEN_` int NOT NULL,
	`PROJID`  STRING NOT NULL,
	`PROJTRANSID`  STRING NOT NULL,
	`QTY`  DECIMAL(32,6) NOT NULL,
	`VOUCHER`  STRING NOT NULL,
	`PARTITION`  STRING NOT NULL,
	`DATAAREAID`  STRING NOT NULL,
	`SYNCSTARTDATETIME` TIMESTAMP NOT NULL,
	`RECID` bigint NOT NULL,
 CONSTRAINT `PK_SMRBICostControlTransCommittedCostStaging` PRIMARY KEY CLUSTERED 
(
	`EXECUTIONID` ASC,
	`PROJTRANSID` ASC,
	`DATAAREAID` ASC,
	`PARTITION` ASC
)WITH(STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
;
