/****** Object:  Table [dbo].[SMRBIProjInvoiceEmplStaging]    Script Date: 03/03/2026 16:26:09 ******/



CREATE OR REPLACE TABLE `dbo`.`SMRBIProjInvoiceEmplStaging`(
	`DEFINITIONGROUP`  STRING NOT NULL,
	`EXECUTIONID`  STRING NOT NULL,
	`ISSELECTED` int NOT NULL,
	`TRANSFERSTATUS` int NOT NULL,
	`ACTIVITYNUMBER`  STRING NOT NULL,
	`CATEGORYID`  STRING NOT NULL,
	`CURRENCYID`  STRING NOT NULL,
	`COMPANY`  STRING NOT NULL,
	`INVOICEDATE` TIMESTAMP NOT NULL,
	`LINEAMOUNT`  DECIMAL(32,6) NOT NULL,
	`PROJID`  STRING NOT NULL,
	`PROJINVOICEID`  STRING NOT NULL,
	`QTY`  DECIMAL(32,6) NOT NULL,
	`TAXAMOUNT`  DECIMAL(32,6) NOT NULL,
	`TRANSDATE` TIMESTAMP NOT NULL,
	`TRANSID`  STRING NOT NULL,
	`TXT`  STRING NOT NULL,
	`WORKER` bigint NOT NULL,
	`PARTITION`  STRING NOT NULL,
	`DATAAREAID`  STRING NOT NULL,
	`SYNCSTARTDATETIME` TIMESTAMP NOT NULL,
	`RECID` bigint NOT NULL,
 CONSTRAINT `PK_SMRBIProjInvoiceEmplStaging` PRIMARY KEY CLUSTERED 
(
	`EXECUTIONID` ASC,
	`TRANSID` ASC,
	`DATAAREAID` ASC,
	`PARTITION` ASC
)WITH(STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
;
