/****** Object:  Table [dbo].[SMRBICaseDetailBaseStaging]    Script Date: 03/03/2026 16:26:08 ******/



CREATE OR REPLACE TABLE `dbo`.`SMRBICaseDetailBaseStaging`(
	`DEFINITIONGROUP`  STRING NOT NULL,
	`EXECUTIONID`  STRING NOT NULL,
	`ISSELECTED` int NOT NULL,
	`TRANSFERSTATUS` int NOT NULL,
	`CASEID`  STRING NOT NULL,
	`CATEGORYRECID` bigint NOT NULL,
	`CLOSEDBY`  STRING NOT NULL,
	`CLOSEDDATETIME` TIMESTAMP NOT NULL,
	`CONTACTPERSONID`  STRING NOT NULL,
	`DEPARTMENT` bigint NOT NULL,
	`DESCRIPTION`  STRING NOT NULL,
	`EMAILID`  STRING NOT NULL,
	`INSTANCERELATIONTYPE` bigint NOT NULL,
	`MEMO`  STRING,
	`OWNERWORKER` bigint NOT NULL,
	`PRIORITY`  STRING NOT NULL,
	`PROCESS`  STRING NOT NULL,
	`STATUS` int NOT NULL,
	`CASECATEGORYHIERARCHYDETAIL_CASECATEGORY`  STRING NOT NULL,
	`CASECATEGORYHIERARCHYDETAIL_CATEGORYTYPE` int NOT NULL,
	`OMOPERATINGUNIT_PARTYNUMBER`  STRING NOT NULL,
	`OMOPERATINGUNIT_OMOPERATINGUNITTYPE` int NOT NULL,
	`ONWERWORKER_PERSONNELNUMBER`  STRING NOT NULL,
	`PARTY_FK_PARTYNUMBER`  STRING NOT NULL,
	`CASEDETAILMODIFIEDBY`  STRING NOT NULL,
	`CASEDETAILMODIFIEDDATETIME` TIMESTAMP NOT NULL,
	`CASEDETAILMODIFIEDTRANSACTIONID` bigint NOT NULL,
	`CASEDETAILRECVERSION` int NOT NULL,
	`PLANNEDEFFECTIVEDATE` TIMESTAMP NOT NULL,
	`COMPANY`  STRING NOT NULL,
	`CASEDETAILCREATEDBY`  STRING NOT NULL,
	`CASEDETAILCREATEDDATETIME` TIMESTAMP NOT NULL,
	`CASEDETAILBASERECID` bigint NOT NULL,
	`PARTITION`  STRING NOT NULL,
	`DATAAREAID`  STRING NOT NULL,
	`SYNCSTARTDATETIME` TIMESTAMP NOT NULL,
	`RECID` bigint NOT NULL,
 CONSTRAINT `PK_SMRBICaseDetailBaseStaging` PRIMARY KEY CLUSTERED 
(
	`EXECUTIONID` ASC,
	`CASEID` ASC,
	`DATAAREAID` ASC,
	`PARTITION` ASC
)WITH(STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
) TEXTIMAGE_ON `PRIMARY`
;
