/****** Object:  Table [dbo].[SMRBIVendRFQTransStaging]    Script Date: 03/03/2026 16:26:08 ******/



CREATE OR REPLACE TABLE `dbo`.`SMRBIVendRFQTransStaging`(
	`DEFINITIONGROUP`  STRING NOT NULL,
	`EXECUTIONID`  STRING NOT NULL,
	`ISSELECTED` int NOT NULL,
	`TRANSFERSTATUS` int NOT NULL,
	`INTERNALRFQID`  STRING NOT NULL,
	`ITEMID`  STRING NOT NULL,
	`LINEAMOUNT`  DECIMAL(32,6) NOT NULL,
	`PURCHPRICE`  DECIMAL(32,6) NOT NULL,
	`PURCHQTY`  DECIMAL(32,6) NOT NULL,
	`RFQDATE` TIMESTAMP NOT NULL,
	`RFQID`  STRING NOT NULL,
	`STATUS` int NOT NULL,
	`COMPANY`  STRING NOT NULL,
	`PARTITION`  STRING NOT NULL,
	`DATAAREAID`  STRING NOT NULL,
	`SYNCSTARTDATETIME` TIMESTAMP NOT NULL,
	`RECID` bigint NOT NULL,
 CONSTRAINT `PK_SMRBIVendRFQTransStaging` PRIMARY KEY CLUSTERED 
(
	`EXECUTIONID` ASC,
	`INTERNALRFQID` ASC,
	`ITEMID` ASC,
	`LINEAMOUNT` ASC,
	`PURCHPRICE` ASC,
	`PURCHQTY` ASC,
	`RFQDATE` ASC,
	`RFQID` ASC,
	`STATUS` ASC,
	`COMPANY` ASC,
	`DATAAREAID` ASC,
	`PARTITION` ASC
)WITH(STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
;
