/****** Object:  Table [dbo].[SMRBIRouteCostCategoryStaging]    Script Date: 03/03/2026 16:26:09 ******/



CREATE OR REPLACE TABLE `dbo`.`SMRBIRouteCostCategoryStaging`(
	`DEFINITIONGROUP`  STRING NOT NULL,
	`EXECUTIONID`  STRING NOT NULL,
	`ISSELECTED` int NOT NULL,
	`TRANSFERSTATUS` int NOT NULL,
	`CATEGORYID`  STRING NOT NULL,
	`COSTGROUPID`  STRING NOT NULL,
	`UNITCOST`  DECIMAL(32,6) NOT NULL,
	`ABSORBEDMANUFACTURINGCOSTMAINACCOUNTIDDISPLAYVALUE`  STRING NOT NULL,
	`ABSORBEDWIPMANUFACTURINGCOSTMAINACCOUNTIDDISPLAYVALUE`  STRING NOT NULL,
	`ESTIMATEDABSORBEDMANUFACTURINGCOSTMAINACCOUNTIDDISPLAYVALUE`  STRING NOT NULL,
	`ESTIMATEDABSORBEDWIPMANUFACTURINGCOSTMAINACCOUNTIDDISPLAYVALUE`  STRING NOT NULL,
	`COMPANY`  STRING NOT NULL,
	`PARTITION`  STRING NOT NULL,
	`DATAAREAID`  STRING NOT NULL,
	`SYNCSTARTDATETIME` TIMESTAMP NOT NULL,
 CONSTRAINT `PK_SMRBIRouteCostCategoryStaging` PRIMARY KEY CLUSTERED 
(
	`EXECUTIONID` ASC,
	`CATEGORYID` ASC,
	`DATAAREAID` ASC,
	`PARTITION` ASC
)WITH(STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
;
