/****** Object:  Table [dbo].[SMRBIMainAccountCategoryStaging]    Script Date: 03/03/2026 16:26:09 ******/



CREATE OR REPLACE TABLE `dbo`.`SMRBIMainAccountCategoryStaging`(
	`DEFINITIONGROUP`  STRING NOT NULL,
	`EXECUTIONID`  STRING NOT NULL,
	`ISSELECTED` int NOT NULL,
	`TRANSFERSTATUS` int NOT NULL,
	`MAINACCOUNTCATEGORY`  STRING NOT NULL,
	`REFERENCEID` int NOT NULL,
	`MAINACCOUNTTYPE` int NOT NULL,
	`DESCRIPTION`  STRING NOT NULL,
	`PARTITION`  STRING NOT NULL,
	`SYNCSTARTDATETIME` TIMESTAMP NOT NULL,
	`RECID` bigint NOT NULL,
 CONSTRAINT `PK_SMRBIMainAccountCategoryStaging` PRIMARY KEY CLUSTERED 
(
	`EXECUTIONID` ASC,
	`REFERENCEID` ASC,
	`PARTITION` ASC
)WITH(STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
;
