/****** Object:  Table [dbo].[SMRBIDirPartyBaseStaging]    Script Date: 03/03/2026 16:26:09 ******/



CREATE OR REPLACE TABLE `dbo`.`SMRBIDirPartyBaseStaging`(
	`DEFINITIONGROUP`  STRING NOT NULL,
	`EXECUTIONID`  STRING NOT NULL,
	`ISSELECTED` int NOT NULL,
	`TRANSFERSTATUS` int NOT NULL,
	`PARTYNUMBER`  STRING NOT NULL,
	`NAME`  STRING NOT NULL,
	`INSTANCERELATIONTYPE` bigint NOT NULL,
	`PARTITION`  STRING NOT NULL,
	`SYNCSTARTDATETIME` TIMESTAMP NOT NULL,
	`RECID` bigint NOT NULL,
 CONSTRAINT `PK_SMRBIDirPartyBaseStaging` PRIMARY KEY CLUSTERED 
(
	`EXECUTIONID` ASC,
	`PARTYNUMBER` ASC,
	`PARTITION` ASC
)WITH(STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
;
