/****** Object:  Table [dbo].[SMRBIDimensionAttributeDirCategoryStaging]    Script Date: 03/03/2026 16:26:08 ******/



CREATE OR REPLACE TABLE `dbo`.`SMRBIDimensionAttributeDirCategoryStaging`(
	`DEFINITIONGROUP`  STRING NOT NULL,
	`EXECUTIONID`  STRING NOT NULL,
	`ISSELECTED` int NOT NULL,
	`TRANSFERSTATUS` int NOT NULL,
	`DIMENSIONATTRIBUTE` bigint NOT NULL,
	`DIRCATEGORY` bigint NOT NULL,
	`DIMENSIONATTRIBUTE_NAME`  STRING NOT NULL,
	`PARTITION`  STRING NOT NULL,
	`SYNCSTARTDATETIME` TIMESTAMP NOT NULL,
	`RECID` bigint NOT NULL,
 CONSTRAINT `PK_SMRBIDimensionAttributeDirCategoryStaging` PRIMARY KEY CLUSTERED 
(
	`EXECUTIONID` ASC,
	`DIMENSIONATTRIBUTE_NAME` ASC,
	`PARTITION` ASC
)WITH(STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
;
