/****** Object:  Table [dbo].[SMRBIVendPackingSlipTransStaging]    Script Date: 03/03/2026 16:26:08 ******/



CREATE OR REPLACE TABLE `dbo`.`SMRBIVendPackingSlipTransStaging`(
	`DEFINITIONGROUP`  STRING NOT NULL,
	`EXECUTIONID`  STRING NOT NULL,
	`ISSELECTED` int NOT NULL,
	`TRANSFERSTATUS` int NOT NULL,
	`DELIVERYDATE` TIMESTAMP NOT NULL,
	`INVENTDIMID`  STRING NOT NULL,
	`ITEMID`  STRING NOT NULL,
	`LINENUM`  DECIMAL(32,16) NOT NULL,
	`ORDERED`  DECIMAL(32,6) NOT NULL,
	`ORIGPURCHID`  STRING NOT NULL,
	`PACKINGSLIPID`  STRING NOT NULL,
	`PRICEUNIT`  DECIMAL(32,12) NOT NULL,
	`PURCHASELINEEXPECTEDDELIVERYDATE` TIMESTAMP NOT NULL,
	`PURCHASELINELINENUMBER` bigint NOT NULL,
	`PURCHUNIT`  STRING NOT NULL,
	`QTY`  DECIMAL(32,6) NOT NULL,
	`VENDPACKINGSLIPJOUR` bigint NOT NULL,
	`COMPANY`  STRING NOT NULL,
	`PARTITION`  STRING NOT NULL,
	`DATAAREAID`  STRING NOT NULL,
	`SYNCSTARTDATETIME` TIMESTAMP NOT NULL,
	`RECID` bigint NOT NULL,
 CONSTRAINT `PK_SMRBIVendPackingSlipTransStaging` PRIMARY KEY CLUSTERED 
(
	`EXECUTIONID` ASC,
	`DELIVERYDATE` ASC,
	`INVENTDIMID` ASC,
	`ITEMID` ASC,
	`LINENUM` ASC,
	`ORDERED` ASC,
	`ORIGPURCHID` ASC,
	`PACKINGSLIPID` ASC,
	`PRICEUNIT` ASC,
	`PURCHASELINEEXPECTEDDELIVERYDATE` ASC,
	`PURCHASELINELINENUMBER` ASC,
	`PURCHUNIT` ASC,
	`QTY` ASC,
	`VENDPACKINGSLIPJOUR` ASC,
	`COMPANY` ASC,
	`DATAAREAID` ASC,
	`PARTITION` ASC
)WITH(STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
;
