/****** Object:  Table [dbo].[SMRBIWorkCalendarStaging]    Script Date: 03/03/2026 16:26:08 ******/



CREATE OR REPLACE TABLE `dbo`.`SMRBIWorkCalendarStaging`(
	`DEFINITIONGROUP`  STRING NOT NULL,
	`EXECUTIONID`  STRING NOT NULL,
	`ISSELECTED` int NOT NULL,
	`TRANSFERSTATUS` int NOT NULL,
	`CALENDARID`  STRING NOT NULL,
	`CALENDARNAME`  STRING NOT NULL,
	`WORKHOURS`  DECIMAL(32,6) NOT NULL,
	`COMPANY`  STRING NOT NULL,
	`BASICCALENDARID`  STRING NOT NULL,
	`PARTITION`  STRING NOT NULL,
	`DATAAREAID`  STRING NOT NULL,
	`SYNCSTARTDATETIME` TIMESTAMP NOT NULL,
 CONSTRAINT `PK_SMRBIWorkCalendarStaging` PRIMARY KEY CLUSTERED 
(
	`EXECUTIONID` ASC,
	`CALENDARID` ASC,
	`DATAAREAID` ASC,
	`PARTITION` ASC
)WITH(STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
;
