/****** Object:  Table [dbo].[SMRBIProdTableStaging]    Script Date: 03/03/2026 16:26:09 ******/



CREATE OR REPLACE TABLE `dbo`.`SMRBIProdTableStaging`(
	`BOMID`  STRING NOT NULL,
	`COLLECTREFPRODID`  STRING NOT NULL,
	`INVENTDIMID`  STRING NOT NULL,
	`INVENTTRANSID`  STRING NOT NULL,
	`ITEMID`  STRING NOT NULL,
	`PRODID`  STRING NOT NULL,
	`ROUTEID`  STRING NOT NULL,
	`DEFAULTDIMENSIONDISPLAYVALUE`  STRING NOT NULL,
	`DEFINITIONGROUP`  STRING NOT NULL,
	`EXECUTIONID`  STRING NOT NULL,
	`ISSELECTED` int NOT NULL,
	`TRANSFERSTATUS` int NOT NULL,
	`COMPANY`  STRING NOT NULL,
	`DENSITY`  DECIMAL(32,6) NOT NULL,
	`DEPTH`  DECIMAL(32,6) NOT NULL,
	`DLVDATE` TIMESTAMP NOT NULL,
	`FINISHEDDATE` TIMESTAMP NOT NULL,
	`HEIGHT`  DECIMAL(32,6) NOT NULL,
	`INVENTREFID`  STRING NOT NULL,
	`INVENTREFTYPE` int NOT NULL,
	`PRODSTATUS` int NOT NULL,
	`QTYCALC`  DECIMAL(32,6) NOT NULL,
	`QTYSCHED`  DECIMAL(32,6) NOT NULL,
	`QTYSTUP`  DECIMAL(32,6) NOT NULL,
	`REALDATE` TIMESTAMP NOT NULL,
	`REMAININVENTPHYSICAL`  DECIMAL(32,6) NOT NULL,
	`REQPOID`  STRING NOT NULL,
	`SCHEDDATE` TIMESTAMP NOT NULL,
	`SCHEDEND` TIMESTAMP NOT NULL,
	`SCHEDSTART` TIMESTAMP NOT NULL,
	`SCHEDSTATUS` int NOT NULL,
	`STUPDATE` TIMESTAMP NOT NULL,
	`WIDTH`  DECIMAL(32,6) NOT NULL,
	`PRODTABLEDIMENSION` bigint NOT NULL,
	`PRODPOOLID`  STRING NOT NULL,
	`PARTITION`  STRING NOT NULL,
	`SYNCSTARTDATETIME` TIMESTAMP NOT NULL,
 CONSTRAINT `PK_SMRBIProdTableStaging` PRIMARY KEY CLUSTERED 
(
	`PRODID` ASC,
	`EXECUTIONID` ASC,
	`PARTITION` ASC
)WITH(STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
;
