/****** Object:  Table [dbo].[SMRBIPurchPurchaseOrderHeaderStaging]    Script Date: 03/03/2026 16:26:08 ******/



CREATE OR REPLACE TABLE `dbo`.`SMRBIPurchPurchaseOrderHeaderStaging`(
	`DEFINITIONGROUP`  STRING NOT NULL,
	`EXECUTIONID`  STRING NOT NULL,
	`ISSELECTED` int NOT NULL,
	`TRANSFERSTATUS` int NOT NULL,
	`PURCHASEORDERSTATUS` int NOT NULL,
	`ORDERVENDORACCOUNTNUMBER`  STRING NOT NULL,
	`REQUESTEDDELIVERYDATE` TIMESTAMP NOT NULL,
	`TOTALDISCOUNTPERCENTAGE`  DECIMAL(32,6) NOT NULL,
	`DELIVERYMODEID`  STRING NOT NULL,
	`DELIVERYTERMSID`  STRING NOT NULL,
	`INVOICEVENDORACCOUNTNUMBER`  STRING NOT NULL,
	`PAYMENTTERMSNAME`  STRING NOT NULL,
	`PURCHASEORDERNUMBER`  STRING NOT NULL,
	`VENDORORDERREFERENCE`  STRING NOT NULL,
	`DELIVERYADDRESSCITY`  STRING NOT NULL,
	`DELIVERYADDRESSCOUNTRYREGIONID`  STRING NOT NULL,
	`DELIVERYADDRESSSTREET`  STRING NOT NULL,
	`DELIVERYADDRESSSTREETNUMBER`  STRING NOT NULL,
	`CURRENCYCODE`  STRING NOT NULL,
	`DELIVERYADDRESSZIPCODE`  STRING NOT NULL,
	`PURCHTABLECREATEDDATETIME` TIMESTAMP NOT NULL,
	`COMPANY`  STRING NOT NULL,
	`PURCHTABLERECID` bigint NOT NULL,
	`DOCUMENTSTATUS` int NOT NULL,
	`PURCHASETYPE` int NOT NULL,
	`WORKERPURCHPLACER` bigint NOT NULL,
	`ITEMBUYERGROUPID`  STRING NOT NULL,
	`PARTITION`  STRING NOT NULL,
	`DATAAREAID`  STRING NOT NULL,
	`SYNCSTARTDATETIME` TIMESTAMP NOT NULL,
 CONSTRAINT `PK_SMRBIPurchPurchaseOrderHeaderStaging` PRIMARY KEY CLUSTERED 
(
	`EXECUTIONID` ASC,
	`PURCHASEORDERNUMBER` ASC,
	`DATAAREAID` ASC,
	`PARTITION` ASC
)WITH(STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
;
