/****** Object:  Table [dbo].[SMRBILogisticsPostalAddressBaseStaging]    Script Date: 03/03/2026 16:26:09 ******/



CREATE OR REPLACE TABLE `dbo`.`SMRBILogisticsPostalAddressBaseStaging`(
	`DEFINITIONGROUP`  STRING NOT NULL,
	`EXECUTIONID`  STRING NOT NULL,
	`ISSELECTED` int NOT NULL,
	`TRANSFERSTATUS` int NOT NULL,
	`ADDRESS`  STRING NOT NULL,
	`CITY`  STRING NOT NULL,
	`COUNTRYREGIONID`  STRING NOT NULL,
	`VALIDFROM` TIMESTAMP NOT NULL,
	`VALIDTO` TIMESTAMP NOT NULL,
	`ZIPCODE`  STRING NOT NULL,
	`LOGISCTOCSPOSTALADDRESSBASERECID` bigint NOT NULL,
	`PARTITION`  STRING NOT NULL,
	`SYNCSTARTDATETIME` TIMESTAMP NOT NULL,
	`RECID` bigint NOT NULL,
 CONSTRAINT `PK_SMRBILogisticsPostalAddressBaseStaging` PRIMARY KEY CLUSTERED 
(
	`EXECUTIONID` ASC,
	`VALIDFROM` ASC,
	`LOGISCTOCSPOSTALADDRESSBASERECID` ASC,
	`PARTITION` ASC
)WITH(STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
;
