/****** Object:  Table [dbo].[FiscalPeriodStaging]    Script Date: 03/03/2026 16:26:09 ******/



CREATE OR REPLACE TABLE `dbo`.`FiscalPeriodStaging`(
	`DEFINITIONGROUP`  STRING NOT NULL,
	`EXECUTIONID`  STRING NOT NULL,
	`ISSELECTED` int NOT NULL,
	`TRANSFERSTATUS` int NOT NULL,
	`COMMENTS`  STRING NOT NULL,
	`ENDDATE` TIMESTAMP NOT NULL,
	`MONTH` int NOT NULL,
	`PERIODNAME`  STRING NOT NULL,
	`QUARTER` int NOT NULL,
	`SHORTNAME`  STRING NOT NULL,
	`STARTDATE` TIMESTAMP NOT NULL,
	`TYPE` int NOT NULL,
	`CALENDAR`  STRING NOT NULL,
	`FISCALYEAR`  STRING NOT NULL,
	`CALENDARTYPE` int NOT NULL,
	`DAYS` int NOT NULL,
	`PARTITION`  STRING NOT NULL,
	`SYNCSTARTDATETIME` TIMESTAMP NOT NULL,
	`RECID` bigint NOT NULL,
 CONSTRAINT `PK_FiscalPeriodStaging` PRIMARY KEY CLUSTERED 
(
	`EXECUTIONID` ASC,
	`ENDDATE` ASC,
	`PERIODNAME` ASC,
	`STARTDATE` ASC,
	`CALENDAR` ASC,
	`FISCALYEAR` ASC,
	`PARTITION` ASC
)WITH(STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
;
