/****** Object:  Table [dbo].[SMRBICostSheetNodeTableStaging]    Script Date: 03/03/2026 16:26:09 ******/



CREATE OR REPLACE TABLE `dbo`.`SMRBICostSheetNodeTableStaging`(
	`DEFINITIONGROUP`  STRING NOT NULL,
	`EXECUTIONID`  STRING NOT NULL,
	`ISSELECTED` int NOT NULL,
	`TRANSFERSTATUS` int NOT NULL,
	`CODE`  STRING NOT NULL,
	`COSTGROUPID`  STRING NOT NULL,
	`COMPANY`  STRING NOT NULL,
	`DESCRIPTION`  STRING NOT NULL,
	`LEVEL_` int NOT NULL,
	`NODEID` int NOT NULL,
	`PARENTNODEID` int NOT NULL,
	`PARTITION`  STRING NOT NULL,
	`DATAAREAID`  STRING NOT NULL,
	`SYNCSTARTDATETIME` TIMESTAMP NOT NULL,
 CONSTRAINT `PK_SMRBICostSheetNodeTableStaging` PRIMARY KEY CLUSTERED 
(
	`EXECUTIONID` ASC,
	`NODEID` ASC,
	`DATAAREAID` ASC,
	`PARTITION` ASC
)WITH(STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
;
