/****** Object:  Table [dbo].[SMRBIWorkCalendarTimeIntervalStaging]    Script Date: 03/03/2026 16:26:08 ******/



CREATE OR REPLACE TABLE `dbo`.`SMRBIWorkCalendarTimeIntervalStaging`(
	`DEFINITIONGROUP`  STRING NOT NULL,
	`EXECUTIONID`  STRING NOT NULL,
	`ISSELECTED` int NOT NULL,
	`TRANSFERSTATUS` int NOT NULL,
	`WORKCALENDARID`  STRING NOT NULL,
	`WORKCALENDARDATE` TIMESTAMP NOT NULL,
	`STARTTIME` int NOT NULL,
	`ENDTIME` int NOT NULL,
	`EFFICIENCYPERCENTAGE`  DECIMAL(32,6) NOT NULL,
	`COMPANY`  STRING NOT NULL,
	`PARTITION`  STRING NOT NULL,
	`DATAAREAID`  STRING NOT NULL,
	`SYNCSTARTDATETIME` TIMESTAMP NOT NULL,
	`RECID` bigint NOT NULL,
 CONSTRAINT `PK_SMRBIWorkCalendarTimeIntervalStaging` PRIMARY KEY CLUSTERED 
(
	`EXECUTIONID` ASC,
	`WORKCALENDARID` ASC,
	`WORKCALENDARDATE` ASC,
	`STARTTIME` ASC,
	`DATAAREAID` ASC,
	`PARTITION` ASC
)WITH(STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
;
