/****** Object:  Table [dbo].[SMRBIInventDimStaging]    Script Date: 03/03/2026 16:26:08 ******/



CREATE OR REPLACE TABLE `dbo`.`SMRBIInventDimStaging`(
	`DEFINITIONGROUP`  STRING NOT NULL,
	`EXECUTIONID`  STRING NOT NULL,
	`ISSELECTED` int NOT NULL,
	`TRANSFERSTATUS` int NOT NULL,
	`CONFIGID`  STRING NOT NULL,
	`INVENTBATCHID`  STRING NOT NULL,
	`INVENTCOLORID`  STRING NOT NULL,
	`INVENTDIMID`  STRING NOT NULL,
	`INVENTLOCATIONID`  STRING NOT NULL,
	`INVENTSITEID`  STRING NOT NULL,
	`INVENTSIZEID`  STRING NOT NULL,
	`INVENTSTATUSID`  STRING NOT NULL,
	`INVENTSTYLEID`  STRING NOT NULL,
	`WMSLOCATIONID`  STRING NOT NULL,
	`COMPANY`  STRING NOT NULL,
	`INVENTDIMMODIFIEDDATETIME` TIMESTAMP NOT NULL,
	`INVENTSERIALID`  STRING NOT NULL,
	`PARTITION`  STRING NOT NULL,
	`DATAAREAID`  STRING NOT NULL,
	`SYNCSTARTDATETIME` TIMESTAMP NOT NULL,
 CONSTRAINT `PK_SMRBIInventDimStaging` PRIMARY KEY CLUSTERED 
(
	`EXECUTIONID` ASC,
	`INVENTDIMID` ASC,
	`DATAAREAID` ASC,
	`PARTITION` ASC
)WITH(STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
;
