/****** Object:  Table [dbo].[SMRBIReqPlanVersionStaging]    Script Date: 03/03/2026 16:26:08 ******/



CREATE OR REPLACE TABLE `dbo`.`SMRBIReqPlanVersionStaging`(
	`DEFINITIONGROUP`  STRING NOT NULL,
	`EXECUTIONID`  STRING NOT NULL,
	`ISSELECTED` int NOT NULL,
	`TRANSFERSTATUS` int NOT NULL,
	`ACTIVE` int NOT NULL,
	`REQPLANVERSIONRECID` bigint NOT NULL,
	`REQPLANDATAAREAID`  STRING NOT NULL,
	`REQPLANID`  STRING NOT NULL,
	`PARTITION`  STRING NOT NULL,
	`SYNCSTARTDATETIME` TIMESTAMP NOT NULL,
	`RECID` bigint NOT NULL,
 CONSTRAINT `PK_SMRBIReqPlanVersionStaging` PRIMARY KEY CLUSTERED 
(
	`EXECUTIONID` ASC,
	`REQPLANVERSIONRECID` ASC,
	`PARTITION` ASC
)WITH(STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
;
