/****** Object:  Table [dbo].[SMRBIProdBOMStaging]    Script Date: 03/03/2026 16:26:09 ******/



CREATE OR REPLACE TABLE `dbo`.`SMRBIProdBOMStaging`(
	`DEFINITIONGROUP`  STRING NOT NULL,
	`EXECUTIONID`  STRING NOT NULL,
	`ISSELECTED` int NOT NULL,
	`TRANSFERSTATUS` int NOT NULL,
	`BOMID`  STRING NOT NULL,
	`BOMQTY`  DECIMAL(32,6) NOT NULL,
	`BOMQTYSERIE`  DECIMAL(32,6) NOT NULL,
	`BOMREFRECID` bigint NOT NULL,
	`CALCULATION` int NOT NULL,
	`COMPANY`  STRING NOT NULL,
	`INVENTDIMID`  STRING NOT NULL,
	`INVENTREFID`  STRING NOT NULL,
	`INVENTREFTRANSID`  STRING NOT NULL,
	`ITEMID`  STRING NOT NULL,
	`LINENUM`  DECIMAL(32,16) NOT NULL,
	`OPRNUM` int NOT NULL,
	`PRODID`  STRING NOT NULL,
	`QTYINVENTCALC`  DECIMAL(32,6) NOT NULL,
	`SCRAPCONST`  DECIMAL(32,6) NOT NULL,
	`SCRAPVAR`  DECIMAL(32,6) NOT NULL,
	`UNITID`  STRING NOT NULL,
	`PRODBOMRECID` bigint NOT NULL,
	`PARTITION`  STRING NOT NULL,
	`SYNCSTARTDATETIME` TIMESTAMP NOT NULL,
	`RECID` bigint NOT NULL,
 CONSTRAINT `PK_SMRBIProdBOMStaging` PRIMARY KEY CLUSTERED 
(
	`EXECUTIONID` ASC,
	`BOMID` ASC,
	`PRODBOMRECID` ASC,
	`PARTITION` ASC
)WITH(STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
;
