/****** Object:  Table [dbo].[SMRBIMarkupTransStaging]    Script Date: 03/03/2026 16:26:08 ******/



CREATE OR REPLACE TABLE `dbo`.`SMRBIMarkupTransStaging`(
	`DEFINITIONGROUP`  STRING NOT NULL,
	`EXECUTIONID`  STRING NOT NULL,
	`ISSELECTED` int NOT NULL,
	`TRANSFERSTATUS` int NOT NULL,
	`CALCULATEDAMOUNT`  DECIMAL(32,6) NOT NULL,
	`CURRENCYCODE`  STRING NOT NULL,
	`COMPANY`  STRING NOT NULL,
	`MARKUPCATEGORY` int NOT NULL,
	`MARKUPCODE`  STRING NOT NULL,
	`TRANSRECID` bigint NOT NULL,
	`TRANSTABLEID` int NOT NULL,
	`VALUE`  DECIMAL(32,6) NOT NULL,
	`MARKUPTRANSRECID` bigint NOT NULL,
	`PARTITION`  STRING NOT NULL,
	`DATAAREAID`  STRING NOT NULL,
	`SYNCSTARTDATETIME` TIMESTAMP NOT NULL,
 CONSTRAINT `PK_SMRBIMarkupTransStaging` PRIMARY KEY CLUSTERED 
(
	`EXECUTIONID` ASC,
	`CALCULATEDAMOUNT` ASC,
	`CURRENCYCODE` ASC,
	`COMPANY` ASC,
	`MARKUPCATEGORY` ASC,
	`MARKUPCODE` ASC,
	`TRANSRECID` ASC,
	`TRANSTABLEID` ASC,
	`VALUE` ASC,
	`MARKUPTRANSRECID` ASC,
	`DATAAREAID` ASC,
	`PARTITION` ASC
)WITH(STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
;
