/****** Object:  Table [dbo].[SMRBIInventTestOperationItemsStaging]    Script Date: 03/03/2026 16:26:09 ******/



CREATE OR REPLACE TABLE `dbo`.`SMRBIInventTestOperationItemsStaging`(
	`DEFINITIONGROUP`  STRING NOT NULL,
	`EXECUTIONID`  STRING NOT NULL,
	`ISSELECTED` int NOT NULL,
	`TRANSFERSTATUS` int NOT NULL,
	`COSTAMOUNT`  DECIMAL(32,6) NOT NULL,
	`INVENTNONCONFORMANCEID`  STRING NOT NULL,
	`INVENTQTY`  DECIMAL(32,6) NOT NULL,
	`ITEMID`  STRING NOT NULL,
	`LINENUM`  DECIMAL(32,16) NOT NULL,
	`COMPANY`  STRING NOT NULL,
	`PARTITION`  STRING NOT NULL,
	`DATAAREAID`  STRING NOT NULL,
	`SYNCSTARTDATETIME` TIMESTAMP NOT NULL,
	`RECID` bigint NOT NULL,
 CONSTRAINT `PK_SMRBIInventTestOperationItemsStaging` PRIMARY KEY CLUSTERED 
(
	`EXECUTIONID` ASC,
	`COSTAMOUNT` ASC,
	`INVENTNONCONFORMANCEID` ASC,
	`INVENTQTY` ASC,
	`ITEMID` ASC,
	`LINENUM` ASC,
	`DATAAREAID` ASC,
	`PARTITION` ASC
)WITH(STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
;
