/****** Object:  Table [dbo].[SMRBIDimensionAttributeLevelValueAllViewStaging]    Script Date: 03/03/2026 16:26:08 ******/



CREATE OR REPLACE TABLE `dbo`.`SMRBIDimensionAttributeLevelValueAllViewStaging`(
	`DEFINITIONGROUP`  STRING NOT NULL,
	`EXECUTIONID`  STRING NOT NULL,
	`ISSELECTED` int NOT NULL,
	`TRANSFERSTATUS` int NOT NULL,
	`VALUECOMBINATIONRECID` bigint NOT NULL,
	`DISPLAYVALUE`  STRING NOT NULL,
	`ENTITYINSTANCE` bigint NOT NULL,
	`DIMENSIONATTRIBUTE` bigint NOT NULL,
	`PARTITION`  STRING NOT NULL,
	`SYNCSTARTDATETIME` TIMESTAMP NOT NULL,
	`RECID` bigint NOT NULL,
 CONSTRAINT `PK_SMRBIDimensionAttributeLevelValueAllViewStaging` PRIMARY KEY CLUSTERED 
(
	`EXECUTIONID` ASC,
	`VALUECOMBINATIONRECID` ASC,
	`DISPLAYVALUE` ASC,
	`ENTITYINSTANCE` ASC,
	`DIMENSIONATTRIBUTE` ASC,
	`PARTITION` ASC
)WITH(STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
;
