/****** Object:  Table [dbo].[SMRBIPurchRFQTableStaging]    Script Date: 03/03/2026 16:26:08 ******/



CREATE OR REPLACE TABLE `dbo`.`SMRBIPurchRFQTableStaging`(
	`DEFINITIONGROUP`  STRING NOT NULL,
	`EXECUTIONID`  STRING NOT NULL,
	`ISSELECTED` int NOT NULL,
	`TRANSFERSTATUS` int NOT NULL,
	`COMPANY`  STRING NOT NULL,
	`DLVMODE`  STRING NOT NULL,
	`DLVTERM`  STRING NOT NULL,
	`RFQCASEID`  STRING NOT NULL,
	`RFQID`  STRING NOT NULL,
	`RFQNAME`  STRING NOT NULL,
	`VENDACCOUNT`  STRING NOT NULL,
	`PURCHRFQTABLECREATEDDATETIME` TIMESTAMP NOT NULL,
	`PARTITION`  STRING NOT NULL,
	`DATAAREAID`  STRING NOT NULL,
	`SYNCSTARTDATETIME` TIMESTAMP NOT NULL,
 CONSTRAINT `PK_SMRBIPurchRFQTableStaging` PRIMARY KEY CLUSTERED 
(
	`EXECUTIONID` ASC,
	`COMPANY` ASC,
	`DLVMODE` ASC,
	`DLVTERM` ASC,
	`RFQCASEID` ASC,
	`RFQID` ASC,
	`RFQNAME` ASC,
	`VENDACCOUNT` ASC,
	`DATAAREAID` ASC,
	`PARTITION` ASC
)WITH(STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
;
