/****** Object:  Table [dbo].[SMRBIVendInvoiceJourStaging]    Script Date: 03/03/2026 16:26:09 ******/



CREATE OR REPLACE TABLE `dbo`.`SMRBIVendInvoiceJourStaging`(
	`DEFINITIONGROUP`  STRING NOT NULL,
	`EXECUTIONID`  STRING NOT NULL,
	`ISSELECTED` int NOT NULL,
	`TRANSFERSTATUS` int NOT NULL,
	`CURRENCYCODE`  STRING NOT NULL,
	`COMPANY`  STRING NOT NULL,
	`DLVMODE`  STRING NOT NULL,
	`DLVTERM`  STRING NOT NULL,
	`INTERNALINVOICEID`  STRING NOT NULL,
	`INVOICEACCOUNT`  STRING NOT NULL,
	`INVOICEAMOUNT`  DECIMAL(32,6) NOT NULL,
	`INVOICEAMOUNTMST`  DECIMAL(32,6) NOT NULL,
	`INVOICEDATE` TIMESTAMP NOT NULL,
	`INVOICEID`  STRING NOT NULL,
	`PAYMENT`  STRING NOT NULL,
	`PURCHID`  STRING NOT NULL,
	`VENDINVOICEJOURRECID` bigint NOT NULL,
	`QTY`  DECIMAL(32,6) NOT NULL,
	`SUMTAX`  DECIMAL(32,6) NOT NULL,
	`VENDINVOICEJOURCREATEDBY`  STRING NOT NULL,
	`VENDINVOICEJOURCREATEDDATETIME` TIMESTAMP NOT NULL,
	`PARTITION`  STRING NOT NULL,
	`DATAAREAID`  STRING NOT NULL,
	`SYNCSTARTDATETIME` TIMESTAMP NOT NULL,
	`RECID` bigint NOT NULL,
 CONSTRAINT `PK_SMRBIVendInvoiceJourStaging` PRIMARY KEY CLUSTERED 
(
	`EXECUTIONID` ASC,
	`VENDINVOICEJOURRECID` ASC,
	`DATAAREAID` ASC,
	`PARTITION` ASC
)WITH(STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
;
