/****** Object:  Table [dbo].[SMRBIWrkCtrActivityResourceRequirementStaging]    Script Date: 03/03/2026 16:26:09 ******/



CREATE OR REPLACE TABLE `dbo`.`SMRBIWrkCtrActivityResourceRequirementStaging`(
	`DEFINITIONGROUP`  STRING NOT NULL,
	`EXECUTIONID`  STRING NOT NULL,
	`ISSELECTED` int NOT NULL,
	`TRANSFERSTATUS` int NOT NULL,
	`ACTIVITYREQUIREMENT` bigint NOT NULL,
	`RESOURCEDATAAREAID`  STRING NOT NULL,
	`WRKCTRID`  STRING NOT NULL,
	`PARTITION`  STRING NOT NULL,
	`SYNCSTARTDATETIME` TIMESTAMP NOT NULL,
	`RECID` bigint NOT NULL,
 CONSTRAINT `PK_SMRBIWrkCtrActivityResourceRequirementStaging` PRIMARY KEY CLUSTERED 
(
	`EXECUTIONID` ASC,
	`ACTIVITYREQUIREMENT` ASC,
	`RESOURCEDATAAREAID` ASC,
	`WRKCTRID` ASC,
	`PARTITION` ASC
)WITH(STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
;
