/****** Object:  Table [dbo].[SMRBIVendReviewCriterionRatingStaging]    Script Date: 03/03/2026 16:26:09 ******/



CREATE OR REPLACE TABLE `dbo`.`SMRBIVendReviewCriterionRatingStaging`(
	`DEFINITIONGROUP`  STRING NOT NULL,
	`EXECUTIONID`  STRING NOT NULL,
	`ISSELECTED` int NOT NULL,
	`TRANSFERSTATUS` int NOT NULL,
	`CRITERION` bigint NOT NULL,
	`RATING` int NOT NULL,
	`VALIDFROM` TIMESTAMP NOT NULL,
	`VALIDTO` TIMESTAMP NOT NULL,
	`VENDORACCOUNTNUMBER`  STRING NOT NULL,
	`VENDORDATAAREAID`  STRING NOT NULL,
	`PARTITION`  STRING NOT NULL,
	`SYNCSTARTDATETIME` TIMESTAMP NOT NULL,
	`RECID` bigint NOT NULL,
 CONSTRAINT `PK_SMRBIVendReviewCriterionRatingStaging` PRIMARY KEY CLUSTERED 
(
	`EXECUTIONID` ASC,
	`CRITERION` ASC,
	`RATING` ASC,
	`VALIDFROM` ASC,
	`VALIDTO` ASC,
	`VENDORACCOUNTNUMBER` ASC,
	`VENDORDATAAREAID` ASC,
	`PARTITION` ASC
)WITH(STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
;
