/****** Object:  Table [dbo].[SMRBIProjectCategoryStaging]    Script Date: 03/03/2026 16:26:09 ******/



CREATE OR REPLACE TABLE `dbo`.`SMRBIProjectCategoryStaging`(
	`DEFINITIONGROUP`  STRING NOT NULL,
	`EXECUTIONID`  STRING NOT NULL,
	`ISSELECTED` int NOT NULL,
	`TRANSFERSTATUS` int NOT NULL,
	`CATEGORY`  STRING NOT NULL,
	`CATEGORYNAME`  STRING NOT NULL,
	`COMPANY`  STRING NOT NULL,
	`PARTITION`  STRING NOT NULL,
	`DATAAREAID`  STRING NOT NULL,
	`SYNCSTARTDATETIME` TIMESTAMP NOT NULL,
 CONSTRAINT `PK_SMRBIProjectCategoryStaging` PRIMARY KEY CLUSTERED 
(
	`EXECUTIONID` ASC,
	`CATEGORY` ASC,
	`DATAAREAID` ASC,
	`PARTITION` ASC
)WITH(STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
;
