/****** Object:  Table [dbo].[SMRBILedgerChartOfAccountsStaging]    Script Date: 03/03/2026 16:26:09 ******/



CREATE OR REPLACE TABLE `dbo`.`SMRBILedgerChartOfAccountsStaging`(
	`DEFINITIONGROUP`  STRING NOT NULL,
	`EXECUTIONID`  STRING NOT NULL,
	`ISSELECTED` int NOT NULL,
	`TRANSFERSTATUS` int NOT NULL,
	`DESCRIPTION`  STRING NOT NULL,
	`CHARTOFACCOUNTS`  STRING NOT NULL,
	`CHARTOFACCOUNTSRECID` bigint NOT NULL,
	`LEDGERCHARTOFACCOUNTSRECID` bigint NOT NULL,
	`PARTITION`  STRING NOT NULL,
	`SYNCSTARTDATETIME` TIMESTAMP NOT NULL,
	`RECID` bigint NOT NULL,
 CONSTRAINT `PK_SMRBILedgerChartOfAccountsStaging` PRIMARY KEY CLUSTERED 
(
	`EXECUTIONID` ASC,
	`CHARTOFACCOUNTS` ASC,
	`PARTITION` ASC
)WITH(STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
;
