/****** Object:  Table [dbo].[SMRBILedgerStaging]    Script Date: 03/03/2026 16:26:08 ******/



CREATE OR REPLACE TABLE `dbo`.`SMRBILedgerStaging`(
	`DEFINITIONGROUP`  STRING NOT NULL,
	`EXECUTIONID`  STRING NOT NULL,
	`ISSELECTED` int NOT NULL,
	`TRANSFERSTATUS` int NOT NULL,
	`BUDGETEXCHANGERATETYPE`  STRING NOT NULL,
	`ACCOUNTINGCURRENCY`  STRING NOT NULL,
	`CHARTOFACCOUNTSRECID` bigint NOT NULL,
	`EXCHANGERATETYPE`  STRING NOT NULL,
	`NAME`  STRING NOT NULL,
	`REPORTINGCURRENCY`  STRING NOT NULL,
	`LEDGERRECID` bigint NOT NULL,
	`PARTITION`  STRING NOT NULL,
	`SYNCSTARTDATETIME` TIMESTAMP NOT NULL,
	`RECID` bigint NOT NULL,
 CONSTRAINT `PK_SMRBILedgerStaging` PRIMARY KEY CLUSTERED 
(
	`EXECUTIONID` ASC,
	`LEDGERRECID` ASC,
	`PARTITION` ASC
)WITH(STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
;
