/****** Object:  Table [dbo].[SMRBIDirPartyStaging]    Script Date: 03/03/2026 16:26:09 ******/



CREATE OR REPLACE TABLE `dbo`.`SMRBIDirPartyStaging`(
	`DEFINITIONGROUP`  STRING NOT NULL,
	`EXECUTIONID`  STRING NOT NULL,
	`ISSELECTED` int NOT NULL,
	`TRANSFERSTATUS` int NOT NULL,
	`PARTYNUMBER`  STRING NOT NULL,
	`NAMEALIAS`  STRING NOT NULL,
	`LEGALENTITYDATAAREA`  STRING NOT NULL,
	`OPERATINGUNITNUMBER`  STRING NOT NULL,
	`OPERATINGUNITTYPE` int NOT NULL,
	`DIRPARTYRECID` bigint NOT NULL,
	`VALIDFROM` TIMESTAMP NOT NULL,
	`VALIDTO` TIMESTAMP NOT NULL,
	`PARTITION`  STRING NOT NULL,
	`SYNCSTARTDATETIME` TIMESTAMP NOT NULL,
	`RECID` bigint NOT NULL,
 CONSTRAINT `PK_SMRBIDirPartyStaging` PRIMARY KEY CLUSTERED 
(
	`EXECUTIONID` ASC,
	`PARTYNUMBER` ASC,
	`PARTITION` ASC
)WITH(STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
;
