/****** Object:  Table [dbo].[SMRBIUnitOfMeasureConversionStaging]    Script Date: 03/03/2026 16:26:08 ******/



CREATE OR REPLACE TABLE `dbo`.`SMRBIUnitOfMeasureConversionStaging`(
	`DEFINITIONGROUP`  STRING NOT NULL,
	`EXECUTIONID`  STRING NOT NULL,
	`ISSELECTED` int NOT NULL,
	`TRANSFERSTATUS` int NOT NULL,
	`DENOMINATOR` int NOT NULL,
	`FACTOR`  DECIMAL(32,16) NOT NULL,
	`INNEROFFSET`  DECIMAL(32,6) NOT NULL,
	`NUMERATOR` int NOT NULL,
	`OUTEROFFSET`  DECIMAL(32,6) NOT NULL,
	`ROUNDING` int NOT NULL,
	`FROMUNITSYMBOL`  STRING NOT NULL,
	`TOUNITSYMBOL`  STRING NOT NULL,
	`PRODUCT` bigint NOT NULL,
	`UNITOFMEASURECONVERSIONRECID` bigint NOT NULL,
	`UOMMODIFIEDDATETIME` TIMESTAMP NOT NULL,
	`PARTITION`  STRING NOT NULL,
	`SYNCSTARTDATETIME` TIMESTAMP NOT NULL,
	`RECID` bigint NOT NULL,
 CONSTRAINT `PK_SMRBIUnitOfMeasureConversionStaging` PRIMARY KEY CLUSTERED 
(
	`EXECUTIONID` ASC,
	`FROMUNITSYMBOL` ASC,
	`TOUNITSYMBOL` ASC,
	`PARTITION` ASC
)WITH(STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
;
