/****** Object:  Table [dbo].[SMRBIBudgetRegisterEntryLineStaging]    Script Date: 03/03/2026 16:26:08 ******/



CREATE OR REPLACE TABLE `dbo`.`SMRBIBudgetRegisterEntryLineStaging`(
	`DEFINITIONGROUP`  STRING NOT NULL,
	`EXECUTIONID`  STRING NOT NULL,
	`ISSELECTED` int NOT NULL,
	`TRANSFERSTATUS` int NOT NULL,
	`ACCOUNTINGCURRENCYAMOUNT`  DECIMAL(32,6) NOT NULL,
	`AMOUNTTYPE` int NOT NULL,
	`BUDGETTRANSACTIONHEADERRECID` bigint NOT NULL,
	`CURRENCYCODE`  STRING NOT NULL,
	`ENTRYDATE` TIMESTAMP NOT NULL,
	`LINENUMBER`  DECIMAL(32,16) NOT NULL,
	`PRICE`  DECIMAL(32,6) NOT NULL,
	`QUANTITY`  DECIMAL(32,6) NOT NULL,
	`TRANSACTIONCURRENCYAMOUNT`  DECIMAL(32,6) NOT NULL,
	`GENERALJOURNALENTRY` bigint NOT NULL,
	`BUDGETREGISTERLINERECID` bigint NOT NULL,
	`LEGALENTITYID`  STRING NOT NULL,
	`LEDGERDIMENSIONACCOUNTSTRUCTURE`  STRING NOT NULL,
	`LEDGERDIMENSIONDISPLAYVALUE`  STRING NOT NULL,
	`PARTITION`  STRING NOT NULL,
	`DATAAREAID`  STRING NOT NULL,
	`SYNCSTARTDATETIME` TIMESTAMP NOT NULL,
	`RECID` bigint NOT NULL,
 CONSTRAINT `PK_SMRBIBudgetRegisterEntryLineStaging` PRIMARY KEY CLUSTERED 
(
	`EXECUTIONID` ASC,
	`LINENUMBER` ASC,
	`BUDGETREGISTERLINERECID` ASC,
	`LEGALENTITYID` ASC,
	`DATAAREAID` ASC,
	`PARTITION` ASC
)WITH(STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
;
