/****** Object:  Table [dbo].[SMRBIForecastSupplyForecastStaging]    Script Date: 03/03/2026 16:26:08 ******/



CREATE OR REPLACE TABLE `dbo`.`SMRBIForecastSupplyForecastStaging`(
	`DEFINITIONGROUP`  STRING NOT NULL,
	`EXECUTIONID`  STRING NOT NULL,
	`ISSELECTED` int NOT NULL,
	`TRANSFERSTATUS` int NOT NULL,
	`AMOUNT`  DECIMAL(32,6) NOT NULL,
	`CURRENCY`  STRING NOT NULL,
	`COMPANY`  STRING NOT NULL,
	`ENDDATE` TIMESTAMP NOT NULL,
	`INVENTDIMID`  STRING NOT NULL,
	`ITEMID`  STRING NOT NULL,
	`MODELID`  STRING NOT NULL,
	`PURCHPRICE`  DECIMAL(32,6) NOT NULL,
	`PURCHQTY`  DECIMAL(32,6) NOT NULL,
	`PURCHUNITID`  STRING NOT NULL,
	`STARTDATE` TIMESTAMP NOT NULL,
	`VENDACCOUNTID`  STRING NOT NULL,
	`FORECASTSUPPLYFORECASTDIMENSION` bigint NOT NULL,
	`PARTITION`  STRING NOT NULL,
	`DATAAREAID`  STRING NOT NULL,
	`SYNCSTARTDATETIME` TIMESTAMP NOT NULL,
	`RECID` bigint NOT NULL,
 CONSTRAINT `PK_SMRBIForecastSupplyForecastStaging` PRIMARY KEY CLUSTERED 
(
	`EXECUTIONID` ASC,
	`AMOUNT` ASC,
	`CURRENCY` ASC,
	`COMPANY` ASC,
	`ENDDATE` ASC,
	`INVENTDIMID` ASC,
	`ITEMID` ASC,
	`MODELID` ASC,
	`PURCHPRICE` ASC,
	`PURCHQTY` ASC,
	`PURCHUNITID` ASC,
	`STARTDATE` ASC,
	`VENDACCOUNTID` ASC,
	`DATAAREAID` ASC,
	`PARTITION` ASC
)WITH(STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
;
