/****** Object:  Table [dbo].[SMRBIDirPersonStaging]    Script Date: 03/03/2026 16:26:08 ******/



CREATE OR REPLACE TABLE `dbo`.`SMRBIDirPersonStaging`(
	`DEFINITIONGROUP`  STRING NOT NULL,
	`EXECUTIONID`  STRING NOT NULL,
	`ISSELECTED` int NOT NULL,
	`TRANSFERSTATUS` int NOT NULL,
	`PARTYNUMBER`  STRING NOT NULL,
	`USER_`  STRING NOT NULL,
	`DIRPERSONRECID` bigint NOT NULL,
	`VALIDTO` TIMESTAMP NOT NULL,
	`VALIDFROM` TIMESTAMP NOT NULL,
	`PARTITION`  STRING NOT NULL,
	`SYNCSTARTDATETIME` TIMESTAMP NOT NULL,
	`RECID` bigint NOT NULL
)
;
