/****** Object:  Table [dbo].[SMRBIProjBudgetLineDetailStaging]    Script Date: 03/03/2026 16:26:09 ******/



CREATE OR REPLACE TABLE `dbo`.`SMRBIProjBudgetLineDetailStaging`(
	`DEFINITIONGROUP`  STRING NOT NULL,
	`EXECUTIONID`  STRING NOT NULL,
	`ISSELECTED` int NOT NULL,
	`TRANSFERSTATUS` int NOT NULL,
	`COSTPRICE`  DECIMAL(32,6) NOT NULL,
	`HCMWORKER` bigint NOT NULL,
	`INVENTDIMID`  STRING NOT NULL,
	`ITEMID`  STRING NOT NULL,
	`PROJBUDGETLINE` bigint NOT NULL,
	`PROJBUDGETREVISIONLINE` bigint NOT NULL,
	`QUANTITY`  DECIMAL(32,6) NOT NULL,
	`RESOURCE_` bigint NOT NULL,
	`RESOURCECATEGORY` bigint NOT NULL,
	`SALESCATEGORY` bigint NOT NULL,
	`SALESPRICE`  DECIMAL(32,6) NOT NULL,
	`SALESUNITID`  STRING NOT NULL,
	`PARTITION`  STRING NOT NULL,
	`DATAAREAID`  STRING NOT NULL,
	`SYNCSTARTDATETIME` TIMESTAMP NOT NULL,
	`RECID` bigint NOT NULL,
 CONSTRAINT `PK_SMRBIProjBudgetLineDetailStaging` PRIMARY KEY CLUSTERED 
(
	`EXECUTIONID` ASC,
	`PROJBUDGETLINE` ASC,
	`DATAAREAID` ASC,
	`PARTITION` ASC
)WITH(STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
;
