/****** Object:  Table [dbo].[SMRBIVendPackingSlipJourStaging]    Script Date: 03/03/2026 16:26:08 ******/



CREATE OR REPLACE TABLE `dbo`.`SMRBIVendPackingSlipJourStaging`(
	`DEFINITIONGROUP`  STRING NOT NULL,
	`EXECUTIONID`  STRING NOT NULL,
	`ISSELECTED` int NOT NULL,
	`TRANSFERSTATUS` int NOT NULL,
	`DELIVERYDATE` TIMESTAMP NOT NULL,
	`DELIVERYNAME`  STRING NOT NULL,
	`DELIVERYTYPE` int NOT NULL,
	`DLVMODE`  STRING NOT NULL,
	`DLVTERM`  STRING NOT NULL,
	`FREIGHTSLIPNUM`  STRING NOT NULL,
	`FREIGHTSLIPTYPE` int NOT NULL,
	`INTERCOMPANYCOMPANYID`  STRING NOT NULL,
	`INTERCOMPANYSALESID`  STRING NOT NULL,
	`INVOICEACCOUNT`  STRING NOT NULL,
	`ORDERACCOUNT`  STRING NOT NULL,
	`PACKINGSLIPID`  STRING NOT NULL,
	`PURCHASETYPE` int NOT NULL,
	`PURCHID`  STRING NOT NULL,
	`VENDPACKINGSLIPJOURRECID` bigint NOT NULL,
	`COMPANY`  STRING NOT NULL,
	`VENDPACKINGSLIPJOURDIMENSION` bigint NOT NULL,
	`PARTITION`  STRING NOT NULL,
	`DATAAREAID`  STRING NOT NULL,
	`SYNCSTARTDATETIME` TIMESTAMP NOT NULL,
	`RECID` bigint NOT NULL,
 CONSTRAINT `PK_SMRBIVendPackingSlipJourStaging` PRIMARY KEY CLUSTERED 
(
	`EXECUTIONID` ASC,
	`VENDPACKINGSLIPJOURRECID` ASC,
	`DATAAREAID` ASC,
	`PARTITION` ASC
)WITH(STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
;
