/****** Object:  Table [dbo].[SMRBIVendReviewCriterionGroupRatingStaging]    Script Date: 03/03/2026 16:26:09 ******/



CREATE OR REPLACE TABLE `dbo`.`SMRBIVendReviewCriterionGroupRatingStaging`(
	`DEFINITIONGROUP`  STRING NOT NULL,
	`EXECUTIONID`  STRING NOT NULL,
	`ISSELECTED` int NOT NULL,
	`TRANSFERSTATUS` int NOT NULL,
	`AVERAGERATING`  DECIMAL(32,6) NOT NULL,
	`CRITERIONGROUP` bigint NOT NULL,
	`VENDORACCOUNTNUMBER`  STRING NOT NULL,
	`VENDORDATAAREAID`  STRING NOT NULL,
	`PARTITION`  STRING NOT NULL,
	`SYNCSTARTDATETIME` TIMESTAMP NOT NULL,
	`RECID` bigint NOT NULL,
 CONSTRAINT `PK_SMRBIVendReviewCriterionGroupRatingStaging` PRIMARY KEY CLUSTERED 
(
	`EXECUTIONID` ASC,
	`CRITERIONGROUP` ASC,
	`VENDORACCOUNTNUMBER` ASC,
	`VENDORDATAAREAID` ASC,
	`PARTITION` ASC
)WITH(STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
;
