/****** Object:  Table [dbo].[SMRBICustomerStaging]    Script Date: 03/03/2026 16:26:08 ******/



CREATE OR REPLACE TABLE `dbo`.`SMRBICustomerStaging`(
	`DEFINITIONGROUP`  STRING NOT NULL,
	`EXECUTIONID`  STRING NOT NULL,
	`ISSELECTED` int NOT NULL,
	`TRANSFERSTATUS` int NOT NULL,
	`COMMISSIONSALESGROUPID`  STRING NOT NULL,
	`CUSTOMERACCOUNT`  STRING NOT NULL,
	`NAME`  STRING NOT NULL,
	`CUSTOMERGROUPID`  STRING NOT NULL,
	`PARTYNUMBER`  STRING NOT NULL,
	`SALESSEGMENTID`  STRING NOT NULL,
	`SALESSUBSEGMENTID`  STRING NOT NULL,
	`DELIVERYADDRESSLOCATIONID`  STRING NOT NULL,
	`CUSTCLASSIFICATIONID`  STRING NOT NULL,
	`CREATEDDATETIME1` TIMESTAMP NOT NULL,
	`CUSTOMERRECID` bigint NOT NULL,
	`DLVTERM`  STRING NOT NULL,
	`COMPANY`  STRING NOT NULL,
	`CITY`  STRING NOT NULL,
	`COUNTRYREGIONID`  STRING NOT NULL,
	`ZIPCODE`  STRING NOT NULL,
	`ADDRESS`  STRING NOT NULL,
	`ADDRESSVALIDTO` TIMESTAMP NOT NULL,
	`ADDRESSVALIDFROM` TIMESTAMP NOT NULL,
	`DELIVERYVALIDTO` TIMESTAMP NOT NULL,
	`DELIVERYVALIDFROM` TIMESTAMP NOT NULL,
	`ONHOLDSTATUS` int NOT NULL,
	`CREDITLIMITISMANDATORY` int NOT NULL,
	`CREDITLIMIT`  DECIMAL(32,6) NOT NULL,
	`MAINCONTACTWORKER` bigint NOT NULL,
	`DEFAULTDIMENSION` bigint NOT NULL,
	`PARTITION`  STRING NOT NULL,
	`YSLECOMPANYCHAINID`  STRING NOT NULL,
	`YSLEGROUPDIMENSION`  STRING NOT NULL,
	`DATAAREAID`  STRING NOT NULL,
	`SYNCSTARTDATETIME` TIMESTAMP NOT NULL,
 CONSTRAINT `PK_SMRBICustomerStaging` PRIMARY KEY CLUSTERED 
(
	`EXECUTIONID` ASC,
	`CUSTOMERACCOUNT` ASC,
	`DATAAREAID` ASC,
	`PARTITION` ASC
)WITH(STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
;
