/****** Object:  Table [dbo].[SMRBIEcoResReleasedProductStaging]    Script Date: 03/03/2026 16:26:08 ******/



CREATE OR REPLACE TABLE `dbo`.`SMRBIEcoResReleasedProductStaging`(
	`DEFINITIONGROUP`  STRING NOT NULL,
	`EXECUTIONID`  STRING NOT NULL,
	`ISSELECTED` int NOT NULL,
	`TRANSFERSTATUS` int NOT NULL,
	`BOMUNITSYMBOL`  STRING NOT NULL,
	`ITEMNUMBER`  STRING NOT NULL,
	`PRODUCTGROUPID`  STRING NOT NULL,
	`PRODUCTNUMBER`  STRING NOT NULL,
	`BUYERGROUPID`  STRING NOT NULL,
	`INVENTORYUNITSYMBOL`  STRING NOT NULL,
	`ORIGINCOUNTRYREGIONID`  STRING NOT NULL,
	`PRIMARYVENDORACCOUNTNUMBER`  STRING NOT NULL,
	`REVENUEABCCODE` int NOT NULL,
	`SALESUNITSYMBOL`  STRING NOT NULL,
	`PRODUCTCREATEDDATETIME` TIMESTAMP NOT NULL,
	`COMPANY`  STRING NOT NULL,
	`PURCHASEUNITSYMBOL`  STRING NOT NULL,
	`PRODUCTRECID` bigint NOT NULL,
	`PHYSICALDIMENSIONGROUPID`  STRING NOT NULL,
	`INTRASTATCOMMODITYCODE`  STRING NOT NULL,
	`PARTITION`  STRING NOT NULL,
	`DATAAREAID`  STRING NOT NULL,
	`SYNCSTARTDATETIME` TIMESTAMP NOT NULL,
 CONSTRAINT `PK_SMRBIEcoResReleasedProductStaging` PRIMARY KEY CLUSTERED 
(
	`EXECUTIONID` ASC,
	`ITEMNUMBER` ASC,
	`DATAAREAID` ASC,
	`PARTITION` ASC
)WITH(STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
;
