/****** Object:  Table [dbo].[SMRBIProdJournalProdStaging]    Script Date: 03/03/2026 16:26:09 ******/



CREATE OR REPLACE TABLE `dbo`.`SMRBIProdJournalProdStaging`(
	`DEFINITIONGROUP`  STRING NOT NULL,
	`EXECUTIONID`  STRING NOT NULL,
	`ISSELECTED` int NOT NULL,
	`TRANSFERSTATUS` int NOT NULL,
	`COMPANY`  STRING NOT NULL,
	`INVENTDIMID`  STRING NOT NULL,
	`INVENTTRANSID`  STRING NOT NULL,
	`ITEMID`  STRING NOT NULL,
	`JOURNALID`  STRING NOT NULL,
	`LINENUM`  DECIMAL(32,16) NOT NULL,
	`PRODFINISHED` int NOT NULL,
	`PRODID`  STRING NOT NULL,
	`QTYGOOD`  DECIMAL(32,6) NOT NULL,
	`PRODJOURNALPRODRECID` bigint NOT NULL,
	`TRANSDATE` TIMESTAMP NOT NULL,
	`PARTITION`  STRING NOT NULL,
	`DATAAREAID`  STRING NOT NULL,
	`SYNCSTARTDATETIME` TIMESTAMP NOT NULL,
 CONSTRAINT `PK_SMRBIProdJournalProdStaging` PRIMARY KEY CLUSTERED 
(
	`EXECUTIONID` ASC,
	`PRODJOURNALPRODRECID` ASC,
	`DATAAREAID` ASC,
	`PARTITION` ASC
)WITH(STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
;
