/****** Object:  Table [dbo].[SMRBISystemUserStaging]    Script Date: 03/03/2026 16:26:08 ******/



CREATE OR REPLACE TABLE `dbo`.`SMRBISystemUserStaging`(
	`DEFINITIONGROUP`  STRING NOT NULL,
	`EXECUTIONID`  STRING NOT NULL,
	`ISSELECTED` int NOT NULL,
	`TRANSFERSTATUS` int NOT NULL,
	`USERID`  STRING NOT NULL,
	`USERNAME`  STRING NOT NULL,
	`COMPANY`  STRING NOT NULL,
	`NETWORKDOMAIN`  STRING NOT NULL,
	`ALIAS`  STRING NOT NULL,
	`PARTITION`  STRING NOT NULL,
	`SYNCSTARTDATETIME` TIMESTAMP NOT NULL,
 CONSTRAINT `PK_SMRBISystemUserStaging` PRIMARY KEY CLUSTERED 
(
	`EXECUTIONID` ASC,
	`USERID` ASC,
	`PARTITION` ASC
)WITH(STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
;
