/****** Object:  Table [dbo].[SMRBIProjSortingStaging]    Script Date: 03/03/2026 16:26:09 ******/



CREATE OR REPLACE TABLE `dbo`.`SMRBIProjSortingStaging`(
	`DEFINITIONGROUP`  STRING NOT NULL,
	`EXECUTIONID`  STRING NOT NULL,
	`ISSELECTED` int NOT NULL,
	`TRANSFERSTATUS` int NOT NULL,
	`DESCRIPTION`  STRING NOT NULL,
	`SORTCODE` int NOT NULL,
	`SORTINGID`  STRING NOT NULL,
	`PARTITION`  STRING NOT NULL,
	`DATAAREAID`  STRING NOT NULL,
	`SYNCSTARTDATETIME` TIMESTAMP NOT NULL,
 CONSTRAINT `PK_SMRBIProjSortingStaging` PRIMARY KEY CLUSTERED 
(
	`EXECUTIONID` ASC,
	`SORTCODE` ASC,
	`SORTINGID` ASC,
	`DATAAREAID` ASC,
	`PARTITION` ASC
)WITH(STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
;
