/****** Object:  Table [dbo].[SMRBIForecastDemandForecastStaging]    Script Date: 03/03/2026 16:26:09 ******/



CREATE OR REPLACE TABLE `dbo`.`SMRBIForecastDemandForecastStaging`(
	`DEFINITIONGROUP`  STRING NOT NULL,
	`EXECUTIONID`  STRING NOT NULL,
	`ISSELECTED` int NOT NULL,
	`TRANSFERSTATUS` int NOT NULL,
	`EXPANDID` bigint NOT NULL,
	`FORECASTMODELID`  STRING NOT NULL,
	`FORECASTSTARTDATE` TIMESTAMP NOT NULL,
	`FORECASTEDQUANTITY`  DECIMAL(32,6) NOT NULL,
	`FORECASTEDUNITPRICE`  DECIMAL(32,6) NOT NULL,
	`FORECASTEDREVENUE`  DECIMAL(32,6) NOT NULL,
	`QUANTITYUNITSYMBOL`  STRING NOT NULL,
	`PRICINGCURRENCYCODE`  STRING NOT NULL,
	`CUSTOMERACCOUNTNUMBER`  STRING NOT NULL,
	`CUSTOMERGROUPID`  STRING NOT NULL,
	`ITEMNUMBER`  STRING NOT NULL,
	`KEYID`  STRING NOT NULL,
	`STARTDATE` TIMESTAMP NOT NULL,
	`INVENTDIMID`  STRING NOT NULL,
	`COMMENT_`  STRING NOT NULL,
	`ITEMGROUPID`  STRING NOT NULL,
	`FORECASTDEMANDFORECASTDIMENSION` bigint NOT NULL,
	`PARTITION`  STRING NOT NULL,
	`DATAAREAID`  STRING NOT NULL,
	`SYNCSTARTDATETIME` TIMESTAMP NOT NULL,
	`RECID` bigint NOT NULL,
 CONSTRAINT `PK_SMRBIForecastDemandForecastStaging` PRIMARY KEY CLUSTERED 
(
	`EXECUTIONID` ASC,
	`EXPANDID` ASC,
	`FORECASTMODELID` ASC,
	`FORECASTSTARTDATE` ASC,
	`FORECASTEDQUANTITY` ASC,
	`FORECASTEDUNITPRICE` ASC,
	`FORECASTEDREVENUE` ASC,
	`QUANTITYUNITSYMBOL` ASC,
	`PRICINGCURRENCYCODE` ASC,
	`CUSTOMERACCOUNTNUMBER` ASC,
	`CUSTOMERGROUPID` ASC,
	`ITEMNUMBER` ASC,
	`KEYID` ASC,
	`STARTDATE` ASC,
	`INVENTDIMID` ASC,
	`COMMENT_` ASC,
	`ITEMGROUPID` ASC,
	`DATAAREAID` ASC,
	`PARTITION` ASC
)WITH(STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
;
