/****** Object:  Table [dbo].[SMRBIExchangeRateStaging]    Script Date: 03/03/2026 16:26:08 ******/



CREATE OR REPLACE TABLE `dbo`.`SMRBIExchangeRateStaging`(
	`DEFINITIONGROUP`  STRING NOT NULL,
	`EXECUTIONID`  STRING NOT NULL,
	`ISSELECTED` int NOT NULL,
	`TRANSFERSTATUS` int NOT NULL,
	`STARTDATE` TIMESTAMP NOT NULL,
	`ENDDATE` TIMESTAMP NOT NULL,
	`FROMCURRENCY`  STRING NOT NULL,
	`TOCURRENCY`  STRING NOT NULL,
	`RATETYPEDESCRIPTION`  STRING NOT NULL,
	`RATETYPENAME`  STRING NOT NULL,
	`RATE`  DECIMAL(32,16) NOT NULL,
	`EXCHANGERATERECID` bigint NOT NULL,
	`EXCHANGERATE`  DECIMAL(32,16) NOT NULL,
	`PARTITION`  STRING NOT NULL,
	`SYNCSTARTDATETIME` TIMESTAMP NOT NULL,
	`RECID` bigint NOT NULL,
 CONSTRAINT `PK_SMRBIExchangeRateStaging` PRIMARY KEY CLUSTERED 
(
	`EXECUTIONID` ASC,
	`STARTDATE` ASC,
	`FROMCURRENCY` ASC,
	`TOCURRENCY` ASC,
	`RATETYPENAME` ASC,
	`PARTITION` ASC
)WITH(STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
;
