/****** Object:  Table [dbo].[SMRBIUnitOfMeasureStaging]    Script Date: 03/03/2026 16:26:09 ******/



CREATE OR REPLACE TABLE `dbo`.`SMRBIUnitOfMeasureStaging`(
	`DEFINITIONGROUP`  STRING NOT NULL,
	`EXECUTIONID`  STRING NOT NULL,
	`ISSELECTED` int NOT NULL,
	`TRANSFERSTATUS` int NOT NULL,
	`DECIMALPRECISION` int NOT NULL,
	`UNITSYMBOL`  STRING NOT NULL,
	`SYSTEMOFUNITS` int NOT NULL,
	`UNITCLASS` int NOT NULL,
	`UNITOFMEASURERECID` bigint NOT NULL,
	`PARTITION`  STRING NOT NULL,
	`SYNCSTARTDATETIME` TIMESTAMP NOT NULL,
	`RECID` bigint NOT NULL,
 CONSTRAINT `PK_SMRBIUnitOfMeasureStaging` PRIMARY KEY CLUSTERED 
(
	`EXECUTIONID` ASC,
	`UNITSYMBOL` ASC,
	`PARTITION` ASC
)WITH(STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
;
