/****** Object:  Table [dbo].[SMRBIsmmActivityParentLinkTableStaging]    Script Date: 03/03/2026 16:26:08 ******/



CREATE OR REPLACE TABLE `dbo`.`SMRBIsmmActivityParentLinkTableStaging`(
	`DEFINITIONGROUP`  STRING NOT NULL,
	`EXECUTIONID`  STRING NOT NULL,
	`ISSELECTED` int NOT NULL,
	`TRANSFERSTATUS` int NOT NULL,
	`ACTIVITYNUMBER`  STRING NOT NULL,
	`COMPANY`  STRING NOT NULL,
	`PARENTTYPE` int NOT NULL,
	`PRIMARYLINK` int NOT NULL,
	`SMMACTIVITYPARENTLINKTABLERECID` bigint NOT NULL,
	`SMMACTIVITYPARENTLINKTABLERECVERSION` int NOT NULL,
	`REFRECID` bigint NOT NULL,
	`REFTABLEID` int NOT NULL,
	`PARTITION`  STRING NOT NULL,
	`DATAAREAID`  STRING NOT NULL,
	`SYNCSTARTDATETIME` TIMESTAMP NOT NULL,
	`RECID` bigint NOT NULL
)
;
