/****** Object:  Table [dbo].[SMRBIPriceDiscTableStaging]    Script Date: 03/03/2026 16:26:08 ******/



CREATE OR REPLACE TABLE `dbo`.`SMRBIPriceDiscTableStaging`(
	`DEFINITIONGROUP`  STRING NOT NULL,
	`EXECUTIONID`  STRING NOT NULL,
	`ISSELECTED` int NOT NULL,
	`TRANSFERSTATUS` int NOT NULL,
	`ACCOUNTRELATION`  STRING NOT NULL,
	`AMOUNT`  DECIMAL(32,6) NOT NULL,
	`CURRENCY`  STRING NOT NULL,
	`COMPANY`  STRING NOT NULL,
	`FROMDATE` TIMESTAMP NOT NULL,
	`ITEMRELATION`  STRING NOT NULL,
	`PRICEDISCTABLEMODIFIEDDATETIME` TIMESTAMP NOT NULL,
	`ORIGINALPRICEDISCADMTRANSRECID` bigint NOT NULL,
	`PRICEDISCTABLEPARTITION` bigint NOT NULL,
	`PDSCALCULATIONID`  STRING NOT NULL,
	`PRICEUNIT`  DECIMAL(32,12) NOT NULL,
	`QUANTITYAMOUNTFROM`  DECIMAL(32,6) NOT NULL,
	`QUANTITYAMOUNTTO`  DECIMAL(32,6) NOT NULL,
	`PRICEDISCTABLERECID` bigint NOT NULL,
	`TODATE` TIMESTAMP NOT NULL,
	`UNITID`  STRING NOT NULL,
	`MODULE` int NOT NULL,
	`CONFIGID`  STRING NOT NULL,
	`INVENTCOLORID`  STRING NOT NULL,
	`INVENTSIZEID`  STRING NOT NULL,
	`PARTITION`  STRING NOT NULL,
	`DATAAREAID`  STRING NOT NULL,
	`SYNCSTARTDATETIME` TIMESTAMP NOT NULL,
	`RECID` bigint NOT NULL,
 CONSTRAINT `PK_SMRBIPriceDiscTableStaging` PRIMARY KEY CLUSTERED 
(
	`EXECUTIONID` ASC,
	`PRICEDISCTABLERECID` ASC,
	`DATAAREAID` ASC,
	`PARTITION` ASC
)WITH(STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
;
