/****** Object:  Table [dbo].[SMRBIPurchPurchaseOrderLineStaging]    Script Date: 03/03/2026 16:26:08 ******/



CREATE OR REPLACE TABLE `dbo`.`SMRBIPurchPurchaseOrderLineStaging`(
	`DEFINITIONGROUP`  STRING NOT NULL,
	`EXECUTIONID`  STRING NOT NULL,
	`ISSELECTED` int NOT NULL,
	`TRANSFERSTATUS` int NOT NULL,
	`PURCHASEORDERLINESTATUS` int NOT NULL,
	`CONFIRMEDDELIVERYDATE` TIMESTAMP NOT NULL,
	`REQUESTEDDELIVERYDATE` TIMESTAMP NOT NULL,
	`LINEAMOUNT`  DECIMAL(32,6) NOT NULL,
	`LINENUMBER` bigint NOT NULL,
	`PURCHASEPRICEQUANTITY`  DECIMAL(32,12) NOT NULL,
	`PURCHASEORDERNUMBER`  STRING NOT NULL,
	`PURCHASEPRICE`  DECIMAL(32,6) NOT NULL,
	`ORDEREDPURCHASEQUANTITY`  DECIMAL(32,6) NOT NULL,
	`PURCHASEUNITSYMBOL`  STRING NOT NULL,
	`CURRENCYCODE`  STRING NOT NULL,
	`INVENTDIMID`  STRING NOT NULL,
	`INVENTREFTRANSID`  STRING NOT NULL,
	`INVENTTRANSID`  STRING NOT NULL,
	`REMAINPURCHPHYSICAL`  DECIMAL(32,6) NOT NULL,
	`COMPANY`  STRING NOT NULL,
	`PURCHLINECREATEDDATETIME` TIMESTAMP NOT NULL,
	`PURCHLINERECID` bigint NOT NULL,
	`PRICEUNIT`  DECIMAL(32,12) NOT NULL,
	`LINEDISCOUNTPERCENTAGE`  DECIMAL(32,6) NOT NULL,
	`LINEDISCOUNTAMOUNT`  DECIMAL(32,6) NOT NULL,
	`ITEMNUMBER`  STRING NOT NULL,
	`TAXITEMGROUP`  STRING NOT NULL,
	`TAXGROUP`  STRING NOT NULL,
	`NAME`  STRING NOT NULL,
	`PARTITION`  STRING NOT NULL,
	`DATAAREAID`  STRING NOT NULL,
	`SYNCSTARTDATETIME` TIMESTAMP NOT NULL,
 CONSTRAINT `PK_SMRBIPurchPurchaseOrderLineStaging` PRIMARY KEY CLUSTERED 
(
	`EXECUTIONID` ASC,
	`LINENUMBER` ASC,
	`PURCHASEORDERNUMBER` ASC,
	`DATAAREAID` ASC,
	`PARTITION` ASC
)WITH(STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
;
