/****** Object:  Table [dbo].[SMRBIInventSettlementStaging]    Script Date: 03/03/2026 16:26:08 ******/



CREATE OR REPLACE TABLE `dbo`.`SMRBIInventSettlementStaging`(
	`DEFINITIONGROUP`  STRING NOT NULL,
	`EXECUTIONID`  STRING NOT NULL,
	`ISSELECTED` int NOT NULL,
	`TRANSFERSTATUS` int NOT NULL,
	`COMPANY`  STRING NOT NULL,
	`QTYSETTLED`  DECIMAL(32,16) NOT NULL,
	`INVENTSETTLEMENTRECID` bigint NOT NULL,
	`SETTLETRANSID`  STRING NOT NULL,
	`TRANSRECID` bigint NOT NULL,
	`PARTITION`  STRING NOT NULL,
	`DATAAREAID`  STRING NOT NULL,
	`SYNCSTARTDATETIME` TIMESTAMP NOT NULL,
 CONSTRAINT `PK_SMRBIInventSettlementStaging` PRIMARY KEY CLUSTERED 
(
	`EXECUTIONID` ASC,
	`INVENTSETTLEMENTRECID` ASC,
	`DATAAREAID` ASC,
	`PARTITION` ASC
)WITH(STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
;
