/****** Object:  Table [dbo].[SMRBIWorkCalendarDateLineStaging]    Script Date: 03/03/2026 16:26:09 ******/



CREATE OR REPLACE TABLE `dbo`.`SMRBIWorkCalendarDateLineStaging`(
	`DEFINITIONGROUP`  STRING NOT NULL,
	`EXECUTIONID`  STRING NOT NULL,
	`ISSELECTED` int NOT NULL,
	`TRANSFERSTATUS` int NOT NULL,
	`CALENDARID`  STRING NOT NULL,
	`EFFECTIVITY`  DECIMAL(32,6) NOT NULL,
	`FROMTIME` int NOT NULL,
	`PROPERTYID`  STRING NOT NULL,
	`TOTIME` int NOT NULL,
	`TRANSDATE` TIMESTAMP NOT NULL,
	`PARTITION`  STRING NOT NULL,
	`DATAAREAID`  STRING NOT NULL,
	`SYNCSTARTDATETIME` TIMESTAMP NOT NULL,
	`RECID` bigint NOT NULL,
 CONSTRAINT `PK_SMRBIWorkCalendarDateLineStaging` PRIMARY KEY CLUSTERED 
(
	`EXECUTIONID` ASC,
	`CALENDARID` ASC,
	`FROMTIME` ASC,
	`TRANSDATE` ASC,
	`DATAAREAID` ASC,
	`PARTITION` ASC
)WITH(STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
;
