/****** Object:  Table [dbo].[SMRBIEcoResReleasedProductVariantStaging]    Script Date: 03/03/2026 16:26:09 ******/



CREATE OR REPLACE TABLE `dbo`.`SMRBIEcoResReleasedProductVariantStaging`(
	`DEFINITIONGROUP`  STRING NOT NULL,
	`EXECUTIONID`  STRING NOT NULL,
	`ISSELECTED` int NOT NULL,
	`TRANSFERSTATUS` int NOT NULL,
	`ITEMNUMBER`  STRING NOT NULL,
	`PRODUCTVARIANTNUMBER`  STRING NOT NULL,
	`INVENTDIMID`  STRING NOT NULL,
	`RETAILVARIANTID`  STRING NOT NULL,
	`DISTINCTPRODUCTVARIANT` bigint NOT NULL,
	`COMPANY`  STRING NOT NULL,
	`VARIANTCREATEDDATETIME` TIMESTAMP NOT NULL,
	`ECORESRELEASEDPRODUCTVARIANTRECID` bigint NOT NULL,
	`PARTITION`  STRING NOT NULL,
	`DATAAREAID`  STRING NOT NULL,
	`SYNCSTARTDATETIME` TIMESTAMP NOT NULL,
 CONSTRAINT `PK_SMRBIEcoResReleasedProductVariantStaging` PRIMARY KEY CLUSTERED 
(
	`EXECUTIONID` ASC,
	`PRODUCTVARIANTNUMBER` ASC,
	`DATAAREAID` ASC,
	`PARTITION` ASC
)WITH(STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
;
