/****** Object:  Table [dbo].[SMRBIHcmWorkerStaging]    Script Date: 03/03/2026 16:26:08 ******/



CREATE OR REPLACE TABLE `dbo`.`SMRBIHcmWorkerStaging`(
	`DEFINITIONGROUP`  STRING NOT NULL,
	`EXECUTIONID`  STRING NOT NULL,
	`ISSELECTED` int NOT NULL,
	`TRANSFERSTATUS` int NOT NULL,
	`PERSONNELNUMBER`  STRING NOT NULL,
	`NAME`  STRING NOT NULL,
	`HCMWORKERRECID` bigint NOT NULL,
	`VALIDTO` TIMESTAMP NOT NULL,
	`VALIDFROM` TIMESTAMP NOT NULL,
	`PARTITION`  STRING NOT NULL,
	`SYNCSTARTDATETIME` TIMESTAMP NOT NULL,
	`RECID` bigint NOT NULL,
 CONSTRAINT `PK_SMRBIHcmWorkerStaging` PRIMARY KEY CLUSTERED 
(
	`EXECUTIONID` ASC,
	`PERSONNELNUMBER` ASC,
	`PARTITION` ASC
)WITH(STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
;
