/****** Object:  Table [dbo].[SMRBIProjProjectLinePropertyStaging]    Script Date: 03/03/2026 16:26:09 ******/



CREATE OR REPLACE TABLE `dbo`.`SMRBIProjProjectLinePropertyStaging`(
	`DEFINITIONGROUP`  STRING NOT NULL,
	`EXECUTIONID`  STRING NOT NULL,
	`ISSELECTED` int NOT NULL,
	`TRANSFERSTATUS` int NOT NULL,
	`COSTPERCENTAGE`  DECIMAL(32,6) NOT NULL,
	`COMPANY`  STRING NOT NULL,
	`LINEPROPERTYID`  STRING NOT NULL,
	`NAME`  STRING NOT NULL,
	`SALESPERCENTAGE`  DECIMAL(32,6) NOT NULL,
	`PARTITION`  STRING NOT NULL,
	`DATAAREAID`  STRING NOT NULL,
	`SYNCSTARTDATETIME` TIMESTAMP NOT NULL,
 CONSTRAINT `PK_SMRBIProjProjectLinePropertyStaging` PRIMARY KEY CLUSTERED 
(
	`EXECUTIONID` ASC,
	`LINEPROPERTYID` ASC,
	`DATAAREAID` ASC,
	`PARTITION` ASC
)WITH(STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
;
