/****** Object:  Table [dbo].[SMRBIRouteVersionStaging]    Script Date: 03/03/2026 16:26:09 ******/



CREATE OR REPLACE TABLE `dbo`.`SMRBIRouteVersionStaging`(
	`DEFINITIONGROUP`  STRING NOT NULL,
	`EXECUTIONID`  STRING NOT NULL,
	`ISSELECTED` int NOT NULL,
	`TRANSFERSTATUS` int NOT NULL,
	`ITEMNUMBER`  STRING NOT NULL,
	`ROUTEID`  STRING NOT NULL,
	`VALIDFROMDATE` TIMESTAMP NOT NULL,
	`VALIDTODATE` TIMESTAMP NOT NULL,
	`COMPANY`  STRING NOT NULL,
	`VALIDFROMQUANTITY`  DECIMAL(32,6) NOT NULL,
	`PARTITION`  STRING NOT NULL,
	`DATAAREAID`  STRING NOT NULL,
	`SYNCSTARTDATETIME` TIMESTAMP NOT NULL,
	`RECID` bigint NOT NULL,
 CONSTRAINT `PK_SMRBIRouteVersionStaging` PRIMARY KEY CLUSTERED 
(
	`EXECUTIONID` ASC,
	`ITEMNUMBER` ASC,
	`ROUTEID` ASC,
	`VALIDFROMDATE` ASC,
	`VALIDTODATE` ASC,
	`COMPANY` ASC,
	`VALIDFROMQUANTITY` ASC,
	`DATAAREAID` ASC,
	`PARTITION` ASC
)WITH(STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
;
