/****** Object:  Table [dbo].[SMRBIProjTransPostingStaging]    Script Date: 03/03/2026 16:26:09 ******/



CREATE OR REPLACE TABLE `dbo`.`SMRBIProjTransPostingStaging`(
	`DEFINITIONGROUP`  STRING NOT NULL,
	`EXECUTIONID`  STRING NOT NULL,
	`ISSELECTED` int NOT NULL,
	`TRANSFERSTATUS` int NOT NULL,
	`ACTIVITYNUMBER`  STRING NOT NULL,
	`AMOUNTMST`  DECIMAL(32,6) NOT NULL,
	`COSTSALES` int NOT NULL,
	`CATEGORYID`  STRING NOT NULL,
	`DEFAULTDIMENSION` bigint NOT NULL,
	`EMPLITEMID`  STRING NOT NULL,
	`INVENTTRANSID`  STRING NOT NULL,
	`LEDGERDIMENSION` bigint NOT NULL,
	`LEDGERORIGIN` int NOT NULL,
	`LEDGERTRANSDATE` TIMESTAMP NOT NULL,
	`PAYMENTDATE` TIMESTAMP NOT NULL,
	`PAYMENTSTATUS` int NOT NULL,
	`POSTINGTYPE` int NOT NULL,
	`PROJADJUSTREFID`  STRING NOT NULL,
	`PROJFUNDINGSOURCE` bigint NOT NULL,
	`PROJID`  STRING NOT NULL,
	`PROJTRANSDATE` TIMESTAMP NOT NULL,
	`PROJTRANSTYPE` int NOT NULL,
	`PROJTYPE` int NOT NULL,
	`QTY`  DECIMAL(32,6) NOT NULL,
	`RESOURCE_` bigint NOT NULL,
	`RESOURCECATEGORY` bigint NOT NULL,
	`RESOURCELEGALENTITY` bigint NOT NULL,
	`SUBSCRIPTIONID`  STRING NOT NULL,
	`TRANSACTIONORIGIN` int NOT NULL,
	`TRANSID`  STRING NOT NULL,
	`VOUCHER`  STRING NOT NULL,
	`WORKER` bigint NOT NULL,
	`WORKERLEGALENTITY` bigint NOT NULL,
	`PARTITION`  STRING NOT NULL,
	`DATAAREAID`  STRING NOT NULL,
	`SYNCSTARTDATETIME` TIMESTAMP NOT NULL,
	`RECID` bigint NOT NULL,
 CONSTRAINT `PK_SMRBIProjTransPostingStaging` PRIMARY KEY CLUSTERED 
(
	`EXECUTIONID` ASC,
	`TRANSID` ASC,
	`DATAAREAID` ASC,
	`PARTITION` ASC
)WITH(STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
;
