/****** Object:  Table [dbo].[SMRBIProjectStaging]    Script Date: 03/03/2026 16:26:09 ******/



CREATE OR REPLACE TABLE `dbo`.`SMRBIProjectStaging`(
	`DEFINITIONGROUP`  STRING NOT NULL,
	`EXECUTIONID`  STRING NOT NULL,
	`ISSELECTED` int NOT NULL,
	`TRANSFERSTATUS` int NOT NULL,
	`PROJECTID`  STRING NOT NULL,
	`CUSTOMERACCOUNT`  STRING NOT NULL,
	`ACTUALENDDATE` TIMESTAMP NOT NULL,
	`PROJECTNAME`  STRING NOT NULL,
	`PROJECTGROUPID`  STRING NOT NULL,
	`ACTUALSTARTDATE` TIMESTAMP NOT NULL,
	`COMPANY`  STRING NOT NULL,
	`PARTITION`  STRING NOT NULL,
	`DATAAREAID`  STRING NOT NULL,
	`SYNCSTARTDATETIME` TIMESTAMP NOT NULL,
 CONSTRAINT `PK_SMRBIProjectStaging` PRIMARY KEY CLUSTERED 
(
	`EXECUTIONID` ASC,
	`PROJECTID` ASC,
	`DATAAREAID` ASC,
	`PARTITION` ASC
)WITH(STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
;
