/****** Object:  Table [dbo].[SMRBIBOMBillOfMaterialsHeaderStaging]    Script Date: 03/03/2026 16:26:09 ******/



CREATE OR REPLACE TABLE `dbo`.`SMRBIBOMBillOfMaterialsHeaderStaging`(
	`DEFINITIONGROUP`  STRING NOT NULL,
	`EXECUTIONID`  STRING NOT NULL,
	`ISSELECTED` int NOT NULL,
	`TRANSFERSTATUS` int NOT NULL,
	`BOMID`  STRING NOT NULL,
	`BOMNAME`  STRING NOT NULL,
	`COMPANY`  STRING NOT NULL,
	`PRODUCTGROUPID`  STRING NOT NULL,
	`PARTITION`  STRING NOT NULL,
	`DATAAREAID`  STRING NOT NULL,
	`SYNCSTARTDATETIME` TIMESTAMP NOT NULL,
 CONSTRAINT `PK_SMRBIBOMBillOfMaterialsHeaderStaging` PRIMARY KEY CLUSTERED 
(
	`EXECUTIONID` ASC,
	`BOMID` ASC,
	`DATAAREAID` ASC,
	`PARTITION` ASC
)WITH(STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
;
