/****** Object:  Table [dbo].[SMRBIMainAccountStaging]    Script Date: 03/03/2026 16:26:09 ******/



CREATE OR REPLACE TABLE `dbo`.`SMRBIMainAccountStaging`(
	`DEFINITIONGROUP`  STRING NOT NULL,
	`EXECUTIONID`  STRING NOT NULL,
	`ISSELECTED` int NOT NULL,
	`TRANSFERSTATUS` int NOT NULL,
	`CHARTOFACCOUNTSRECID` bigint NOT NULL,
	`MAINACCOUNTCATEGORY`  STRING NOT NULL,
	`MAINACCOUNTID`  STRING NOT NULL,
	`NAME`  STRING NOT NULL,
	`MAINACCOUNTTYPE` int NOT NULL,
	`MAINACCOUNTRECID` bigint NOT NULL,
	`PARTITION`  STRING NOT NULL,
	`SYNCSTARTDATETIME` TIMESTAMP NOT NULL,
	`RECID` bigint NOT NULL,
 CONSTRAINT `PK_SMRBIMainAccountStaging` PRIMARY KEY CLUSTERED 
(
	`EXECUTIONID` ASC,
	`CHARTOFACCOUNTSRECID` ASC,
	`MAINACCOUNTCATEGORY` ASC,
	`MAINACCOUNTID` ASC,
	`NAME` ASC,
	`MAINACCOUNTTYPE` ASC,
	`MAINACCOUNTRECID` ASC,
	`PARTITION` ASC
)WITH(STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
;
