/****** Object:  Table [dbo].[SMRBICustomerSettlementStaging]    Script Date: 03/03/2026 16:26:09 ******/



CREATE OR REPLACE TABLE `dbo`.`SMRBICustomerSettlementStaging`(
	`DEFINITIONGROUP`  STRING NOT NULL,
	`EXECUTIONID`  STRING NOT NULL,
	`ISSELECTED` int NOT NULL,
	`TRANSFERSTATUS` int NOT NULL,
	`SETTLEAMOUNTMST`  DECIMAL(32,6) NOT NULL,
	`SETTLEAMOUNTCUR`  DECIMAL(32,6) NOT NULL,
	`ACCOUNTNUM`  STRING NOT NULL,
	`EXCHADJUSTMENT`  DECIMAL(32,6) NOT NULL,
	`TRANSCOMPANY`  STRING NOT NULL,
	`TRANSDATE` TIMESTAMP NOT NULL,
	`TRANSRECID` bigint NOT NULL,
	`PARTITION`  STRING NOT NULL,
	`SYNCSTARTDATETIME` TIMESTAMP NOT NULL,
	`RECID` bigint NOT NULL,
 CONSTRAINT `PK_SMRBICustomerSettlementStaging` PRIMARY KEY CLUSTERED 
(
	`EXECUTIONID` ASC,
	`RECID` ASC,
	`PARTITION` ASC
)WITH(STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
;
