/****** Object:  Table [dbo].[DataManagementExecutionJobDetailStaging]    Script Date: 03/03/2026 16:26:08 ******/



CREATE OR REPLACE TABLE `dbo`.`DataManagementExecutionJobDetailStaging`(
	`DEFINITIONGROUP`  STRING NOT NULL,
	`EXECUTIONID`  STRING NOT NULL,
	`ISSELECTED` int NOT NULL,
	`TRANSFERSTATUS` int NOT NULL,
	`DEFINITIONGROUPID`  STRING NOT NULL,
	`ENTITYNAME`  STRING NOT NULL,
	`JOBID`  STRING NOT NULL,
	`STAGINGENDDATETIME` TIMESTAMP NOT NULL,
	`EXCELSHEETNAME`  STRING NOT NULL,
	`EXECUTETARGETSTEP` int NOT NULL,
	`FIRSTROWISHEADER` int NOT NULL,
	`FILEPATH`  STRING NOT NULL,
	`IGNOREERROR` int NOT NULL,
	`STAGINGRECORDSTOBEPROCESSEDCOUNT` int NOT NULL,
	`PARALLELTASKCOUNT` int NOT NULL,
	`STAGINGRECORDSCREATEDCOUNT` int NOT NULL,
	`TARGETRECORDSCREATEDCOUNT` int NOT NULL,
	`TARGETRECORDSUPDATEDCOUNT` int NOT NULL,
	`CREATEERRORFILE` int NOT NULL,
	`RUNBUSINESSLOGIC` int NOT NULL,
	`RUNBUSINESSVALIDATION` int NOT NULL,
	`SEQUENCENUMBER` int NOT NULL,
	`NUMBEROFROWSTOSKIP` int NOT NULL,
	`SOURCEFORMAT`  STRING NOT NULL,
	`STAGINGSTATUS` int NOT NULL,
	`STAGINGSTARTDATETIME` TIMESTAMP NOT NULL,
	`TARGETSTATUS` int NOT NULL,
	`TARGETENDDATETIME` TIMESTAMP NOT NULL,
	`TARGETSTARTDATETIME` TIMESTAMP NOT NULL,
	`EXECUTIONUNIT` int NOT NULL,
	`LEVELINEXECUTIONUNIT` int NOT NULL,
	`SEQUENCEINLEVEL` int NOT NULL,
	`FAILEXECUTIONUNITONERROR` int NOT NULL,
	`FAILLEVELONERROR` int NOT NULL,
	`PARTITION`  STRING NOT NULL,
	`SYNCSTARTDATETIME` TIMESTAMP NOT NULL,
	`RECID` bigint NOT NULL,
 CONSTRAINT `PK_DataManagementExecutionJobDetailStaging` PRIMARY KEY CLUSTERED 
(
	`EXECUTIONID` ASC,
	`DEFINITIONGROUPID` ASC,
	`ENTITYNAME` ASC,
	`JOBID` ASC,
	`PARTITION` ASC
)WITH(STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
;
