/****** Object:  Table [dbo].[SMRBIWrkCtrActivityRequirementSetStaging]    Script Date: 03/03/2026 16:26:09 ******/



CREATE OR REPLACE TABLE `dbo`.`SMRBIWrkCtrActivityRequirementSetStaging`(
	`DEFINITIONGROUP`  STRING NOT NULL,
	`EXECUTIONID`  STRING NOT NULL,
	`ISSELECTED` int NOT NULL,
	`TRANSFERSTATUS` int NOT NULL,
	`ACTIVITY` bigint NOT NULL,
	`WRKCTRACTIVITYREQUIREMENTSETRECID` bigint NOT NULL,
	`PARTITION`  STRING NOT NULL,
	`SYNCSTARTDATETIME` TIMESTAMP NOT NULL,
	`RECID` bigint NOT NULL,
 CONSTRAINT `PK_SMRBIWrkCtrActivityRequirementSetStaging` PRIMARY KEY CLUSTERED 
(
	`EXECUTIONID` ASC,
	`WRKCTRACTIVITYREQUIREMENTSETRECID` ASC,
	`PARTITION` ASC
)WITH(STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
;
