/****** Object:  Table [dbo].[SMRBIOpResOperationsResourceStaging]    Script Date: 03/03/2026 16:26:08 ******/



CREATE OR REPLACE TABLE `dbo`.`SMRBIOpResOperationsResourceStaging`(
	`DEFINITIONGROUP`  STRING NOT NULL,
	`EXECUTIONID`  STRING NOT NULL,
	`ISSELECTED` int NOT NULL,
	`TRANSFERSTATUS` int NOT NULL,
	`EFFICIENCYPERCENTAGE`  DECIMAL(32,6) NOT NULL,
	`HASFINITESCHEDULINGCAPACITY` int NOT NULL,
	`OPERATIONSRESOURCETYPE` int NOT NULL,
	`ISINDIVIDUALRESOURCE` int NOT NULL,
	`COMPANY`  STRING NOT NULL,
	`ROUTEGROUPID`  STRING NOT NULL,
	`RESOURCEID`  STRING NOT NULL,
	`RESOURCENAME`  STRING NOT NULL,
	`PARTITION`  STRING NOT NULL,
	`DATAAREAID`  STRING NOT NULL,
	`SYNCSTARTDATETIME` TIMESTAMP NOT NULL,
 CONSTRAINT `PK_SMRBIOpResOperationsResourceStaging` PRIMARY KEY CLUSTERED 
(
	`EXECUTIONID` ASC,
	`RESOURCEID` ASC,
	`DATAAREAID` ASC,
	`PARTITION` ASC
)WITH(STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
;
