/****** Object:  Table [dbo].[SMRBIVendReviewCriterionStaging]    Script Date: 03/03/2026 16:26:09 ******/



CREATE OR REPLACE TABLE `dbo`.`SMRBIVendReviewCriterionStaging`(
	`DEFINITIONGROUP`  STRING NOT NULL,
	`EXECUTIONID`  STRING NOT NULL,
	`ISSELECTED` int NOT NULL,
	`TRANSFERSTATUS` int NOT NULL,
	`CRITERIONGROUP` bigint NOT NULL,
	`NAME`  STRING NOT NULL,
	`VENDREVIEWCRITERIONRECID` bigint NOT NULL,
	`PARTITION`  STRING NOT NULL,
	`SYNCSTARTDATETIME` TIMESTAMP NOT NULL,
	`RECID` bigint NOT NULL,
 CONSTRAINT `PK_SMRBIVendReviewCriterionStaging` PRIMARY KEY CLUSTERED 
(
	`EXECUTIONID` ASC,
	`CRITERIONGROUP` ASC,
	`NAME` ASC,
	`PARTITION` ASC
)WITH(STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
;
