/****** Object:  Table [dbo].[SMRBICaseCategoryHierarchyDetailStaging]    Script Date: 03/03/2026 16:26:09 ******/



CREATE OR REPLACE TABLE `dbo`.`SMRBICaseCategoryHierarchyDetailStaging`(
	`DEFINITIONGROUP`  STRING NOT NULL,
	`EXECUTIONID`  STRING NOT NULL,
	`ISSELECTED` int NOT NULL,
	`TRANSFERSTATUS` int NOT NULL,
	`CASECATEGORY`  STRING NOT NULL,
	`CATEGORYTYPE` int NOT NULL,
	`CREATEACTIVITYFORCASE` int NOT NULL,
	`CREATEACTIVITYFORFOLLOWUP` int NOT NULL,
	`COMPANY`  STRING NOT NULL,
	`DEFAULTACTIVITYCATEGORY` int NOT NULL,
	`DEFAULTACTIVITYPHASE`  STRING NOT NULL,
	`DEFAULTACTIVITYPURPOSE`  STRING NOT NULL,
	`DEFAULTACTIVITYTYPE`  STRING NOT NULL,
	`DEFAULTFOLLOWUPCATEGORY` int NOT NULL,
	`DEFAULTFOLLOWUPPHASE`  STRING NOT NULL,
	`DEFAULTFOLLOWUPPURPOSE`  STRING NOT NULL,
	`DEFAULTFOLLOWUPTYPE`  STRING NOT NULL,
	`DEFAULTOWNERWORKER` bigint NOT NULL,
	`DEPARTMENT` bigint NOT NULL,
	`DESCRIPTION`  STRING NOT NULL,
	`EMAILID`  STRING NOT NULL,
	`PARENTRECID` bigint NOT NULL,
	`PROCESS`  STRING NOT NULL,
	`CASECATEGORYHIERARCHYRECID` bigint NOT NULL,
	`CASECATEGORYHIERARCHYRECVERSION` int NOT NULL,
	`SERVICELEVELAGREEMENTID`  STRING NOT NULL,
	`PARTITION`  STRING NOT NULL,
	`DATAAREAID`  STRING NOT NULL,
	`SYNCSTARTDATETIME` TIMESTAMP NOT NULL,
	`RECID` bigint NOT NULL,
 CONSTRAINT `PK_SMRBICaseCategoryHierarchyDetailStaging` PRIMARY KEY CLUSTERED 
(
	`EXECUTIONID` ASC,
	`CASECATEGORY` ASC,
	`CATEGORYTYPE` ASC,
	`DATAAREAID` ASC,
	`PARTITION` ASC
)WITH(STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
;
