/****** Object:  Table [dbo].[SMRBICustomerPriorityClassificationGroupStaging]    Script Date: 03/03/2026 16:26:08 ******/



CREATE OR REPLACE TABLE `dbo`.`SMRBICustomerPriorityClassificationGroupStaging`(
	`DEFINITIONGROUP`  STRING NOT NULL,
	`EXECUTIONID`  STRING NOT NULL,
	`ISSELECTED` int NOT NULL,
	`TRANSFERSTATUS` int NOT NULL,
	`CUSTOMERPRIORITYCLASSIFICATIONGROUPCODE`  STRING NOT NULL,
	`DESCRIPTION`  STRING NOT NULL,
	`COMPANY`  STRING NOT NULL,
	`PARTITION`  STRING NOT NULL,
	`DATAAREAID`  STRING NOT NULL,
	`SYNCSTARTDATETIME` TIMESTAMP NOT NULL,
 CONSTRAINT `PK_SMRBICustomerPriorityClassificationGroupStaging` PRIMARY KEY CLUSTERED 
(
	`EXECUTIONID` ASC,
	`CUSTOMERPRIORITYCLASSIFICATIONGROUPCODE` ASC,
	`DATAAREAID` ASC,
	`PARTITION` ASC
)WITH(STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
;
