/****** Object:  Table [dbo].[SMRBIInventNonConformanceTableStaging]    Script Date: 03/03/2026 16:26:09 ******/



CREATE OR REPLACE TABLE `dbo`.`SMRBIInventNonConformanceTableStaging`(
	`DEFINITIONGROUP`  STRING NOT NULL,
	`EXECUTIONID`  STRING NOT NULL,
	`ISSELECTED` int NOT NULL,
	`TRANSFERSTATUS` int NOT NULL,
	`CUSTACCOUNT`  STRING NOT NULL,
	`INVENTDIMID`  STRING NOT NULL,
	`INVENTNONCONFORMANCEAPPROVAL` int NOT NULL,
	`INVENTNONCONFORMANCEID`  STRING NOT NULL,
	`INVENTNONCONFORMANCETYPE` int NOT NULL,
	`INVENTREFID`  STRING NOT NULL,
	`INVENTTESTPROBLEMTYPEID`  STRING NOT NULL,
	`INVENTTESTQUARANTINETYPE` int NOT NULL,
	`INVENTTRANSIDREF`  STRING NOT NULL,
	`INVENTTRANSTYPE` int NOT NULL,
	`ITEMID`  STRING NOT NULL,
	`NONCONFORMANCEDATE` TIMESTAMP NOT NULL,
	`RUSH` int NOT NULL,
	`UNITID`  STRING NOT NULL,
	`VENDACCOUNT`  STRING NOT NULL,
	`HCMWORKER_PERSONNELNUMBER`  STRING NOT NULL,
	`DEFAULTDIMENSIONDISPLAYVALUE`  STRING NOT NULL,
	`COMPANY`  STRING NOT NULL,
	`TESTDEFECTQTY`  DECIMAL(32,6) NOT NULL,
	`PARTITION`  STRING NOT NULL,
	`DATAAREAID`  STRING NOT NULL,
	`SYNCSTARTDATETIME` TIMESTAMP NOT NULL,
 CONSTRAINT `PK_SMRBIInventNonConformanceTableStaging` PRIMARY KEY CLUSTERED 
(
	`EXECUTIONID` ASC,
	`INVENTNONCONFORMANCEID` ASC,
	`DATAAREAID` ASC,
	`PARTITION` ASC
)WITH(STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
;
