/****** Object:  Table [dbo].[SMRBIWHSPhysicalDimensionGroupDetailStaging]    Script Date: 03/03/2026 16:26:08 ******/



CREATE OR REPLACE TABLE `dbo`.`SMRBIWHSPhysicalDimensionGroupDetailStaging`(
	`DEFINITIONGROUP`  STRING NOT NULL,
	`EXECUTIONID`  STRING NOT NULL,
	`ISSELECTED` int NOT NULL,
	`TRANSFERSTATUS` int NOT NULL,
	`PHYSICALDEPTH`  DECIMAL(32,6) NOT NULL,
	`PHYSICALHEIGHT`  DECIMAL(32,6) NOT NULL,
	`PHYSICALDIMENSIONGROUPID`  STRING NOT NULL,
	`PHYSICALUNITSYMBOL`  STRING NOT NULL,
	`PHYSICALWEIGHT`  DECIMAL(32,12) NOT NULL,
	`PHYSICALWIDTH`  DECIMAL(32,6) NOT NULL,
	`COMPANY`  STRING NOT NULL,
	`PARTITION`  STRING NOT NULL,
	`DATAAREAID`  STRING NOT NULL,
	`SYNCSTARTDATETIME` TIMESTAMP NOT NULL,
	`RECID` bigint NOT NULL,
 CONSTRAINT `PK_SMRBIWHSPhysicalDimensionGroupDetailStaging` PRIMARY KEY CLUSTERED 
(
	`EXECUTIONID` ASC,
	`PHYSICALDIMENSIONGROUPID` ASC,
	`PHYSICALUNITSYMBOL` ASC,
	`DATAAREAID` ASC,
	`PARTITION` ASC
)WITH(STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
;
