/****** Object:  Table [dbo].[SMRBIProdRouteStaging]    Script Date: 03/03/2026 16:26:09 ******/



CREATE OR REPLACE TABLE `dbo`.`SMRBIProdRouteStaging`(
	`DEFINITIONGROUP`  STRING NOT NULL,
	`EXECUTIONID`  STRING NOT NULL,
	`ISSELECTED` int NOT NULL,
	`TRANSFERSTATUS` int NOT NULL,
	`CALCPROC`  DECIMAL(32,6) NOT NULL,
	`CALCSETUP`  DECIMAL(32,6) NOT NULL,
	`COMPANY`  STRING NOT NULL,
	`FROMDATE` TIMESTAMP NOT NULL,
	`OPRID`  STRING NOT NULL,
	`OPRNUM` int NOT NULL,
	`OPRNUMNEXT` int NOT NULL,
	`PRODID`  STRING NOT NULL,
	`ROUTEOPRREFRECID` bigint NOT NULL,
	`TODATE` TIMESTAMP NOT NULL,
	`PARTITION`  STRING NOT NULL,
	`SYNCSTARTDATETIME` TIMESTAMP NOT NULL,
	`RECID` bigint NOT NULL,
 CONSTRAINT `PK_SMRBIProdRouteStaging` PRIMARY KEY CLUSTERED 
(
	`EXECUTIONID` ASC,
	`CALCPROC` ASC,
	`CALCSETUP` ASC,
	`COMPANY` ASC,
	`FROMDATE` ASC,
	`OPRID` ASC,
	`OPRNUM` ASC,
	`OPRNUMNEXT` ASC,
	`PRODID` ASC,
	`ROUTEOPRREFRECID` ASC,
	`TODATE` ASC,
	`PARTITION` ASC
)WITH(STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
;
