/****** Object:  Table [dbo].[SMRBIProjBudgetRevisionLineStaging]    Script Date: 03/03/2026 16:26:09 ******/



CREATE OR REPLACE TABLE `dbo`.`SMRBIProjBudgetRevisionLineStaging`(
	`DEFINITIONGROUP`  STRING NOT NULL,
	`EXECUTIONID`  STRING NOT NULL,
	`ISSELECTED` int NOT NULL,
	`TRANSFERSTATUS` int NOT NULL,
	`NEWTOTALBUDGET`  DECIMAL(32,6) NOT NULL,
	`PREVIOUSAPPROVEDBUDGET`  DECIMAL(32,6) NOT NULL,
	`PROJBUDGETLINE` bigint NOT NULL,
	`PROJBUDGETREVISION` bigint NOT NULL,
	`REVISIONAMOUNT`  DECIMAL(32,6) NOT NULL,
	`PARTITION`  STRING NOT NULL,
	`DATAAREAID`  STRING NOT NULL,
	`SYNCSTARTDATETIME` TIMESTAMP NOT NULL,
	`RECID` bigint NOT NULL,
 CONSTRAINT `PK_SMRBIProjBudgetRevisionLineStaging` PRIMARY KEY CLUSTERED 
(
	`EXECUTIONID` ASC,
	`PROJBUDGETLINE` ASC,
	`PROJBUDGETREVISION` ASC,
	`DATAAREAID` ASC,
	`PARTITION` ASC
)WITH(STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
;
