/****** Object:  Table [dbo].[SMRBIPurchProductApprovedVendorStaging]    Script Date: 03/03/2026 16:26:08 ******/



CREATE OR REPLACE TABLE `dbo`.`SMRBIPurchProductApprovedVendorStaging`(
	`DEFINITIONGROUP`  STRING NOT NULL,
	`EXECUTIONID`  STRING NOT NULL,
	`ISSELECTED` int NOT NULL,
	`TRANSFERSTATUS` int NOT NULL,
	`ITEMNUMBER`  STRING NOT NULL,
	`APPROVEDVENDORACCOUNTNUMBER`  STRING NOT NULL,
	`EFFECTIVEDATE` TIMESTAMP NOT NULL,
	`COMPANY`  STRING NOT NULL,
	`PARTITION`  STRING NOT NULL,
	`DATAAREAID`  STRING NOT NULL,
	`SYNCSTARTDATETIME` TIMESTAMP NOT NULL,
	`RECID` bigint NOT NULL,
 CONSTRAINT `PK_SMRBIPurchProductApprovedVendorStaging` PRIMARY KEY CLUSTERED 
(
	`EXECUTIONID` ASC,
	`ITEMNUMBER` ASC,
	`APPROVEDVENDORACCOUNTNUMBER` ASC,
	`EFFECTIVEDATE` ASC,
	`DATAAREAID` ASC,
	`PARTITION` ASC
)WITH(STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
;
