/****** Object:  Table [dbo].[SMRBICustInvoiceTransStaging]    Script Date: 03/03/2026 16:26:08 ******/



CREATE OR REPLACE TABLE `dbo`.`SMRBICustInvoiceTransStaging`(
	`DEFINITIONGROUP`  STRING NOT NULL,
	`EXECUTIONID`  STRING NOT NULL,
	`ISSELECTED` int NOT NULL,
	`TRANSFERSTATUS` int NOT NULL,
	`CURRENCYCODE`  STRING NOT NULL,
	`COMPANY`  STRING NOT NULL,
	`DLVDATE` TIMESTAMP NOT NULL,
	`INVENTDIMID`  STRING NOT NULL,
	`INVENTQTY`  DECIMAL(32,6) NOT NULL,
	`INVENTTRANSID`  STRING NOT NULL,
	`INVOICEDATE` TIMESTAMP NOT NULL,
	`INVOICEID`  STRING NOT NULL,
	`ITEMID`  STRING NOT NULL,
	`LINEAMOUNT`  DECIMAL(32,6) NOT NULL,
	`LINEAMOUNTMST`  DECIMAL(32,6) NOT NULL,
	`LINEDISC`  DECIMAL(32,6) NOT NULL,
	`LINEHEADER`  STRING NOT NULL,
	`LINENUM`  DECIMAL(32,16) NOT NULL,
	`LINEPERCENT`  DECIMAL(32,6) NOT NULL,
	`ORIGSALESID`  STRING NOT NULL,
	`PRICEUNIT`  DECIMAL(32,12) NOT NULL,
	`QTY`  DECIMAL(32,6) NOT NULL,
	`QTYPHYSICAL`  DECIMAL(32,6) NOT NULL,
	`CUSTINVOICETRANSRECID` bigint NOT NULL,
	`SALESID`  STRING NOT NULL,
	`SALESPRICE`  DECIMAL(32,6) NOT NULL,
	`SALESUNIT`  STRING NOT NULL,
	`TAXWRITECODE`  STRING NOT NULL,
	`DEFAULTDIMENSIONDISPLAYVALUE`  STRING NOT NULL,
	`LEDGERDIMENSIONDISPLAYVALUE`  STRING NOT NULL,
	`CUSTINVOICETRANSDIMENSION` bigint NOT NULL,
	`NAME`  STRING NOT NULL,
	`DISCPERCENT`  DECIMAL(32,6) NOT NULL,
	`DISCAMOUNT`  DECIMAL(32,6) NOT NULL,
	`PARTITION`  STRING NOT NULL,
	`DATAAREAID`  STRING NOT NULL,
	`SYNCSTARTDATETIME` TIMESTAMP NOT NULL,
	`RECID` bigint NOT NULL,
 CONSTRAINT `PK_SMRBICustInvoiceTransStaging` PRIMARY KEY CLUSTERED 
(
	`EXECUTIONID` ASC,
	`CUSTINVOICETRANSRECID` ASC,
	`DATAAREAID` ASC,
	`PARTITION` ASC
)WITH(STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
;
