/****** Object:  Table [dbo].[SMRBIVendSettlementStaging]    Script Date: 03/03/2026 16:26:08 ******/



CREATE OR REPLACE TABLE `dbo`.`SMRBIVendSettlementStaging`(
	`DEFINITIONGROUP`  STRING NOT NULL,
	`EXECUTIONID`  STRING NOT NULL,
	`ISSELECTED` int NOT NULL,
	`TRANSFERSTATUS` int NOT NULL,
	`ACCOUNTNUM`  STRING NOT NULL,
	`EXCHADJUSTMENT`  DECIMAL(32,6) NOT NULL,
	`SETTLEAMOUNTCUR`  DECIMAL(32,6) NOT NULL,
	`SETTLEAMOUNTMST`  DECIMAL(32,6) NOT NULL,
	`TRANSCOMPANY`  STRING NOT NULL,
	`TRANSDATE` TIMESTAMP NOT NULL,
	`TRANSRECID` bigint NOT NULL,
	`VENDSETTLEMENTRECID` bigint NOT NULL,
	`PARTITION`  STRING NOT NULL,
	`DATAAREAID`  STRING NOT NULL,
	`SYNCSTARTDATETIME` TIMESTAMP NOT NULL,
	`RECID` bigint NOT NULL
)
;
