/****** Object:  Table [dbo].[SMRBIPurchRFQReplyLineStaging]    Script Date: 03/03/2026 16:26:08 ******/



CREATE OR REPLACE TABLE `dbo`.`SMRBIPurchRFQReplyLineStaging`(
	`DEFINITIONGROUP`  STRING NOT NULL,
	`EXECUTIONID`  STRING NOT NULL,
	`ISSELECTED` int NOT NULL,
	`TRANSFERSTATUS` int NOT NULL,
	`PURCHRFQCREATEDDATETIME` TIMESTAMP NOT NULL,
	`COMPANY`  STRING NOT NULL,
	`LINEAMOUNT`  DECIMAL(32,6) NOT NULL,
	`LINEPERCENT`  DECIMAL(32,6) NOT NULL,
	`PURCHPRICE`  DECIMAL(32,6) NOT NULL,
	`PURCHQTY`  DECIMAL(32,6) NOT NULL,
	`PURCHUNIT`  STRING NOT NULL,
	`RFQID`  STRING NOT NULL,
	`LINENUM`  DECIMAL(32,16) NOT NULL,
	`PARTITION`  STRING NOT NULL,
	`DATAAREAID`  STRING NOT NULL,
	`SYNCSTARTDATETIME` TIMESTAMP NOT NULL,
 CONSTRAINT `PK_SMRBIPurchRFQReplyLineStaging` PRIMARY KEY CLUSTERED 
(
	`EXECUTIONID` ASC,
	`PURCHRFQCREATEDDATETIME` ASC,
	`COMPANY` ASC,
	`LINEAMOUNT` ASC,
	`LINEPERCENT` ASC,
	`PURCHPRICE` ASC,
	`PURCHQTY` ASC,
	`PURCHUNIT` ASC,
	`RFQID` ASC,
	`DATAAREAID` ASC,
	`PARTITION` ASC
)WITH(STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
;
