/****** Object:  Table [dbo].[SMRBIDirPartyLocationPostalAddressStaging]    Script Date: 03/03/2026 16:26:09 ******/



CREATE OR REPLACE TABLE `dbo`.`SMRBIDirPartyLocationPostalAddressStaging`(
	`DEFINITIONGROUP`  STRING NOT NULL,
	`EXECUTIONID`  STRING NOT NULL,
	`ISSELECTED` int NOT NULL,
	`TRANSFERSTATUS` int NOT NULL,
	`ISPRIMARY` int NOT NULL,
	`PARTYNUMBER`  STRING NOT NULL,
	`ADDRESS`  STRING NOT NULL,
	`CITY`  STRING NOT NULL,
	`COUNTRYREGIONID`  STRING NOT NULL,
	`VALIDTO` TIMESTAMP NOT NULL,
	`ZIPCODE`  STRING NOT NULL,
	`VALIDFROM` TIMESTAMP NOT NULL,
	`PARTITION`  STRING NOT NULL,
	`SYNCSTARTDATETIME` TIMESTAMP NOT NULL,
	`RECID` bigint NOT NULL,
 CONSTRAINT `PK_SMRBIDirPartyLocationPostalAddressStaging` PRIMARY KEY CLUSTERED 
(
	`EXECUTIONID` ASC,
	`ISPRIMARY` ASC,
	`PARTYNUMBER` ASC,
	`ADDRESS` ASC,
	`CITY` ASC,
	`COUNTRYREGIONID` ASC,
	`VALIDTO` ASC,
	`ZIPCODE` ASC,
	`VALIDFROM` ASC,
	`PARTITION` ASC
)WITH(STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
;
