/****** Object:  Table [dbo].[SMRBIEcoResProductAttributeValueStaging]    Script Date: 03/03/2026 16:26:08 ******/



CREATE OR REPLACE TABLE `dbo`.`SMRBIEcoResProductAttributeValueStaging`(
	`DEFINITIONGROUP`  STRING NOT NULL,
	`EXECUTIONID`  STRING NOT NULL,
	`ISSELECTED` int NOT NULL,
	`TRANSFERSTATUS` int NOT NULL,
	`ATTRIBUTENAME`  STRING NOT NULL,
	`ATTRIBUTETYPENAME`  STRING NOT NULL,
	`CURRENCYCODE`  STRING NOT NULL,
	`BOOLEANVALUE` int NOT NULL,
	`DATATYPE` int NOT NULL,
	`DATETIMEVALUE` TIMESTAMP NOT NULL,
	`DECIMALVALUE`  DECIMAL(32,6) NOT NULL,
	`INTEGERVALUE` int NOT NULL,
	`NAME`  STRING NOT NULL,
	`PRODUCTNUMBER`  STRING NOT NULL,
	`TEXTVALUE`  STRING NOT NULL,
	`PARTITION`  STRING NOT NULL,
	`SYNCSTARTDATETIME` TIMESTAMP NOT NULL,
	`RECID` bigint NOT NULL,
 CONSTRAINT `PK_SMRBIEcoResProductAttributeValueStaging` PRIMARY KEY CLUSTERED 
(
	`EXECUTIONID` ASC,
	`ATTRIBUTENAME` ASC,
	`ATTRIBUTETYPENAME` ASC,
	`PRODUCTNUMBER` ASC,
	`PARTITION` ASC
)WITH(STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
;
