/****** Object:  Table [dbo].[SMRBIInventTestCorrectionStaging]    Script Date: 03/03/2026 16:26:09 ******/



CREATE OR REPLACE TABLE `dbo`.`SMRBIInventTestCorrectionStaging`(
	`DEFINITIONGROUP`  STRING NOT NULL,
	`EXECUTIONID`  STRING NOT NULL,
	`ISSELECTED` int NOT NULL,
	`TRANSFERSTATUS` int NOT NULL,
	`CORRECTIONCOMPLETED` int NOT NULL,
	`CORRECTIONCOMPLETEDDATETIME` TIMESTAMP NOT NULL,
	`CORRECTIONRESPONSIBLEWORKER` bigint NOT NULL,
	`DIAGNOSTICTYPEID`  STRING NOT NULL,
	`INVENTNONCONFORMANCEID`  STRING NOT NULL,
	`PLANNEDDATE` TIMESTAMP NOT NULL,
	`PRIORITY` int NOT NULL,
	`REQUESTEDDATE` TIMESTAMP NOT NULL,
	`SHORTTERMCORRECTION` int NOT NULL,
	`COMPANY`  STRING NOT NULL,
	`PARTITION`  STRING NOT NULL,
	`DATAAREAID`  STRING NOT NULL,
	`SYNCSTARTDATETIME` TIMESTAMP NOT NULL,
	`RECID` bigint NOT NULL,
 CONSTRAINT `PK_SMRBIInventTestCorrectionStaging` PRIMARY KEY CLUSTERED 
(
	`EXECUTIONID` ASC,
	`INVENTNONCONFORMANCEID` ASC,
	`DATAAREAID` ASC,
	`PARTITION` ASC
)WITH(STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
;
