/****** Object:  Table [dbo].[SMRBICustInvoiceJourStaging]    Script Date: 03/03/2026 16:26:08 ******/



CREATE OR REPLACE TABLE `dbo`.`SMRBICustInvoiceJourStaging`(
	`DEFINITIONGROUP`  STRING NOT NULL,
	`EXECUTIONID`  STRING NOT NULL,
	`ISSELECTED` int NOT NULL,
	`TRANSFERSTATUS` int NOT NULL,
	`INVOICEID`  STRING NOT NULL,
	`INVOICEDATE` TIMESTAMP NOT NULL,
	`COMPANY`  STRING NOT NULL,
	`DLVMODE`  STRING NOT NULL,
	`DLVTERM`  STRING NOT NULL,
	`INVOICEACCOUNT`  STRING NOT NULL,
	`ORDERACCOUNT`  STRING NOT NULL,
	`PAYMENT`  STRING NOT NULL,
	`CUSTINVOICEJOURRECID` bigint NOT NULL,
	`SALESID`  STRING NOT NULL,
	`INVOICEAMOUNT`  DECIMAL(32,6) NOT NULL,
	`CUSTINVOICEJOURCREATEDDATETIME` TIMESTAMP NOT NULL,
	`SALESBALANCE`  DECIMAL(32,6) NOT NULL,
	`SUMMARKUP`  DECIMAL(32,6) NOT NULL,
	`SUMTAX`  DECIMAL(32,6) NOT NULL,
	`PARTITION`  STRING NOT NULL,
	`YSLELEDGERVOUCHER`  STRING NOT NULL,
	`DATAAREAID`  STRING NOT NULL,
	`SYNCSTARTDATETIME` TIMESTAMP NOT NULL,
	`RECID` bigint NOT NULL,
 CONSTRAINT `PK_SMRBICustInvoiceJourStaging` PRIMARY KEY CLUSTERED 
(
	`EXECUTIONID` ASC,
	`CUSTINVOICEJOURRECID` ASC,
	`DATAAREAID` ASC,
	`PARTITION` ASC
)WITH(STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
;
