/****** Object:  Table [dbo].[SMRBIInventItemPendingPriceStaging]    Script Date: 03/03/2026 16:26:09 ******/



CREATE OR REPLACE TABLE `dbo`.`SMRBIInventItemPendingPriceStaging`(
	`DEFINITIONGROUP`  STRING NOT NULL,
	`EXECUTIONID`  STRING NOT NULL,
	`ISSELECTED` int NOT NULL,
	`TRANSFERSTATUS` int NOT NULL,
	`FROMDATE` TIMESTAMP NOT NULL,
	`ITEMNUMBER`  STRING NOT NULL,
	`PRICE`  DECIMAL(32,16) NOT NULL,
	`PRICETYPE` int NOT NULL,
	`PRICEQUANTITY`  DECIMAL(32,12) NOT NULL,
	`PRICESITEID`  STRING NOT NULL,
	`PRODUCTUNITSYMBOL`  STRING NOT NULL,
	`PRODUCTCONFIGURATIONID`  STRING NOT NULL,
	`PRODUCTCOLORID`  STRING NOT NULL,
	`PRODUCTSIZEID`  STRING NOT NULL,
	`PRODUCTSTYLEID`  STRING NOT NULL,
	`COSTINGVERSIONID`  STRING NOT NULL,
	`COMPANY`  STRING NOT NULL,
	`INVENTDIMID`  STRING NOT NULL,
	`UNITID`  STRING NOT NULL,
	`PRICECALCID`  STRING NOT NULL,
	`MARKUP`  DECIMAL(32,16) NOT NULL,
	`PRICEUNIT`  DECIMAL(32,12) NOT NULL,
	`PARTITION`  STRING NOT NULL,
	`DATAAREAID`  STRING NOT NULL,
	`SYNCSTARTDATETIME` TIMESTAMP NOT NULL,
 CONSTRAINT `PK_SMRBIInventItemPendingPriceStaging` PRIMARY KEY CLUSTERED 
(
	`EXECUTIONID` ASC,
	`FROMDATE` ASC,
	`ITEMNUMBER` ASC,
	`PRICETYPE` ASC,
	`PRICESITEID` ASC,
	`PRODUCTCONFIGURATIONID` ASC,
	`PRODUCTCOLORID` ASC,
	`PRODUCTSIZEID` ASC,
	`PRODUCTSTYLEID` ASC,
	`COSTINGVERSIONID` ASC,
	`DATAAREAID` ASC,
	`PARTITION` ASC
)WITH(STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
;
