/****** Object:  Table [dbo].[SMRBIProjBudgetStaging]    Script Date: 03/03/2026 16:26:09 ******/



CREATE OR REPLACE TABLE `dbo`.`SMRBIProjBudgetStaging`(
	`DEFINITIONGROUP`  STRING NOT NULL,
	`EXECUTIONID`  STRING NOT NULL,
	`ISSELECTED` int NOT NULL,
	`TRANSFERSTATUS` int NOT NULL,
	`BUDGETID`  STRING NOT NULL,
	`BUDGETSTATE` int NOT NULL,
	`BUDGETWORKFLOWSTATUS` int NOT NULL,
	`DESCRIPTION`  STRING NOT NULL,
	`ORIGINALBUDGETFORECASTMODEL`  STRING NOT NULL,
	`REMAININGBUDGETFORECASTMODEL`  STRING NOT NULL,
	`ROOTPROJID`  STRING NOT NULL,
	`PARTITION`  STRING NOT NULL,
	`DATAAREAID`  STRING NOT NULL,
	`SYNCSTARTDATETIME` TIMESTAMP NOT NULL,
	`RECID` bigint NOT NULL,
 CONSTRAINT `PK_SMRBIProjBudgetStaging` PRIMARY KEY CLUSTERED 
(
	`EXECUTIONID` ASC,
	`BUDGETID` ASC,
	`DATAAREAID` ASC,
	`PARTITION` ASC
)WITH(STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
;
