/****** Object:  Table [dbo].[SMRBIProdCalcTransStaging]    Script Date: 03/03/2026 16:26:09 ******/



CREATE OR REPLACE TABLE `dbo`.`SMRBIProdCalcTransStaging`(
	`DEFINITIONGROUP`  STRING NOT NULL,
	`EXECUTIONID`  STRING NOT NULL,
	`ISSELECTED` int NOT NULL,
	`TRANSFERSTATUS` int NOT NULL,
	`BOM` int NOT NULL,
	`CALCTYPE` int NOT NULL,
	`COLLECTREFLEVEL` int NOT NULL,
	`CONSUMPCONSTANT`  DECIMAL(32,16) NOT NULL,
	`CONSUMPTYPE` int NOT NULL,
	`CONSUMPVARIABLE`  DECIMAL(32,16) NOT NULL,
	`COSTAMOUNT`  DECIMAL(32,16) NOT NULL,
	`COSTGROUPID`  STRING NOT NULL,
	`COSTMARKUP`  DECIMAL(32,16) NOT NULL,
	`COMPANY`  STRING NOT NULL,
	`IDREFRECID` bigint NOT NULL,
	`IDREFTABLEID` int NOT NULL,
	`INVENTDIMID`  STRING NOT NULL,
	`LINENUM`  DECIMAL(32,16) NOT NULL,
	`OPRID`  STRING NOT NULL,
	`OPRNUM` int NOT NULL,
	`QTY`  DECIMAL(32,6) NOT NULL,
	`REALCONSUMP`  DECIMAL(32,16) NOT NULL,
	`REALCOSTADJUSTMENT`  DECIMAL(32,16) NOT NULL,
	`REALCOSTAMOUNT`  DECIMAL(32,16) NOT NULL,
	`REALQTY`  DECIMAL(32,16) NOT NULL,
	`RESOURCE_`  STRING NOT NULL,
	`SALESAMOUNT`  DECIMAL(32,6) NOT NULL,
	`SALESMARKUP`  DECIMAL(32,6) NOT NULL,
	`TRANSDATE` TIMESTAMP NOT NULL,
	`TRANSREFID`  STRING NOT NULL,
	`TRANSREFTYPE` int NOT NULL,
	`UNITID`  STRING NOT NULL,
	`VENDID`  STRING NOT NULL,
	`PRODCALCTRANSRECID` bigint NOT NULL,
	`PARTITION`  STRING NOT NULL,
	`SYNCSTARTDATETIME` TIMESTAMP NOT NULL,
 CONSTRAINT `PK_SMRBIProdCalcTransStaging` PRIMARY KEY CLUSTERED 
(
	`EXECUTIONID` ASC,
	`UNITID` ASC,
	`PRODCALCTRANSRECID` ASC,
	`PARTITION` ASC
)WITH(STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
;
