/****** Object:  Table [dbo].[SMRBIProjBudgetLineRelationStaging]    Script Date: 03/03/2026 16:26:09 ******/



CREATE OR REPLACE TABLE `dbo`.`SMRBIProjBudgetLineRelationStaging`(
	`DEFINITIONGROUP`  STRING NOT NULL,
	`EXECUTIONID`  STRING NOT NULL,
	`ISSELECTED` int NOT NULL,
	`TRANSFERSTATUS` int NOT NULL,
	`ACTIVITYNUMBER`  STRING NOT NULL,
	`CATEGORYID`  STRING NOT NULL,
	`COMMITTEDREVISIONS`  DECIMAL(32,6) NOT NULL,
	`ORIGINALBUDGET`  DECIMAL(32,6) NOT NULL,
	`PROJALLOCATIONMETHOD` int NOT NULL,
	`PROJBUDGETLINETYPE` int NOT NULL,
	`PROJID`  STRING NOT NULL,
	`PROJTRANSTYPE` int NOT NULL,
	`TOTALBUDGET`  DECIMAL(32,6) NOT NULL,
	`UNCOMMITTEDREVISIONS`  DECIMAL(32,6) NOT NULL,
	`PROJBUDGET_BUDGETID`  STRING NOT NULL,
	`PARTITION`  STRING NOT NULL,
	`SYNCSTARTDATETIME` TIMESTAMP NOT NULL,
 CONSTRAINT `PK_SMRBIProjBudgetLineRelationStaging` PRIMARY KEY CLUSTERED 
(
	`EXECUTIONID` ASC,
	`ACTIVITYNUMBER` ASC,
	`CATEGORYID` ASC,
	`PROJBUDGETLINETYPE` ASC,
	`PROJID` ASC,
	`PROJBUDGET_BUDGETID` ASC,
	`PARTITION` ASC
)WITH(STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
;
