/****** Object:  Table [dbo].[SMRBIOfficeAddinLegalEntityStaging]    Script Date: 03/03/2026 16:26:08 ******/



CREATE OR REPLACE TABLE `dbo`.`SMRBIOfficeAddinLegalEntityStaging`(
	`DEFINITIONGROUP`  STRING NOT NULL,
	`EXECUTIONID`  STRING NOT NULL,
	`ISSELECTED` int NOT NULL,
	`TRANSFERSTATUS` int NOT NULL,
	`COMPANYNAME`  STRING NOT NULL,
	`COMPANYID`  STRING NOT NULL,
	`BUSINESSACTIVITY`  STRING NOT NULL,
	`PARTITION`  STRING NOT NULL,
	`SYNCSTARTDATETIME` TIMESTAMP NOT NULL,
	`RECID` bigint NOT NULL,
 CONSTRAINT `PK_SMRBIOfficeAddinLegalEntityStaging` PRIMARY KEY CLUSTERED 
(
	`EXECUTIONID` ASC,
	`COMPANYID` ASC,
	`PARTITION` ASC
)WITH(STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
;
