/****** Object:  Table [dbo].[SMRBIRouteOperationPropertiesStaging]    Script Date: 03/03/2026 16:26:08 ******/



CREATE OR REPLACE TABLE `dbo`.`SMRBIRouteOperationPropertiesStaging`(
	`DEFINITIONGROUP`  STRING NOT NULL,
	`EXECUTIONID`  STRING NOT NULL,
	`ISSELECTED` int NOT NULL,
	`TRANSFERSTATUS` int NOT NULL,
	`SETUPCOSTCATEGORYID`  STRING NOT NULL,
	`QUANTITYCOSTCATEGORYID`  STRING NOT NULL,
	`OPERATIONID`  STRING NOT NULL,
	`PRODUCTIONSITEID`  STRING NOT NULL,
	`PROCESSCOSTCATEGORYID`  STRING NOT NULL,
	`PROCESSTIME`  DECIMAL(32,6) NOT NULL,
	`ROUTEGROUPID`  STRING NOT NULL,
	`ROUTEID`  STRING NOT NULL,
	`SETUPTIME`  DECIMAL(32,6) NOT NULL,
	`COSTINGOPERATIONRESOURCEID`  STRING NOT NULL,
	`COMPANY`  STRING NOT NULL,
	`PARTITION`  STRING NOT NULL,
	`DATAAREAID`  STRING NOT NULL,
	`SYNCSTARTDATETIME` TIMESTAMP NOT NULL,
	`RECID` bigint NOT NULL,
 CONSTRAINT `PK_SMRBIRouteOperationPropertiesStaging` PRIMARY KEY CLUSTERED 
(
	`EXECUTIONID` ASC,
	`SETUPCOSTCATEGORYID` ASC,
	`QUANTITYCOSTCATEGORYID` ASC,
	`OPERATIONID` ASC,
	`PRODUCTIONSITEID` ASC,
	`PROCESSCOSTCATEGORYID` ASC,
	`PROCESSTIME` ASC,
	`ROUTEGROUPID` ASC,
	`ROUTEID` ASC,
	`SETUPTIME` ASC,
	`COSTINGOPERATIONRESOURCEID` ASC,
	`COMPANY` ASC,
	`DATAAREAID` ASC,
	`PARTITION` ASC
)WITH(STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
;
