/****** Object:  Table [dbo].[SMRBIVendorStaging]    Script Date: 03/03/2026 16:26:08 ******/



CREATE OR REPLACE TABLE `dbo`.`SMRBIVendorStaging`(
	`DEFINITIONGROUP`  STRING NOT NULL,
	`EXECUTIONID`  STRING NOT NULL,
	`ISSELECTED` int NOT NULL,
	`TRANSFERSTATUS` int NOT NULL,
	`VENDORACCOUNTNUMBER`  STRING NOT NULL,
	`COMPANYCHAINNAME`  STRING NOT NULL,
	`BUYERGROUPID`  STRING NOT NULL,
	`MAINCONTACTPERSONNELNUMBER`  STRING NOT NULL,
	`ADDRESSCITY`  STRING NOT NULL,
	`ADDRESSCOUNTRYREGIONID`  STRING NOT NULL,
	`ADDRESSVALIDFROM` TIMESTAMP NOT NULL,
	`ADDRESSVALIDTO` TIMESTAMP NOT NULL,
	`ADDRESSZIPCODE`  STRING NOT NULL,
	`FORMATTEDPRIMARYADDRESS`  STRING NOT NULL,
	`DEFAULTPURCHASEORDERPOOLID`  STRING NOT NULL,
	`VENDORGROUPID`  STRING NOT NULL,
	`VENDTABLERECID` bigint NOT NULL,
	`COMPANY`  STRING NOT NULL,
	`VENDORDCREATEDDATETIME` TIMESTAMP NOT NULL,
	`NAME`  STRING NOT NULL,
	`PARTYRECID` bigint NOT NULL,
	`CURRENCY`  STRING NOT NULL,
	`BLOCKED` int NOT NULL,
	`VENDORORGANIZATIONNAME`  STRING NOT NULL,
	`PARTITION`  STRING NOT NULL,
	`DATAAREAID`  STRING NOT NULL,
	`SYNCSTARTDATETIME` TIMESTAMP NOT NULL,
 CONSTRAINT `PK_SMRBIVendorStaging` PRIMARY KEY CLUSTERED 
(
	`EXECUTIONID` ASC,
	`VENDORACCOUNTNUMBER` ASC,
	`DATAAREAID` ASC,
	`PARTITION` ASC
)WITH(STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
;
