/****** Object:  Table [dbo].[SMRBIProjBudgetRevisionStaging]    Script Date: 03/03/2026 16:26:09 ******/



CREATE OR REPLACE TABLE `dbo`.`SMRBIProjBudgetRevisionStaging`(
	`DEFINITIONGROUP`  STRING NOT NULL,
	`EXECUTIONID`  STRING NOT NULL,
	`ISSELECTED` int NOT NULL,
	`TRANSFERSTATUS` int NOT NULL,
	`DESCRIPTION`  STRING NOT NULL,
	`EXTERNALREFERENCE`  STRING NOT NULL,
	`REQUESTEDBYCUST`  STRING NOT NULL,
	`REQUESTEDBYVEND`  STRING NOT NULL,
	`REQUESTEDDATE` TIMESTAMP NOT NULL,
	`REVISIONDATE` TIMESTAMP NOT NULL,
	`REVISIONID`  STRING NOT NULL,
	`REVISIONWORKFLOWSTATUS` int NOT NULL,
	`HCMWORKER_PERSONNELNUMBER`  STRING NOT NULL,
	`DIRPERSON_FK_PARTYNUMBER`  STRING NOT NULL,
	`PROJBUDGET_BUDGETID`  STRING NOT NULL,
	`PARTITION`  STRING NOT NULL,
	`DATAAREAID`  STRING NOT NULL,
	`SYNCSTARTDATETIME` TIMESTAMP NOT NULL,
	`RECID` bigint NOT NULL,
 CONSTRAINT `PK_SMRBIProjBudgetRevisionStaging` PRIMARY KEY CLUSTERED 
(
	`EXECUTIONID` ASC,
	`REVISIONID` ASC,
	`DATAAREAID` ASC,
	`PARTITION` ASC
)WITH(STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
;
