/****** Object:  Table [dbo].[SMRBIsmmBusinessSubsegmentStaging]    Script Date: 03/03/2026 16:26:09 ******/



CREATE OR REPLACE TABLE `dbo`.`SMRBIsmmBusinessSubsegmentStaging`(
	`DEFINITIONGROUP`  STRING NOT NULL,
	`EXECUTIONID`  STRING NOT NULL,
	`ISSELECTED` int NOT NULL,
	`TRANSFERSTATUS` int NOT NULL,
	`BUSINESSSEGMENTCODE`  STRING NOT NULL,
	`SUBSEGMENTDESCRIPTION`  STRING NOT NULL,
	`SUBSEGMENTCODE`  STRING NOT NULL,
	`PARTITION`  STRING NOT NULL,
	`DATAAREAID`  STRING NOT NULL,
	`SYNCSTARTDATETIME` TIMESTAMP NOT NULL,
 CONSTRAINT `PK_SMRBIsmmBusinessSubsegmentStaging` PRIMARY KEY CLUSTERED 
(
	`EXECUTIONID` ASC,
	`BUSINESSSEGMENTCODE` ASC,
	`SUBSEGMENTCODE` ASC,
	`DATAAREAID` ASC,
	`PARTITION` ASC
)WITH(STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
;
