/****** Object:  Table [dbo].[SMRBIOpResOperationsResourceGroupWorkCalendarAssignmentStaging]    Script Date: 03/03/2026 16:26:08 ******/



CREATE OR REPLACE TABLE `dbo`.`SMRBIOpResOperationsResourceGroupWorkCalendarAssignmentStaging`(
	`DEFINITIONGROUP`  STRING NOT NULL,
	`EXECUTIONID`  STRING NOT NULL,
	`ISSELECTED` int NOT NULL,
	`TRANSFERSTATUS` int NOT NULL,
	`OPERATIONSRESOURCEGROUPID`  STRING NOT NULL,
	`WORKCALENDARID`  STRING NOT NULL,
	`VALIDFROM` TIMESTAMP NOT NULL,
	`VALIDTO` TIMESTAMP NOT NULL,
	`COMPANY`  STRING NOT NULL,
	`PARTITION`  STRING NOT NULL,
	`DATAAREAID`  STRING NOT NULL,
	`SYNCSTARTDATETIME` TIMESTAMP NOT NULL,
	`RECID` bigint NOT NULL,
 CONSTRAINT `PK_SMRBIOpResOperationsResourceGroupWorkCalendarAssignmentStaging` PRIMARY KEY CLUSTERED 
(
	`EXECUTIONID` ASC,
	`OPERATIONSRESOURCEGROUPID` ASC,
	`VALIDFROM` ASC,
	`VALIDTO` ASC,
	`DATAAREAID` ASC,
	`PARTITION` ASC
)WITH(STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
;
