/****** Object:  Table [dbo].[SMRBIReqItemCoverageSettingsStaging]    Script Date: 03/03/2026 16:26:08 ******/



CREATE OR REPLACE TABLE `dbo`.`SMRBIReqItemCoverageSettingsStaging`(
	`DEFINITIONGROUP`  STRING NOT NULL,
	`EXECUTIONID`  STRING NOT NULL,
	`ISSELECTED` int NOT NULL,
	`TRANSFERSTATUS` int NOT NULL,
	`ITEMNUMBER`  STRING NOT NULL,
	`COVERAGEWAREHOUSEID`  STRING NOT NULL,
	`COVERAGEPRODUCTCONFIGURATIONID`  STRING NOT NULL,
	`VENDORACCOUNTNUMBER`  STRING NOT NULL,
	`COMPANY`  STRING NOT NULL,
	`PARTITION`  STRING NOT NULL,
	`DATAAREAID`  STRING NOT NULL,
	`SYNCSTARTDATETIME` TIMESTAMP NOT NULL,
 CONSTRAINT `PK_SMRBIReqItemCoverageSettingsStaging` PRIMARY KEY CLUSTERED 
(
	`EXECUTIONID` ASC,
	`ITEMNUMBER` ASC,
	`COVERAGEWAREHOUSEID` ASC,
	`COVERAGEPRODUCTCONFIGURATIONID` ASC,
	`DATAAREAID` ASC,
	`PARTITION` ASC
)WITH(STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
;
