/****** Object:  Table [dbo].[CostSheetNodeStaging]    Script Date: 03/03/2026 16:26:09 ******/



CREATE OR REPLACE TABLE `dbo`.`CostSheetNodeStaging`(
	`DEFINITIONGROUP`  STRING NOT NULL,
	`EXECUTIONID`  STRING NOT NULL,
	`ISSELECTED` int NOT NULL,
	`TRANSFERSTATUS` int NOT NULL,
	`ISCALCULATIONFACTORSPECIFIEDPERITEM` int NOT NULL,
	`RATENODESUBTYPE` int NOT NULL,
	`SURCHARGENODESUBTYPE` int NOT NULL,
	`UNITBASEDNODESUBTYPE` int NOT NULL,
	`NODENAME`  STRING NOT NULL,
	`COSTGROUPID`  STRING NOT NULL,
	`NODEDESCRIPTION`  STRING NOT NULL,
	`ISNODESHOWNASHEADER` int NOT NULL,
	`PRICENODESUBTYPE` int NOT NULL,
	`ISNODESHOWNASTOTALLINE` int NOT NULL,
	`NODETYPE` int NOT NULL,
	`DEFAULTLEDGERDIMENSIONDISPLAYVALUE`  STRING NOT NULL,
	`ESTIMATEDINDIRECTABSORPTIONMAINACCOUNTIDDISPLAYVALUE`  STRING NOT NULL,
	`ESTIMATEDINDIRECTABSORPTIONOFFSETMAINACCOUNTIDDISPLAYVALUE`  STRING NOT NULL,
	`INDIRECTABSORPTIONMAINACCOUNTIDDISPLAYVALUE`  STRING NOT NULL,
	`INDIRECTABSORPTIONOFFSETMAINACCOUNTIDDISPLAYVALUE`  STRING NOT NULL,
	`PARENTNODENAME`  STRING NOT NULL,
	`ABSORPTIONBASISNODENAME`  STRING NOT NULL,
	`SURCHARGENODEABSORPTIONBASISSUBTYPE` int NOT NULL,
	`RATENODEABSORPTIONBASISSUBTYPE` int NOT NULL,
	`PARTITION`  STRING NOT NULL,
	`DATAAREAID`  STRING NOT NULL,
	`SYNCSTARTDATETIME` TIMESTAMP NOT NULL,
 CONSTRAINT `PK_CostSheetNodeStaging` PRIMARY KEY CLUSTERED 
(
	`EXECUTIONID` ASC,
	`NODENAME` ASC,
	`ABSORPTIONBASISNODENAME` ASC,
	`SURCHARGENODEABSORPTIONBASISSUBTYPE` ASC,
	`RATENODEABSORPTIONBASISSUBTYPE` ASC,
	`DATAAREAID` ASC,
	`PARTITION` ASC
)WITH(STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
;
