/****** Object:  Table [dbo].[SMRBICustPackingSlipTransStaging]    Script Date: 03/03/2026 16:26:08 ******/



CREATE OR REPLACE TABLE `dbo`.`SMRBICustPackingSlipTransStaging`(
	`DEFINITIONGROUP`  STRING NOT NULL,
	`EXECUTIONID`  STRING NOT NULL,
	`ISSELECTED` int NOT NULL,
	`TRANSFERSTATUS` int NOT NULL,
	`CURRENCYCODE`  STRING NOT NULL,
	`COMPANY`  STRING NOT NULL,
	`DELIVERYDATE` TIMESTAMP NOT NULL,
	`INVENTDIMID`  STRING NOT NULL,
	`INVENTREFTRANSID`  STRING NOT NULL,
	`INVENTTRANSID`  STRING NOT NULL,
	`INVOICETRANSREFRECID` bigint NOT NULL,
	`ITEMID`  STRING NOT NULL,
	`LINENUM`  DECIMAL(32,16) NOT NULL,
	`ORDERED`  DECIMAL(32,6) NOT NULL,
	`ORIGSALESID`  STRING NOT NULL,
	`PACKINGSLIPID`  STRING NOT NULL,
	`PRICEUNIT`  DECIMAL(32,12) NOT NULL,
	`QTY`  DECIMAL(32,6) NOT NULL,
	`REMAIN`  DECIMAL(32,6) NOT NULL,
	`SALESID`  STRING NOT NULL,
	`SALESLINESHIPPINGDATECONFIRMED` TIMESTAMP NOT NULL,
	`SALESLINESHIPPINGDATEREQUESTED` TIMESTAMP NOT NULL,
	`SALESUNIT`  STRING NOT NULL,
	`CUSTPACKINGSLIPTRANSRECID` bigint NOT NULL,
	`PARTITION`  STRING NOT NULL,
	`DATAAREAID`  STRING NOT NULL,
	`SYNCSTARTDATETIME` TIMESTAMP NOT NULL,
	`RECID` bigint NOT NULL,
 CONSTRAINT `PK_SMRBICustPackingSlipTransStaging` PRIMARY KEY CLUSTERED 
(
	`EXECUTIONID` ASC,
	`CUSTPACKINGSLIPTRANSRECID` ASC,
	`DATAAREAID` ASC,
	`PARTITION` ASC
)WITH(STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
;
