/****** Object:  Table [dbo].[SMRBIBudgetRegisterEntryHeaderStaging]    Script Date: 03/03/2026 16:26:08 ******/



CREATE OR REPLACE TABLE `dbo`.`SMRBIBudgetRegisterEntryHeaderStaging`(
	`DEFINITIONGROUP`  STRING NOT NULL,
	`EXECUTIONID`  STRING NOT NULL,
	`ISSELECTED` int NOT NULL,
	`TRANSFERSTATUS` int NOT NULL,
	`BUDGETCODE`  STRING NOT NULL,
	`BUDGETMODELID`  STRING NOT NULL,
	`DEFAULTDATE` TIMESTAMP NOT NULL,
	`PRIMARYLEDGERID` bigint NOT NULL,
	`BUDGETMODELTYPE` int NOT NULL,
	`BUDGETSUBMODELID`  STRING NOT NULL,
	`TRANSACTIONNUMBER`  STRING NOT NULL,
	`DESCRIPTION`  STRING NOT NULL,
	`COMPANY`  STRING NOT NULL,
	`BUDGETREGISTERRECID` bigint NOT NULL,
	`STATUS` int NOT NULL,
	`PARTITION`  STRING NOT NULL,
	`DATAAREAID`  STRING NOT NULL,
	`SYNCSTARTDATETIME` TIMESTAMP NOT NULL,
	`RECID` bigint NOT NULL,
 CONSTRAINT `PK_SMRBIBudgetRegisterEntryHeaderStaging` PRIMARY KEY CLUSTERED 
(
	`EXECUTIONID` ASC,
	`BUDGETREGISTERRECID` ASC,
	`DATAAREAID` ASC,
	`PARTITION` ASC
)WITH(STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
;
