/****** Object:  Table [dbo].[AssetJournalV2EntityStaging]    Script Date: 03/03/2026 16:26:09 ******/



CREATE OR REPLACE TABLE `dbo`.`AssetJournalV2EntityStaging`(
	`ACCOUNTDISPLAYVALUE`  STRING NOT NULL,
	`OFFSETACCOUNTDISPLAYVALUE`  STRING NOT NULL,
	`DEFAULTDIMENSIONDISPLAYVALUE`  STRING NOT NULL,
	`DEFINITIONGROUP`  STRING NOT NULL,
	`EXECUTIONID`  STRING NOT NULL,
	`ISSELECTED` int NOT NULL,
	`TRANSFERSTATUS` int NOT NULL,
	`CREDITAMOUNT`  DECIMAL(32,6) NOT NULL,
	`DEBITAMOUNT`  DECIMAL(32,6) NOT NULL,
	`JOURNALBATCHNUMBER`  STRING NOT NULL,
	`OFFSETACCOUNTTYPE` int NOT NULL,
	`TRANSDATE` TIMESTAMP NOT NULL,
	`STRING`  STRING NOT NULL,
	`VOUCHER`  STRING NOT NULL,
	`CURRENCYCODE`  STRING NOT NULL,
	`POSTINGLAYER` int NOT NULL,
	`JOURNALNAMEID`  STRING NOT NULL,
	`LINENUMBER`  DECIMAL(32,16) NOT NULL,
	`ISPOSTED` int NOT NULL,
	`DESCRIPTION`  STRING NOT NULL,
	`BOOKID`  STRING NOT NULL,
	`TRANSACTIONTYPE` int NOT NULL,
	`ACCOUNTTYPE` int NOT NULL,
	`CONSUMPTIONUNITS`  DECIMAL(32,6) NOT NULL,
	`EXCHANGERATE`  DECIMAL(32,16) NOT NULL,
	`CHINESEVOUCHERTYPE`  STRING NOT NULL,
	`CHINESEVOUCHER`  STRING NOT NULL,
	`CREDITAMOUNTREPORTINGCURRENCY`  DECIMAL(32,6) NOT NULL,
	`DEBITAMOUNTREPORTINGCURRENCY`  DECIMAL(32,6) NOT NULL,
	`PARTITION`  STRING NOT NULL,
	`DATAAREAID`  STRING NOT NULL,
	`SYNCSTARTDATETIME` TIMESTAMP NOT NULL,
 CONSTRAINT `PK_AssetJournalV2EntityStaging` PRIMARY KEY CLUSTERED 
(
	`EXECUTIONID` ASC,
	`JOURNALBATCHNUMBER` ASC,
	`LINENUMBER` ASC,
	`DATAAREAID` ASC,
	`PARTITION` ASC
)WITH(STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
;
