/****** Object:  Table [dbo].[SMRBIReqTransCovStaging]    Script Date: 03/03/2026 16:26:09 ******/



CREATE OR REPLACE TABLE `dbo`.`SMRBIReqTransCovStaging`(
	`DEFINITIONGROUP`  STRING NOT NULL,
	`EXECUTIONID`  STRING NOT NULL,
	`ISSELECTED` int NOT NULL,
	`TRANSFERSTATUS` int NOT NULL,
	`COMPANY`  STRING NOT NULL,
	`ISSUERECID` bigint NOT NULL,
	`QTY`  DECIMAL(32,6) NOT NULL,
	`RECEIPTRECID` bigint NOT NULL,
	`REQTRANSCOVRECID` bigint NOT NULL,
	`PARTITION`  STRING NOT NULL,
	`DATAAREAID`  STRING NOT NULL,
	`SYNCSTARTDATETIME` TIMESTAMP NOT NULL,
	`RECID` bigint NOT NULL,
 CONSTRAINT `PK_SMRBIReqTransCovStaging` PRIMARY KEY CLUSTERED 
(
	`EXECUTIONID` ASC,
	`ISSUERECID` ASC,
	`REQTRANSCOVRECID` ASC,
	`DATAAREAID` ASC,
	`PARTITION` ASC
)WITH(STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
;
