/****** Object:  Table [dbo].[SMRBIOpResOperationsResourceGroupStaging]    Script Date: 03/03/2026 16:26:08 ******/



CREATE OR REPLACE TABLE `dbo`.`SMRBIOpResOperationsResourceGroupStaging`(
	`DEFINITIONGROUP`  STRING NOT NULL,
	`EXECUTIONID`  STRING NOT NULL,
	`ISSELECTED` int NOT NULL,
	`TRANSFERSTATUS` int NOT NULL,
	`INPUTWAREHOUSEID`  STRING NOT NULL,
	`INPUTWAREHOUSELOCATIONID`  STRING NOT NULL,
	`OUTPUTWAREHOUSEID`  STRING NOT NULL,
	`OUTPUTWAREHOUSELOCATIONID`  STRING NOT NULL,
	`PRODUCTIONUNITID`  STRING NOT NULL,
	`GROUPID`  STRING NOT NULL,
	`GROUPNAME`  STRING NOT NULL,
	`COMPANY`  STRING NOT NULL,
	`OPRESOPERATIONSRESOURCEGROUPRECID` bigint NOT NULL,
	`PARTITION`  STRING NOT NULL,
	`DATAAREAID`  STRING NOT NULL,
	`SYNCSTARTDATETIME` TIMESTAMP NOT NULL,
	`RECID` bigint NOT NULL,
 CONSTRAINT `PK_SMRBIOpResOperationsResourceGroupStaging` PRIMARY KEY CLUSTERED 
(
	`EXECUTIONID` ASC,
	`GROUPID` ASC,
	`DATAAREAID` ASC,
	`PARTITION` ASC
)WITH(STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
;
