/****** Object:  Table [dbo].[SMRBIInventItemBatchStaging]    Script Date: 03/03/2026 16:26:08 ******/



CREATE OR REPLACE TABLE `dbo`.`SMRBIInventItemBatchStaging`(
	`DEFINITIONGROUP`  STRING NOT NULL,
	`EXECUTIONID`  STRING NOT NULL,
	`ISSELECTED` int NOT NULL,
	`TRANSFERSTATUS` int NOT NULL,
	`BATCHDESCRIPTION`  STRING,
	`BATCHEXPIRATIONDATE` TIMESTAMP NOT NULL,
	`BATCHNUMBER`  STRING NOT NULL,
	`ITEMNUMBER`  STRING NOT NULL,
	`MANUFACTURINGDATE` TIMESTAMP NOT NULL,
	`COMPANY`  STRING NOT NULL,
	`INVENTBATCHRECID` bigint NOT NULL,
	`PARTITION`  STRING NOT NULL,
	`DATAAREAID`  STRING NOT NULL,
	`SYNCSTARTDATETIME` TIMESTAMP NOT NULL,
 CONSTRAINT `PK_SMRBIInventItemBatchStaging` PRIMARY KEY CLUSTERED 
(
	`EXECUTIONID` ASC,
	`BATCHNUMBER` ASC,
	`ITEMNUMBER` ASC,
	`DATAAREAID` ASC,
	`PARTITION` ASC
)WITH(STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
) TEXTIMAGE_ON `PRIMARY`
;
