/****** Object:  Table [dbo].[SMRBIBOMCalcTableStaging]    Script Date: 03/03/2026 16:26:09 ******/



CREATE OR REPLACE TABLE `dbo`.`SMRBIBOMCalcTableStaging`(
	`DEFINITIONGROUP`  STRING NOT NULL,
	`EXECUTIONID`  STRING NOT NULL,
	`ISSELECTED` int NOT NULL,
	`TRANSFERSTATUS` int NOT NULL,
	`PRICECALCID`  STRING NOT NULL,
	`BOMCALCTYPE` int NOT NULL,
	`BOMID`  STRING NOT NULL,
	`COSTCALCULATIONMETHOD` int NOT NULL,
	`COSTMARKUP`  DECIMAL(32,16) NOT NULL,
	`COSTPRICE`  DECIMAL(32,6) NOT NULL,
	`COMPANY`  STRING NOT NULL,
	`INVENTDIMID`  STRING NOT NULL,
	`ITEMID`  STRING NOT NULL,
	`QTY`  DECIMAL(32,6) NOT NULL,
	`ROUTEID`  STRING NOT NULL,
	`SALESMARKUP`  DECIMAL(32,6) NOT NULL,
	`SALESPRICE`  DECIMAL(32,6) NOT NULL,
	`TRANSDATE` TIMESTAMP NOT NULL,
	`UNITID`  STRING NOT NULL,
	`PARTITION`  STRING NOT NULL,
	`DATAAREAID`  STRING NOT NULL,
	`SYNCSTARTDATETIME` TIMESTAMP NOT NULL,
 CONSTRAINT `PK_SMRBIBOMCalcTableStaging` PRIMARY KEY CLUSTERED 
(
	`EXECUTIONID` ASC,
	`PRICECALCID` ASC,
	`DATAAREAID` ASC,
	`PARTITION` ASC
)WITH(STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
;
