/****** Object:  Table [dbo].[SMRBIProjForecastSalesStaging]    Script Date: 03/03/2026 16:26:09 ******/



CREATE OR REPLACE TABLE `dbo`.`SMRBIProjForecastSalesStaging`(
	`DEFINITIONGROUP`  STRING NOT NULL,
	`EXECUTIONID`  STRING NOT NULL,
	`ISSELECTED` int NOT NULL,
	`TRANSFERSTATUS` int NOT NULL,
	`ACTIVITYNUMBER`  STRING NOT NULL,
	`BUDGETCOMMENT`  STRING NOT NULL,
	`COSTPRICE`  DECIMAL(32,6) NOT NULL,
	`CURRENCY`  STRING NOT NULL,
	`CUSTOMERACCOUNTID`  STRING NOT NULL,
	`CUSTOMERGROUPID`  STRING NOT NULL,
	`ITEMGROUPID`  STRING NOT NULL,
	`ITEMID`  STRING NOT NULL,
	`MODELID`  STRING NOT NULL,
	`PRICEUNIT`  DECIMAL(32,12) NOT NULL,
	`PROJECTCATEGORYID`  STRING NOT NULL,
	`PROJECTID`  STRING NOT NULL,
	`PROJECTLINEPROPERTYID`  STRING NOT NULL,
	`PROJECTTRANSID`  STRING NOT NULL,
	`SALESPRICE`  DECIMAL(32,6) NOT NULL,
	`SALESQUANTITY`  DECIMAL(32,6) NOT NULL,
	`SALESUNITID`  STRING NOT NULL,
	`STARTDATE` TIMESTAMP NOT NULL,
	`COMPANY`  STRING NOT NULL,
	`FORECASTEDREVENUE` int NOT NULL,
	`PERIODKEYID`  STRING NOT NULL,
	`PROJECTTRANSACTIONID`  STRING NOT NULL,
	`EXPANDID` bigint NOT NULL,
	`PARTITION`  STRING NOT NULL,
	`DATAAREAID`  STRING NOT NULL,
	`SYNCSTARTDATETIME` TIMESTAMP NOT NULL,
	`RECID` bigint NOT NULL,
 CONSTRAINT `PK_SMRBIProjForecastSalesStaging` PRIMARY KEY CLUSTERED 
(
	`EXECUTIONID` ASC,
	`ACTIVITYNUMBER` ASC,
	`DATAAREAID` ASC,
	`PARTITION` ASC
)WITH(STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
;
