/****** Object:  Table [dbo].[SMRBIVendInvoiceTransStaging]    Script Date: 03/03/2026 16:26:09 ******/



CREATE OR REPLACE TABLE `dbo`.`SMRBIVendInvoiceTransStaging`(
	`DEFINITIONGROUP`  STRING NOT NULL,
	`EXECUTIONID`  STRING NOT NULL,
	`ISSELECTED` int NOT NULL,
	`TRANSFERSTATUS` int NOT NULL,
	`CURRENCYCODE`  STRING NOT NULL,
	`COMPANY`  STRING NOT NULL,
	`DESCRIPTION`  STRING NOT NULL,
	`INTERNALINVOICEID`  STRING NOT NULL,
	`INVENTDIMID`  STRING NOT NULL,
	`INVENTTRANSID`  STRING NOT NULL,
	`INVOICEDATE` TIMESTAMP NOT NULL,
	`INVOICEID`  STRING NOT NULL,
	`ITEMID`  STRING NOT NULL,
	`LINEAMOUNT`  DECIMAL(32,6) NOT NULL,
	`LINEAMOUNTMST`  DECIMAL(32,6) NOT NULL,
	`LINEDISC`  DECIMAL(32,6) NOT NULL,
	`LINENUM`  DECIMAL(32,16) NOT NULL,
	`LINEPERCENT`  DECIMAL(32,6) NOT NULL,
	`ORIGPURCHID`  STRING NOT NULL,
	`PRICEUNIT`  DECIMAL(32,12) NOT NULL,
	`PURCHPRICE`  DECIMAL(32,6) NOT NULL,
	`PURCHUNIT`  STRING NOT NULL,
	`QTY`  DECIMAL(32,6) NOT NULL,
	`VENDINVOICETRANSRECID` bigint NOT NULL,
	`TAXWRITECODE`  STRING NOT NULL,
	`DEFAULTDIMENSIONDISPLAYVALUE`  STRING NOT NULL,
	`LEDGERDIMENSIONDISPLAYVALUE`  STRING NOT NULL,
	`VENDINVOICETRANSDIMENSION` bigint NOT NULL,
	`DEFAULTDIMENSION` bigint NOT NULL,
	`PARTITION`  STRING NOT NULL,
	`DATAAREAID`  STRING NOT NULL,
	`SYNCSTARTDATETIME` TIMESTAMP NOT NULL,
	`RECID` bigint NOT NULL,
 CONSTRAINT `PK_SMRBIVendInvoiceTransStaging` PRIMARY KEY CLUSTERED 
(
	`EXECUTIONID` ASC,
	`VENDINVOICETRANSRECID` ASC,
	`DATAAREAID` ASC,
	`PARTITION` ASC
)WITH(STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
;
