/****** Object:  Table [dbo].[SMRBIProjForecastEmplStaging]    Script Date: 03/03/2026 16:26:09 ******/



CREATE OR REPLACE TABLE `dbo`.`SMRBIProjForecastEmplStaging`(
	`CATEGORY`  STRING NOT NULL,
	`LINEPROPERTY`  STRING NOT NULL,
	`PROJECTID`  STRING NOT NULL,
	`SALESCURRENCY`  STRING NOT NULL,
	`TRANSACTIONID`  STRING NOT NULL,
	`DEFINITIONGROUP`  STRING NOT NULL,
	`EXECUTIONID`  STRING NOT NULL,
	`ISSELECTED` int NOT NULL,
	`TRANSFERSTATUS` int NOT NULL,
	`ACTIVITYNUMBER`  STRING NOT NULL,
	`COSTPRICE`  DECIMAL(32,6) NOT NULL,
	`COMPANY`  STRING NOT NULL,
	`DESCRIPTION`  STRING NOT NULL,
	`FORECASTMODEL`  STRING NOT NULL,
	`HOURS`  DECIMAL(32,6) NOT NULL,
	`PROJECTDATE` TIMESTAMP NOT NULL,
	`SALESPRICE`  DECIMAL(32,6) NOT NULL,
	`WORKER` bigint NOT NULL,
	`PARTITION`  STRING NOT NULL,
	`DATAAREAID`  STRING NOT NULL,
	`SYNCSTARTDATETIME` TIMESTAMP NOT NULL,
 CONSTRAINT `PK_SMRBIProjForecastEmplStaging` PRIMARY KEY CLUSTERED 
(
	`TRANSACTIONID` ASC,
	`EXECUTIONID` ASC,
	`DATAAREAID` ASC,
	`PARTITION` ASC
)WITH(STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
;
