/****** Object:  Table [dbo].[SMRBIReqTransStaging]    Script Date: 03/03/2026 16:26:09 ******/



CREATE OR REPLACE TABLE `dbo`.`SMRBIReqTransStaging`(
	`DEFINITIONGROUP`  STRING NOT NULL,
	`EXECUTIONID`  STRING NOT NULL,
	`ISSELECTED` int NOT NULL,
	`TRANSFERSTATUS` int NOT NULL,
	`COVQTY`  DECIMAL(32,6) NOT NULL,
	`COMPANY`  STRING NOT NULL,
	`DIRECTION` int NOT NULL,
	`ITEMID`  STRING NOT NULL,
	`PLANVERSION` bigint NOT NULL,
	`QTY`  DECIMAL(32,6) NOT NULL,
	`REQTRANSREQID` bigint NOT NULL,
	`REFID`  STRING NOT NULL,
	`REFTYPE` int NOT NULL,
	`REQDATE` TIMESTAMP NOT NULL,
	`ACTIONDATE` TIMESTAMP NOT NULL,
	`COVINVENTDIMID`  STRING NOT NULL,
	`CUSTACCOUNTID`  STRING NOT NULL,
	`INVENTTRANSORIGIN` bigint NOT NULL,
	`ACTIONTYPE` int NOT NULL,
	`ACTIONMARKED` int NOT NULL,
	`ACTIONDAYS` int NOT NULL,
	`FUTURESCALCULATED` int NOT NULL,
	`FUTURESDATE` TIMESTAMP NOT NULL,
	`FUTURESDAYS` int NOT NULL,
	`FUTURESMARKED` int NOT NULL,
	`REQTIME` int NOT NULL,
	`PARTITION`  STRING NOT NULL,
	`DATAAREAID`  STRING NOT NULL,
	`SYNCSTARTDATETIME` TIMESTAMP NOT NULL,
	`RECID` bigint NOT NULL,
 CONSTRAINT `PK_SMRBIReqTransStaging` PRIMARY KEY CLUSTERED 
(
	`EXECUTIONID` ASC,
	`REQTRANSREQID` ASC,
	`DATAAREAID` ASC,
	`PARTITION` ASC
)WITH(STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
;
