/****** Object:  Table [dbo].[SMRBIPdsRebateTableStaging]    Script Date: 03/03/2026 16:26:09 ******/



CREATE OR REPLACE TABLE `dbo`.`SMRBIPdsRebateTableStaging`(
	`DEFINITIONGROUP`  STRING NOT NULL,
	`EXECUTIONID`  STRING NOT NULL,
	`ISSELECTED` int NOT NULL,
	`TRANSFERSTATUS` int NOT NULL,
	`REBATECREATEDDATETIME` TIMESTAMP NOT NULL,
	`CURRENCYCODE`  STRING NOT NULL,
	`CUSTACCOUNT`  STRING NOT NULL,
	`CUSTINVOICETRANSREFRECID` bigint NOT NULL,
	`COMPANY`  STRING NOT NULL,
	`INVENTTRANSID`  STRING NOT NULL,
	`ITEMID`  STRING NOT NULL,
	`PDSCORRECTEDREBATEAMT`  DECIMAL(32,6) NOT NULL,
	`PDSPROCESSDATE` TIMESTAMP NOT NULL,
	`PDSREBATEADJUSTMENTDATE` TIMESTAMP NOT NULL,
	`PDSREBATEAMT`  DECIMAL(32,6) NOT NULL,
	`PDSREBATEAMTTYPE` int NOT NULL,
	`PDSREBATEBALANCE`  DECIMAL(32,6) NOT NULL,
	`PDSREBATEID`  STRING NOT NULL,
	`PDSREBATESTATUS` int NOT NULL,
	`PDSREBATETYPE`  STRING NOT NULL,
	`PDSREBATEVALUE`  DECIMAL(32,6) NOT NULL,
	`REBATECALCDATE` TIMESTAMP NOT NULL,
	`SALESAMOUNT`  DECIMAL(32,6) NOT NULL,
	`SALESID`  STRING NOT NULL,
	`SALESINVOICEDATE` TIMESTAMP NOT NULL,
	`SALESINVOICEID`  STRING NOT NULL,
	`LEDGERDIMENSIONDISPLAYVALUE`  STRING NOT NULL,
	`PDSSTARTINGREBATEAMT`  DECIMAL(32,6) NOT NULL,
	`PDSREBATETABLEDIMENSION` bigint NOT NULL,
	`PARTITION`  STRING NOT NULL,
	`DATAAREAID`  STRING NOT NULL,
	`SYNCSTARTDATETIME` TIMESTAMP NOT NULL,
 CONSTRAINT `PK_SMRBIPdsRebateTableStaging` PRIMARY KEY CLUSTERED 
(
	`EXECUTIONID` ASC,
	`PDSREBATEID` ASC,
	`DATAAREAID` ASC,
	`PARTITION` ASC
)WITH(STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
;
