/****** Object:  Table [dbo].[SMRBIProdRouteTransStaging]    Script Date: 03/03/2026 16:26:09 ******/



CREATE OR REPLACE TABLE `dbo`.`SMRBIProdRouteTransStaging`(
	`DEFINITIONGROUP`  STRING NOT NULL,
	`EXECUTIONID`  STRING NOT NULL,
	`ISSELECTED` int NOT NULL,
	`TRANSFERSTATUS` int NOT NULL,
	`AMOUNT`  DECIMAL(32,6) NOT NULL,
	`CATEGORYID`  STRING NOT NULL,
	`COMPANY`  STRING NOT NULL,
	`DATEWIP` TIMESTAMP NOT NULL,
	`HOURPRICE`  DECIMAL(32,6) NOT NULL,
	`HOURS`  DECIMAL(32,6) NOT NULL,
	`OPRID`  STRING NOT NULL,
	`OPRNUM` int NOT NULL,
	`QTYERROR`  DECIMAL(32,6) NOT NULL,
	`QTYGOOD`  DECIMAL(32,6) NOT NULL,
	`PRODROUTETRANSRECID` bigint NOT NULL,
	`TRANSREFID`  STRING NOT NULL,
	`TRANSREFTYPE` int NOT NULL,
	`TRANSTYPE` int NOT NULL,
	`WORKER` bigint NOT NULL,
	`WRKCTRID`  STRING NOT NULL,
	`PARTITION`  STRING NOT NULL,
	`SYNCSTARTDATETIME` TIMESTAMP NOT NULL,
	`RECID` bigint NOT NULL,
 CONSTRAINT `PK_SMRBIProdRouteTransStaging` PRIMARY KEY CLUSTERED 
(
	`EXECUTIONID` ASC,
	`PRODROUTETRANSRECID` ASC,
	`PARTITION` ASC
)WITH(STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
;
