/****** Object:  Table [dbo].[YSLEShipmentInvoiceDetailsStaging]    Script Date: 03/03/2026 16:26:08 ******/



CREATE OR REPLACE TABLE `dbo`.`YSLEShipmentInvoiceDetailsStaging`(
	`DEFINITIONGROUP`  STRING NOT NULL,
	`EXECUTIONID`  STRING NOT NULL,
	`ISSELECTED` int NOT NULL,
	`TRANSFERSTATUS` int NOT NULL,
	`SHIPMENTID`  STRING NOT NULL,
	`LINENUM`  DECIMAL(32,16) NOT NULL,
	`INVOICEDATE` TIMESTAMP NOT NULL,
	`VENDINVOICEID`  STRING NOT NULL,
	`CUSTINVOICEID`  STRING NOT NULL,
	`CURRENCYCODE`  STRING NOT NULL,
	`AMOUNT`  DECIMAL(32,6) NOT NULL,
	`VOUCHER`  STRING NOT NULL,
	`PARTITION`  STRING NOT NULL,
	`DATAAREAID`  STRING NOT NULL,
	`SYNCSTARTDATETIME` TIMESTAMP NOT NULL,
	`RECID` bigint NOT NULL,
 CONSTRAINT `PK_YSLEShipmentInvoiceDetailsStaging` PRIMARY KEY CLUSTERED 
(
	`EXECUTIONID` ASC,
	`SHIPMENTID` ASC,
	`LINENUM` ASC,
	`DATAAREAID` ASC,
	`PARTITION` ASC
)WITH(STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
;
