/****** Object:  Table [DWH].[DimVoucher]    Script Date: 03/03/2026 16:26:08 ******/



CREATE OR REPLACE TABLE `DWH`.`DimVoucher`(
	`DimVoucherId` BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL,
	`Voucher`  STRING NOT NULL,
	`CompanyCode`  STRING NOT NULL,
	`Information`  STRING NOT NULL,
	`CreatedETLRunId` int NOT NULL,
	`ModifiedETLRunId` int NOT NULL,
 CONSTRAINT `PK_DimVoucherFD` PRIMARY KEY CLUSTERED 
(
	`DimVoucherId` ASC
)WITH(STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
;
