/****** Object:  Table [DWH].[DimSystemUser]    Script Date: 03/03/2026 16:26:09 ******/



CREATE OR REPLACE TABLE `DWH`.`DimSystemUser`(
	`DimSystemUserId` BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL,
	`SystemUserCode`  STRING NOT NULL,
	`DomainUserName`  STRING NOT NULL,
	`UserName`  STRING NOT NULL,
	`CreatedETLRunId` int NOT NULL,
	`ModifiedETLRunId` int NOT NULL,
 CONSTRAINT `PK_DimSystemUserId` PRIMARY KEY CLUSTERED 
(
	`DimSystemUserId` ASC
)WITH(STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
;
