/****** Object:  Table [DWH].[DimDate]    Script Date: 03/03/2026 16:26:08 ******/



CREATE OR REPLACE TABLE `DWH`.`DimDate`(
	`DimDateId` int NOT NULL,
	TIMESTAMP TIMESTAMP NOT NULL,
	`YearId` int NOT NULL,
	`YearName`  STRING NOT NULL,
	`SemesterId` int NOT NULL,
	`SemesterName`  STRING NOT NULL,
	`SemesterOfYearId` int NOT NULL,
	`SemesterOfYearName`  STRING NOT NULL,
	`QuarterId` int NOT NULL,
	`QuarterName`  STRING NOT NULL,
	`QuarterOfYearName`  STRING NOT NULL,
	`QuarterOfYearId` int NOT NULL,
	`MonthOfYearId` int NOT NULL,
	`MonthId` int NOT NULL,
	`MonthName`  STRING NOT NULL,
	`MonthOfYearName`  STRING NOT NULL,
	`DayOfYearId` int NOT NULL,
	`DayNameLong`  STRING NOT NULL,
	`DayNameShort`  STRING NOT NULL,
	`DayOfYearName`  STRING NOT NULL,
	`DayOfWeekName`  STRING NOT NULL,
	`DayOfWeekId` int NOT NULL,
	`WeekOfYearId` int NOT NULL,
	`WeekOfYearName`  STRING NOT NULL,
	`WeekId` int NOT NULL,
	`WeekName`  STRING NOT NULL,
	`IsCurrentYear` `BOOLEAN` NOT NULL,
	`IsPreviousYear` `BOOLEAN` NOT NULL,
	`IsToday` `BOOLEAN` NOT NULL,
	`IsYesterday` `BOOLEAN` NOT NULL,
	`IsCurrentMonth` `BOOLEAN` NOT NULL,
	`IsPreviousMonth` `BOOLEAN` NOT NULL,
	`IsCurrentWeek` `BOOLEAN` NOT NULL,
	`IsPreviousWeek` `BOOLEAN` NOT NULL,
	`CreatedETLRunId` int NOT NULL,
	`ModifiedETLRunId` int NOT NULL,
	`FYStart` TIMESTAMP NOT NULL,
	`FYDayOfYearId` int NOT NULL,
	`FYDayId` int NOT NULL,
	`FYQuarterOfYearId` int NOT NULL,
	`FYQuarterOfYearName`  STRING NOT NULL,
	`FYQuarterId` int NOT NULL,
	`FYQuarterName`  STRING NOT NULL,
	`FYMonthOfYearId` int NOT NULL,
	`FYMonthId`  STRING NOT NULL,
	`FYWeekOfYearId` int NOT NULL,
	`FYWeekOfYearName`  STRING NOT NULL,
	`FYWeekId` int NOT NULL,
	`FYWeekName`  STRING NOT NULL,
	`FYDayOfYearName`  STRING NOT NULL,
	`FYMonthName`  STRING NOT NULL,
	`FYMonthOfYearName`  STRING NOT NULL,
	`FYYearId` int NOT NULL,
	`FYYearName`  STRING NOT NULL,
	`FYIsPreviousYear` `BOOLEAN` NOT NULL,
	`FYIsCurrentYear` `BOOLEAN` NOT NULL,
	`FYDayNameLong`  STRING NOT NULL,
	`FYDayNameShort`  STRING NOT NULL,
	`FYDayOfWeekName`  STRING NOT NULL,
	`FYDayOfWeekId` int NOT NULL,
 CONSTRAINT `PK_DimDate` PRIMARY KEY CLUSTERED 
(
	`DimDateId` ASC
)WITH(STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
;
