/****** Object:  StoredProcedure [ETL].[uspCreateForeignKeysTable]    Script Date: 03/03/2026 16:26:10 ******/





CREATE OR REPLACE PROCEDURE `ETL`.`uspCreateForeignKeysTable`(
IN V_Table STRING,
IN V_Schema STRING,
IN V_Execute EXECUTE)
LANGUAGE SQL
SQL SECURITY INVOKER
AS

BEGIN
 
DECLARE VARIABLE V_Query STRING
;CALLER
AS

CREATE TEMPORARY TABLE V_Columns
(ColumnName STRING, TableName STRING)
;
CREATE TEMPORARY TABLE V_ScriptTable
(Query STRING)
;
INSERT INTO V_Columns 
(ColumnName, TableName)

(SELECT C.COLUMN_NAME,
COALESCE(T2.TABLE_NAME, T3.TABLE_NAME)

FROM INFORMATION_SCHEMA.COLUMNS C

LEFT JOIN  INFORMATION_SCHEMA.TABLES T2
ON T2.TABLE_NAME = SUBSTRING(C.COLUMN_NAME,4,LEN(C.COLUMN_NAME)-5)
AND T2.TABLE_SCHEMA = C.TABLE_SCHEMA
AND LEFT(T2.TABLE_NAME,3)<>'Tmp'

LEFT JOIN 
(SELECT MAX(LEN(T3.TABLE_NAME)) AS TableLength,
C.COLUMN_NAME AS COLUMN_NAME
FROM INFORMATION_SCHEMA.COLUMNS C
INNER JOIN
INFORMATION_SCHEMA.TABLES T3
ON INSTR(SUBSTRING(C.COLUMN_NAME, 0), RIGHT(T3.TABLE_NAME,LEN(T3.TABLE_NAME)-3))>0
AND (LEN(C.COLUMN_NAME)-INSTR(SUBSTRING(C.COLUMN_NAME, 0), RIGHT(T3.TABLE_NAME,LEN(T3.TABLE_NAME)-3))-LEN(T3.TABLE_NAME)+2) = 0
WHERE C.TABLE_NAME = V_Table
AND C.TABLE_SCHEMA = V_Schema
AND C.DATA_TYPE = 'int'
AND LEFT(C.COLUMN_NAME,3)='Dim'
AND LEFT(T3.TABLE_NAME,3)<>'Tmp'
AND RIGHT(C.COLUMN_NAME,2)='Id'
GROUP BY C.COLUMN_NAME) AS Temp
ON Temp.COLUMN_NAME = C.COLUMN_NAME

LEFT JOIN INFORMATION_SCHEMA.TABLES T3
ON INSTR(SUBSTRING(C.COLUMN_NAME, 0), RIGHT(T3.TABLE_NAME,LEN(T3.TABLE_NAME)-3))>0
AND (LEN(C.COLUMN_NAME)-INSTR(SUBSTRING(C.COLUMN_NAME, 0), RIGHT(T3.TABLE_NAME,LEN(T3.TABLE_NAME)-3))-LEN(T3.TABLE_NAME)+2) = 0
AND LEN(T3.TABLE_NAME)=Temp.TableLength
AND T3.TABLE_SCHEMA = C.TABLE_SCHEMA

WHERE C.TABLE_NAME = V_Table
AND C.TABLE_SCHEMA = V_Schema
AND LEFT(T3.TABLE_NAME,3)<> 'Tmp'
AND C.DATA_TYPE = 'int'
AND LEFT(C.COLUMN_NAME,3)='Dim'
AND RIGHT(C.COLUMN_NAME,2)='Id'
AND C.COLUMN_NAME NOT IN (SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE WHERE TABLE_NAME = V_Table AND TABLE_SCHEMA = V_Schema)
)

;
INSERT INTO V_ScriptTable
(Query)
(SELECT 'ALTER TABLE '||V_Schema||'.'||V_Table||'  WITH NOCHECK ADD  CONSTRAINT `FK_'||V_Schema||'_'
||Replace(V_Table,'.','_')||'_'||ColumnName
||'` FOREIGN KEY(`'||ColumnName||'`) REFERENCES `DWH`.`'||COALESCE(TableName, 'Unkown')||'` (`'||REPLACE(COALESCE(TableName, 'Unknown'),'DWH','PK')||'Id'||'`) 


;
SET V_Query = (
SELECT
COALESCE(V_Query + CHAR(10), '') + Query FROM
    V_ScriptTable
	 LIMIT 1);
SELECT V_Query
;
IF V_Execute = 1
THEN
EXECUTE(V_Query)
;
END IF

;
SELECT V_Query
;
END
