# Databricks notebook source
# MAGIC %md
# MAGIC # DWH.FactAccountsPayable.Table
# MAGIC This notebook was automatically converted from the script below. It may contain errors, so use it as a starting point and make necessary corrections.
# MAGIC
# MAGIC Source script: `/Volumes/dbe_dbx_internships/switchschema/switchvolume/input-20260324104824-3bci/DWH.FactAccountsPayable.Table.sql`

# COMMAND ----------

# ------------------------------------------------------------
# Setup: import any needed modules (Databricks provides Spark session)
# ------------------------------------------------------------
from pyspark.sql import functions as F

# COMMAND ----------

# ------------------------------------------------------------
# Create the FactAccountsPayable table in the target catalog/schema.
# Databricks Delta does not enforce primary keys or foreign keys,
# and the IDENTITY property is expressed via GENERATED ... AS IDENTITY.
# ------------------------------------------------------------
spark.sql("""
CREATE TABLE IF NOT EXISTS dbe_dbx_internships.switchschema.FactAccountsPayable (
    FactAccountsPayableId BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    DimCompanyId INT NOT NULL,
    DimPurchaseInvoiceId INT NOT NULL,
    DimIsOpenAmountId BOOLEAN NOT NULL,
    DimOutstandingPeriodId INT NOT NULL,
    DimSupplierId INT NOT NULL,
    DimTransactionCurrencyId INT NOT NULL,
    DimAccountingCurrencyId INT NOT NULL,
    DimReportingCurrencyId INT NOT NULL,
    DimGroupCurrencyId INT NOT NULL,
    DimReportDateId INT NOT NULL,
    DimDueDateId INT NOT NULL,
    ReportMonthId INT,
    InvoiceDate TIMESTAMP NOT NULL,
    LastPaymentDate TIMESTAMP NOT NULL,
    DocumentDate TIMESTAMP NOT NULL,
    RecId LONG NOT NULL,
    PayablesVoucher STRING NOT NULL,
    Description STRING NOT NULL,
    InvoiceAmountTC DECIMAL(38,6),
    InvoiceAmountAC DECIMAL(38,6),
    InvoiceAmountRC DECIMAL(38,6),
    InvoiceAmountGC DECIMAL(38,6),
    InvoiceAmountAC_Budget DECIMAL(38,6),
    InvoiceAmountRC_Budget DECIMAL(38,6),
    InvoiceAmountGC_Budget DECIMAL(38,6),
    PaidAmountTC DECIMAL(38,6),
    PaidAmountAC DECIMAL(38,6),
    PaidAmountRC DECIMAL(38,6),
    PaidAmountGC DECIMAL(38,6),
    PaidAmountAC_Budget DECIMAL(38,6),
    PaidAmountRC_Budget DECIMAL(38,6),
    PaidAmountGC_Budget DECIMAL(38,6),
    OpenAmountTC DECIMAL(38,6),
    OpenAmountAC DECIMAL(38,6),
    OpenAmountRC DECIMAL(38,6),
    OpenAmountGC DECIMAL(38,6),
    OpenAmountAC_Budget DECIMAL(38,6),
    OpenAmountRC_Budget DECIMAL(38,6),
    OpenAmountGC_Budget DECIMAL(38,6),
    AppliedExchangeRateTC DECIMAL(38,6),
    AppliedExchangeRateAC DECIMAL(38,6),
    AppliedExchangeRateRC DECIMAL(38,6),
    AppliedExchangeRateGC DECIMAL(38,6),
    AppliedExchangeRateAC_Budget DECIMAL(38,6),
    AppliedExchangeRateRC_Budget DECIMAL(38,6),
    AppliedExchangeRateGC_Budget DECIMAL(38,6),
    CreatedETLRunId INT NOT NULL,
    ModifiedETLRunId INT NOT NULL,
    DimVoucherId INT
)
USING DELTA
COMMENT 'Fact table for Accounts Payable – primary key and foreign keys are documented as comments because Delta does not enforce them.'
""")

# COMMAND ----------

# ------------------------------------------------------------
# NOTE: The original T‑SQL script defines a PRIMARY KEY constraint
# (FactAccountsPayableId) and many FOREIGN KEY constraints. Delta Lake
# currently does not enforce PK/FK constraints, so they are retained
# here as comments for documentation purposes only.
# ------------------------------------------------------------
spark.sql("""
-- Primary Key (documented for reference; not enforced)
-- CONSTRAINT PK_FactAPCurrent PRIMARY KEY (FactAccountsPayableId)

-- Foreign Key constraints (documented for reference; not enforced)
-- FK_DimDueDateId            -> DWH.DimDate(DimDateId)
-- FK_DimReportDateId        -> DWH.DimDate(DimDateId)
-- FK_DimAccountingCurrency  -> DWH.DimCurrency(DimCurrencyId)
-- FK_DimGroupCurrency       -> DWH.DimCurrency(DimCurrencyId)
-- FK_DimReportingCurrency   -> DWH.DimCurrency(DimCurrencyId)
-- FK_DimTransactionCurrency -> DWH.DimCurrency(DimCurrencyId)
-- FK_DimCompany              -> DWH.DimCompany(DimCompanyId)
-- FK_DimIsOpenAmount         -> DWH.DimIsOpenAmount(DimIsOpenAmountId)
-- FK_DimOutstandingPeriod    -> DWH.DimOutstandingPeriod(DimOutstandingPeriodId)
-- FK_DimPurchaseInvoice      -> DWH.DimPurchaseInvoice(DimPurchaseInvoiceId)
-- FK_DimSupplier             -> DWH.DimSupplier(DimSupplierId)
""")

# COMMAND ----------

# MAGIC %md
# MAGIC ## Static Syntax Check Results
# MAGIC These are errors from static syntax checks. Manual corrections are required for these errors.
# MAGIC ### Spark SQL Syntax Errors
# MAGIC ```
# MAGIC Error in query 1: [PARSE_SYNTAX_ERROR] Syntax error at or near end of input. SQLSTATE: 42601 (line 1, pos 920)
# MAGIC
# MAGIC == SQL ==
# MAGIC EXPLAIN -- Primary Key (documented for reference; not enforced) -- CONSTRAINT PK_FactAPCurrent PRIMARY KEY (FactAccountsPayableId)  -- Foreign Key constraints (documented for reference; not enforced) -- FK_DimDueDateId            -> DWH.DimDate(DimDateId) -- FK_DimReportDateId        -> DWH.DimDate(DimDateId) -- FK_DimAccountingCurrency  -> DWH.DimCurrency(DimCurrencyId) -- FK_DimGroupCurrency       -> DWH.DimCurrency(DimCurrencyId) -- FK_DimReportingCurrency   -> DWH.DimCurrency(DimCurrencyId) -- FK_DimTransactionCurrency -> DWH.DimCurrency(DimCurrencyId) -- FK_DimCompany              -> DWH.DimCompany(DimCompanyId) -- FK_DimIsOpenAmount         -> DWH.DimIsOpenAmount(DimIsOpenAmountId) -- FK_DimOutstandingPeriod    -> DWH.DimOutstandingPeriod(DimOutstandingPeriodId) -- FK_DimPurchaseInvoice      -> DWH.DimPurchaseInvoice(DimPurchaseInvoiceId) -- FK_DimSupplier             -> DWH.DimSupplier(DimSupplierId)
# MAGIC --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------^^^
# MAGIC ```
